### ISSUE TITLE
Web and IIS Express profiles have different defaults

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Templates#113]
The IIS Express debug profile has a series of defaults (launch browser, Development env variable, etc.). It does not define a launchsettings.json file.

All other debug profiles have a different set of defaults (don't launch browser, no env variables, etc.). This may be appropriate for misc commands like EF, but the Web profile should have the same default settings as IIS Express.  I recommend adding a launchsettings.json file that matches the IIS Express defaults.

**Comment by Tratcher** [comment]
Almost all of my above comments still hold. Compare the tooling experience between `IIS Express` and `web`:
A) When I ctl+F5 from 'web' it doesn't launch the browser by default.
B) It does set `ASPNET_ENV` now but this variable name is outdated, it should be named `Hosting:Environment`
C) There's no option for me to specify the port `web` should start on.

**Comment by sayedihashimi** [comment]
Hi @Tratcher you're correct, the experience for the web command has not improved. It was originally scheduled for beta8 but was moved out in order to prioritize httpplatformhandler integration with IIS Express. We are working on the web command support now and hoping to release in the next round.

> B) It does set ASPNET_ENV now but this variable name is outdated, it should be named Hosting:Environment

Does @BillHiebert know the name changed?

**Comment by Tratcher** [comment]
Probably not, we added the new one months ago but have continued to support the old one.

**Comment by sayedihashimi** [comment]
I opened an issue in the internal tfs tracker 154196 to update the env var name as @Tratcher indicated above.

**Comment by rustd** [comment]
I am assuming nothing is required from templates side for this. Closing this out. Please reopen if there is anything needed.

**Comment by Tratcher** [comment]
We still need to verify that either tooling or templates provide reasonable defaults for "web"

**Comment by rustd** [comment]
Moving to rc2. Web and IISExpress should have the same defaults. @phenning this might require some tooling changes as well. Moving to rc2

**Comment by sayedihashimi** [comment]
With RC2 the concept of command is going away. Closing this now.

**Comment by Tratcher** [comment]
Commands will be gone, but there will still be launch profiles for non-IIS scenarios, correct?

**Comment by phenning** [comment]
@Tratcher, unknown at this time, but the defaults should be tracked under tooling, as templates should not drive this unless they are providing a launchSettings.json as part of the template content
