### ISSUE TITLE
Need more templates

### ISSUE THREAD

**Issue by dougbu** [aspnet/Templates#115]
MVC 6 project templates should include a test project template. And the main ASP.NET 5 Preview Templates / Web Application or ... / Empty templates should have a few more sub-options, enabling for example addition and removal of XML support, creation of a minimal MVC project, or adding in EF (without choosing Individual User Accounts authentication).

Hopefully this will allow the new project dialogue to enable the options shown below -- plus a few options specific to MVC 6.
![disabled project features](https://cloud.githubusercontent.com/assets/6431421/8257821/2a76a606-1665-11e5-8e75-cdb21473f6a1.png)

**Comment by miloush** [comment]
+1 on minimal MVC

**Comment by Eilon** [comment]
Closing because there are no plans to implement this.
