### ISSUE TITLE
Need to add a Test library template

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Templates#116]
Right now the only way to add a Test project is to do add a class library and then transition it into a test project. Problem with this is that when you create a new class library its target framework is `dotnet`. This is incompatible for test projects but can be very misleading when attempting to get a test project working.

**Comment by peterblazejewicz** [comment]
FYI: I've updated and tested xUnit.net template for RC1 for `generator-aspnet`. The PR waits for review, but it just works. The content is fully based on xUnit.net examples - as they are now supporting extensive documentation for example test and tooling usage:
https://github.com/OmniSharp/generator-aspnet/pull/498

**Comment by phenning** [comment]
Test projects are now also available in VS
