### ISSUE TITLE
Portions of MVC 6 template are not using safe project name

### ISSUE THREAD

**Issue by dougbu** [aspnet/Templates#118]
A brand-new MVC 6 project built using the Preview / Web Application template may contain a number of broken C# files. Repro steps:
1. Create a project from this template
2. Name solution MVC6.20150619
3. Observe namespace in `HomeController` is `MVC5._20150619.Controllers`
4. Observe namespace in `AccountController` is invalid (`MVC5.20150619.Controllers`)

**Comment by phenning** [comment]
TFS: [227406](https://devdiv.visualstudio.com/defaultcollection/DevDiv/_workitems?id=227406&_a=edit)

**Comment by phenning** [comment]
Fixed in new templates
