### ISSUE TITLE
Gruntfile template should use the correct casing for the filename

### ISSUE THREAD

**Issue by rustd** [aspnet/Templates#132]
Gruntfile template should use the correct casing for the filename #108
We should update the casing of the created file from  gruntfile.js  to  Gruntfile.js  since that is the standard. See related change in  yo aspnet  OmniSharp/generator-aspnet#229.

**Comment by spboyer** [comment]
reviewed all of the files all are consistent with `Gruntfile.js`, should be able to close this.

**Comment by peterblazejewicz** [comment]
:+1: 
also tested this

**Comment by rustd** [comment]
Thanks!
