### ISSUE TITLE
Need a SPA template

### ISSUE THREAD

**Issue by rustd** [aspnet/Templates#137]

**Comment by spboyer** [comment]
What are the components of the SPA we are looking for? Should we consider just an upgrade of the VS2013 HotTowel template? 

I'd propose
- angular 1.3.x 
- JavaScript and TypeScript options
- 2 - 3 views (routes)

More or less the same components of the HotTowel spa from previous versions

@madskristensen @sayedihashimi @johnpapa

**Comment by Eilon** [comment]
Closing because there are several SPA templates built-in as of .NET Core 2.0.
