### ISSUE TITLE
The carousel on the home page doesn't work with touch in Edge on Windows 10

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Templates#151]
The carousel on the home page supports swiping through the images on all browsers, except for Edge on Windows 10.

**Comment by peterblazejewicz** [comment]
This won't be updated any time soon as this specific package is no longer maintained:
https://github.com/ixisio/bootstrap-touch-carousel#this-package-is-no-longer-maintained-were-searching-for-contributors
also:
https://github.com/aspnet/Tooling/issues/155
https://github.com/aspnet/Templates/issues/194

**Comment by rustd** [comment]
#194 is tracking this
