### ISSUE TITLE
Usability: Remove "Project_Readme.html" from project

### ISSUE THREAD

**Issue by madskristensen** [aspnet/Templates#166]

**Comment by RehanSaeed** [comment]
Please consider using a check-list like ReadMe.html from [ASP.NET MVC Boilerplate](https://visualstudiogallery.msdn.microsoft.com/6cf50a48-fc1e-4eaf-9e82-0b2a6705ca7d) that gives you a TODO list of things to check/change in your project and also lets you check them off (I am using persist-js to store the check-list settings to local storage or another store if it is an older browser).

![checklist](https://cloud.githubusercontent.com/assets/2270364/10537763/e145b4ba-73eb-11e5-9b95-655171d0baf3.png)

I also use a few alerts at the top of the check-list to fix the most common problems I get a lot of emails about. Once again when you close one, it is persisted using persist-js.

![checklist 2](https://cloud.githubusercontent.com/assets/2270364/10537834/69c19804-73ec-11e5-84d4-b6bf63e315ab.png)

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/aspnet/Templates/blob/dev/README.md.
