### ISSUE TITLE
Usability: Open a global "Project_Readme.html" in VS browser on project creation

### ISSUE THREAD

**Issue by madskristensen** [aspnet/Templates#167]
A copy of the `Project_Readme.html` file should be written to disk (somewhere in the VS install directory) by setup authoring. When a new ASP.NET 5 project is created, the in-VS browser should open that file.

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/aspnet/Templates/blob/dev/README.md.
