### ISSUE TITLE
Remove Certain Assembly attributes from AssemblyInfo.cs

### ISSUE THREAD

**Issue by phenning** [aspnet/Templates#179]
This can be done after DNX starts flowing these from project.json

AssemblyTitle
AssemblyDescription
AssemblyCulture
AssemblyCopyright

https://github.com/aspnet/dnx/issues/2715

**Comment by rustd** [comment]
Runtime bugs are fixed so we can do this in RC1

**Comment by phenning** [comment]
Moving this to RC2 since we have removed the AssemblyInfo.cs by default in RC1, keeping bug active for when we add the item template.

**Comment by phenning** [comment]
Closing this, we'll do the right thing in #264
