### ISSUE TITLE
Welcome Page TagHelper link out of date

### ISSUE THREAD

**Issue by vkichline** [aspnet/Templates#196]
On the VSE Welcome to ASPNET 5 Preview page has a link to info about TagHelpers which points to a video from last year that's way out of date (https://channel9.msdn.com/Shows/Web+Camps+TV/Create-your-own-Domain-Specific-Language-in-ASPNET-with-TagHelpers.)  Taylor suggest pointing to out docs on asp.net.

**Comment by rustd** [comment]
Updated the link to point to http://docs.asp.net/projects/mvc/en/latest/views/tag-helpers/index.html
