### ISSUE TITLE
Add Resx Item template

### ISSUE THREAD

**Issue by rustd** [aspnet/Templates#199]
Add resx item template. This is basically the same content as existing one. I think we already have one but need to validate that it works since runtime and tooling added support for it.

**Comment by rustd** [comment]
@kirthik can you please provide @phenning with the content needed here for the item template.

**Comment by kirthik** [comment]
@BillHiebert since he was looking at it. He might have more context than me.

**Comment by rustd** [comment]
@phenning for a content we just need to add the same item template that was there for ASP.NET 4.6

**Comment by phenning** [comment]
Added.

**Comment by rustd** [comment]
@phenning please test that the following works with the Item template. Create a resource file with name "test" and VS generates  test.designer.cs. Create one with name  "test.fr-Fr" and VS should not generate a designer file for it.

**Comment by mota57** [comment]
this is 2017 and when I go to the menu 'add new item' in vs 2017 I can't find a option to create a resource file. Why is that? what is the solution?
