### ISSUE TITLE
This makes me VERY happy!

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Templates#205]
https://github.com/aspnet/Announcements/issues/79

Thanks for making it OSS.

**Comment by peterblazejewicz** [comment]
:+1:

**Comment by herecydev** [comment]
:+1:

**Comment by GerjanOnline** [comment]
:+1:

**Comment by TerribleDev** [comment]
:+1:

**Comment by rustd** [comment]
Thank you for the feedback :) I am closing this as this is not an issue anymore.
