### ISSUE TITLE
Translation of templates

### ISSUE THREAD

**Issue by agriffard** [aspnet/Templates#207]
Do you intend to translate the templates in other languages?
How would you structure the folders based on the culture to allow anyone to translate in his own language?
I would be happy to help to translate some files in French, the Project_readme.html for example .

May be I should also see if I can help to translate the Docs.

**Comment by rustd** [comment]
Templates will be translated into the languages Visual Studio ships in. Our process is to only localize content which is useful for developers such as error messages and instructions to enable social logins.
You can see the following repo for helping out with the docs. https://github.com/aspnet/Docs
