### ISSUE TITLE
Improve UX and markup of LogOff feature using built-in HTML button features

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Templates#214]
The small in one place could improve UX and code markup quality by ditching JavaScript + click here + to submit a form + retrieved by ID implementation that way:

``` diff
diff --git a/src/Rules/StarterWeb/IndividualAuth/Views/Shared/_LoginPartial.cshtml b/src/Rules/StarterWeb/IndividualAuth/Views/Shared/_LoginPartial.cshtml
index f774bb3..b236b97 100644
--- a/src/Rules/StarterWeb/IndividualAuth/Views/Shared/_LoginPartial.cshtml
+++ b/src/Rules/StarterWeb/IndividualAuth/Views/Shared/_LoginPartial.cshtml
@@ -2,12 +2,14 @@

 @if (User.Identity.IsAuthenticated)
 {
-    <form asp-controller="Account" asp-action="LogOff" method="post" id="logoutForm" class="navbar-right">
+    <form asp-controller="Account" asp-action="LogOff" method="post" class="navbar-right">
         <ul class="nav navbar-nav navbar-right">
             <li>
                 <a asp-controller="Manage" asp-action="Index" title="Manage">Hello @User.GetUserName()!</a>
             </li>
-            <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
+            <li>
+                <button type="submit" class="btn btn-link navbar-btn">Log off</button>
+            </li>
         </ul>
     </form>
 }
```

So, once clicked a button submits a form, as per HTML specs.

Without additional css the form will be rendered in default link color:

![image](https://cloud.githubusercontent.com/assets/14539/10466196/3b7855be-71f3-11e5-8203-8499fd00e8c4.png)

The color of link can be changed with single declaration added to site.css.

Is it OK to change this?

**Comment by keichinger** [comment]
This is more than reasonable for me. Why require JavaScript just to submit a form if one can also use a regular `<button type="submit"...>...</button>`.

**Comment by rustd** [comment]
Sure let's do this. Let's leave the color as it is. Can you send a PR?

**Comment by peterblazejewicz** [comment]
> Let's leave the color as it is.

There is no visual change after #225 PR
Thanks!
