### ISSUE TITLE
The hgroup markup is deprecated while still used in templates

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Templates#217]
Similarly to other topics:
[Consider Replacing obsolete `hgroup` tag in html code](https://github.com/aspnet/MusicStore/issues/523)
[Consider dropping obsolete hgroup element in web application templates](https://github.com/aspnet/Tooling/issues/159)
the `hgroup` element is now deprecated in HTML5 specs (though it still works in browsers):
The official wiki recommandation is explicit:

```
Don't use this anymore:
<hgroup>
 <h1>The reality dysfunction</h1>
 <h2>Space is not the only void</h2>
</hgroup>
```

https://www.w3.org/wiki/HTML/Elements/hgroup
Relevant code:
https://github.com/aspnet/Templates/search?l=csharp&q=hgroup&utf8=%E2%9C%93

I've posted examples how it could be replaced:
https://github.com/aspnet/MusicStore/issues/523#issue-99065216

Thanks!

**Comment by rustd** [comment]
We should replace hgroup by header and replace h2 by p tag. @peterblazejewicz do you want to send a PR?

**Comment by peterblazejewicz** [comment]
Sure thing - WIP

**Comment by peterblazejewicz** [comment]
done #217
Thanks!
