### ISSUE TITLE
Duplicated information for contributors

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Templates#218]
The project has its own specific contribution guide at the wiki:
https://github.com/aspnet/Templates/wiki/Contributing-to-Templates
Would it be ok to reword built-in GitHub contributing.md to host the same content (and still point to aspnet/home for general reference)?
The duplicated information is something to avoid I think
Thanks!

**Comment by rustd** [comment]
Updated instructions here. https://github.com/aspnet/Templates/blob/release/CONTRIBUTING.md
