### ISSUE TITLE
Advanced MVC and API Project Templates

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/Templates#221]
Please consider adding a template for MVC and API with little more than just the very basics. There are certain features that almost every site on the internet requires or would be nice to have. My [ASP.NET MVC Boilerplate](https://visualstudiogallery.msdn.microsoft.com/6cf50a48-fc1e-4eaf-9e82-0b2a6705ca7d) project has been fairly successful with 44,000 downloads in 11 months so there is definitely an appetite for it. I have seen sites popping up all over the internet using my template. I currently have an MVC template but am working on an API one too with many of the same features below but also including Swagger, JsonPatch etc. by default.

![mvc 6 preview image](https://cloud.githubusercontent.com/assets/2270364/10538370/e97bcd14-73ef-11e5-89bf-8458e1ac10be.png)
# Feature Selection
- Most features below can be turned on or off from a feature selection dialogue.

![featureselection1](https://cloud.githubusercontent.com/assets/2270364/10538277/67d01400-73ef-11e5-93f7-7e2b0271b001.png)

I have found that adding a feature selection wizard cuts down the need for multiple slightly different project templates and code duplication. More Settings:

![featureselection2](https://cloud.githubusercontent.com/assets/2270364/10538279/695a5d80-73ef-11e5-80de-b030d22cab33.png)
# ReadMe
- Include a full ReadMe.html file with a check list of activities to complete (See https://github.com/aspnet/Templates/issues/166). The check list settings are stored in local storage using persist-js.

![checklist](https://cloud.githubusercontent.com/assets/2270364/10538220/f45cfc4a-73ee-11e5-9e37-d6b61156dd2b.png)
# Secure By Default
- HTTPS Everywhere option which enables HTTPS with the HSTS and HPKP HTTP headers.
- Content Security Policy (CSP) HTTP Header using the NWebSec NuGet packages (Not yet available)
- Other HTTP headers provided by NWebSec like X-Content-Type-Options, X-Download-Options and X-Frame-Options.
- There is no Bower lib directory under wwwroot. We should not be serving up any Tom Dick or Harry's code from their GitHub project.
- Configure the anti-forgery tokens to rename the cookie names and form field names.
- User secrets config included by default.
# Fast By Default
- Turn on GZip compression by default.
- Cache things by default. Cache profile settings are stored in config.json.
- Add a image optimization Gulp task.
- Named routes used by default, rather than controller name and action name.
# Search Engine Optimization (SEO)

The default ASP.NET MVC template takes no consideration of Search Engine Optimization at all and is the biggest weakness IMHO. 
- Dynamically generated robots.txt file (Even a static one will do).
- Dynamically generated sitemap.xml file.
- Sitemap pinger service allowing you to ping Google and Bing your updated sitemap.
- Turn on append trailing slashes to URL's and making all URL's lower case by default.
- Redirect non-canonical URL's (URL's without a trailing slash or mixed case characters which are considered different URL's by search engines) to their canonical equivalent.
- Humans.txt file.
# Accessibility

4% of the world population is estimated to be visually impaired, while 0.55% are blind. ASP.NET MVC Boilerplate ensures that your site is accessible by adding aria attributes to your HTML mark-up and special shortcuts (Skip to main content) for people using screen readers.
# Browser Compatibility
- Include Favicons for popular browsers like iOS.
- Include a BrowserConfig.xml file for Windows favicons.
- Include a manifest.json file for Android favicons.
# Resilience and Error Handling
- Add an error page able to handle all status codes by default.
- Turn on IIS Dynamic IP Security in report mode.
- Fallback to local scripts if CDN fails. Using the tag helper to do this does not work if jQuery CDN fails and something else relies on jQuery.
- Include a 404 error page if no route is resolved.
# Easier Debugging and Performance Testing Tools
- Enable Glimpse when it comes out by default.
- Enable view pre-compilation in release mode by default.
- Include the runtime info page by default in Development.
- Include Browser Link by default in Development.
- Include logging by default.
# Patterns and Practices
- Use SCSS or LESS by default.
- Provides an option to use TypeScript. Includes a tsconfig.json file.
- Use constants instead of strings everywhere.
- Show an example JavaScript file using strict mode, IIFE and prototype pattern.
- Include Mocha JavaScript unit testing.
- Include JSHint Gulp task. Includes a .jshintrc file to configure it.
- Include JSCS Gulp task. Includes a .jscsrc file to configure it.
- Includes Font Awesome by default. Icons make everything look better.
# Atom Feed
- An Atom 1.0 has been included by default. PubSubHubbub 0.4 support has also been built in, allowing you to push feed updates to subscribers.
# Search
- Includes a search feature by default but leaves it open for you to choose how you want to implement it. It also implements Open Search XML right out of the box.
# Social Media Support
- Open Graph meta tags and Twitter Card meta tags are included by default. Not only that but ASP.NET MVC Boilerplate includes fully documented HTML and Tag helpers that allow you to easily generate Open Graph object or Twitter Card met tags easily and correctly.

I haven't even covered everything!

**Comment by alexdresko** [comment]
:+1: Rad.

**Comment by rustd** [comment]
I think a good way of surfacing these templates is through the Visual Studio gallery. In the Create experience in Visual Studio, a user can browse the gallery and install these advanced templates.

**Comment by rustd** [comment]
Please see the comment above.
