### ISSUE TITLE
Bootstrap 4?

### ISSUE THREAD

**Issue by alexdresko** [aspnet/Templates#222]
What version of Bootstrap is expected to ship with the new templates? If v3, is there a plan to somehow support v4 when it comes out?

Just yesterday I published a blog post illustrating my attempt to get ASP.NET 5 beta 7 working with Bootstrap 4 alpha and, for kicks, jQuery 3 alpha. http://www.alexdresko.com/2015/10/15/ride-the-dresko-wave/

It may not be the desired result, but I was able to create a working demo here... 

http://ridethedreskowave.azurewebsites.net/

Maybe that'll be useful for someone...

**Comment by peterblazejewicz** [comment]
The project dependencies are supposed to be upgarded for RC, see comments on Bootstrap 3.3.5 update issue not yet ported here:
https://github.com/aspnet/Tooling/issues/163
I think MS should first update BS to stable version but have version 4 in the labs
btw: https://github.com/peterblazejewicz/aspnet-5-bootstrap-4

**Comment by alexdresko** [comment]
Nice work, @peterblazejewicz! Of course I didn't take the time to go out and see if anyone else had done all of that work before I set out to do it myself, but I enjoyed the exercise anyway.

**Comment by rustd** [comment]
We will update to Bootstrap v3.3.5 since it is the latest stable version. Once Bootstrap v4 becomes stable we can consider updating to that version.
