### ISSUE TITLE
Consider adding .editorconfig for contributors

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Templates#226]
The code authors using VS studio most probably use built-in settings for source files, and even if VS does not have built-in support for EditorConfig:
http://editorconfig.org/
and even if VS 2015 seems to have broken support for plugin supporting `.editorconfig`:
https://github.com/editorconfig/editorconfig-visualstudio/issues/24
it would be nice if the VS built-in settings used in project are shared and available to contributors.
We could use that config file in all other editors to avoid unwanted commit changes and diffs.
Thanks!

**Comment by rustd** [comment]
This is not a templates issue. what change do you expect?

**Comment by peterblazejewicz** [comment]
The MS Team probably uses default settings in VS when formatting code. The could be nice for people using other editors to move that settings into commonly used EditorConfig file (I'm using such solution at work). That's like manifesto on how code should be formatted and some editors respect it by default (or via extension).
For example I have always to check if I'm not introducing side changes in commits just by adding or removing white space, etc.
Also related project like `generator-aspnet` could adopt that configuration to avoid unnecessary changes when updating content. The `generator-aspnet` uses `.editorconfig` - I use it for generator related content only thought.
Thanks!

**Comment by CADbloke** [comment]
ReBracer is another extension you can use to push standardized settings.

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/aspnet/Templates/blob/dev/README.md.
