### ISSUE TITLE
Inconsistent casing for configuration file item templates

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Templates#228]
I see 3 variations in casing used across the item template names for the 4 following templates:
1. Bower Configuration File
2. NPM configuration file
3. Gulp Configuration file
4. Grunt Configuration file

It seems as though the best practice is to capitalize the first letter of each word, in which case items 2 through 4 above need to be adjusted.

![config_file_naming](https://cloud.githubusercontent.com/assets/10702007/10568229/dd365dfc-75da-11e5-99d2-906f633a59ea.png)

**Comment by rustd** [comment]
Thank you for reporting this issue. #1 is the correct format.

**Comment by phenning** [comment]
Fixed for RC1
