### ISSUE TITLE
Switch to using LocalRedirect from AccountController

### ISSUE THREAD

**Issue by Eilon** [aspnet/Templates#231]
The API isn't implemented yet, see https://github.com/aspnet/Mvc/issues/3346

This could be used from the AccountController in several places.

Then remove the `RedirectToLocal` method in AccountController.

**Comment by rustd** [comment]
@phenning  aspnet/Mvc#3346 is fixed so we can update the templates in RC1

**Comment by phenning** [comment]
RedirectToLocal in the template does more then LocalRedirect does. LocalRedirect doesn't handle null or empty redirectUrls gracefully like Url.IsLocal does. We'll need a helper method anyway to handle this.
