### ISSUE TITLE
Authentication workflow problem when email confirmation is required.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Templates#242]
**TL;DR:**
User using external login provider and application with email confirmation required will be able to login the first time (on user creation) without confirming email and he/she won't be able to log in again.

---

When a visitor enter the page and hit login, then choosing an external provider, it's then redirected to username/email confirmation.

typing an email creates and account and log the user in. (user should be required to confirm email)
There's no email sending code in the ExternalLogin workflow.

if user logout and then try to login again, it's again presenting him the Associate account.

If he types in the same email address it says it's already taken.
If he types a new email address, it says Invalid login (already associated).

If he chooses to forgot password, then it's presented with a forgot password confirmation but not email sent because it's not confirmed.

Problems summary:
1. There's no way a user can log in (for a second time) in this scenario.
2. The user can use the system without email confirmation as long as he/she stays logged in when account was created.
3. No email confirmation is sent on this workflow.
4. Forgot password does **not** help.

**Comment by rustd** [comment]
The user should not get an Associate form when they login.

**Comment by Eilon** [comment]
This issue was moved to aspnet/templating#108
