### ISSUE TITLE
Review web templates for more accessible and context aware markup

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Templates#249]
As asked here: https://github.com/aspnet/Templates/pull/246#issuecomment-150343164

> @peterblazejewicz Can you open a separate issue to investigate whether there is anywhere else we should be using .sr-only? We'll take this PR as is for this specific instance.

The templates are to be reviewed to consists of clear, readable markup, for example - in case where Bootstrap 3._/4._, review where '.sr-only' class should be used  to support screen readers (look for carousel prominent component indicators markup as example). These also means 'fieldset', `label` elements in forms, [optional] `legend` in form, correct type for some markup elements (like 'submit' or 'cancel' for buttons, etc). After this the markup should be clean and just enjoyable to read :)

Thanks!

**Comment by rustd** [comment]
@peterblazejewicz do you want to take this one? If not then we can look into it.

**Comment by rustd** [comment]
As part of this we should see if we can automate the validation for HTML/ CSS/ Javascript.

**Comment by peterblazejewicz** [comment]
@rustd 
Sorry for missing this. It won't be possible back in Nov (I didn't have PC with at home). Now I have access to shared PC win at home with Win10/VS2015, so I could participate with VS based toolchain.
Thanks!

**Comment by rustd** [comment]
@peterblazejewicz Thank you! Let us know if you would like to work on this. 
We would also need to ensure that the templates pass all validator checks listed on https://validator.w3.org/

**Comment by Eilon** [comment]
This issue was moved to aspnet/templating#107
