### ISSUE TITLE
Remove SetBasePath(appEnv.ApplicationBasePath) from Templates

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Templates#251]
This is inferred now and doesn't need to be set.

/cc @divega @kirthik

**Comment by rustd** [comment]
@kirthik  please send a PR

**Comment by kirthik** [comment]
Working on it. Will send a PR soon.

**Comment by muratg** [comment]
@davidfowl Per https://github.com/aspnet/Templates/issues/269 this is not properly inferred, or it just doesn't work for user-secrets.  I recommend adding this back in templates for RC1.

cc @Eilon @danroth27

**Comment by Eilon** [comment]
#269 is open and assigned to @kirthik but she is OOF this week. We can discuss in the other bug.
