### ISSUE TITLE
Remove "NuGet.Config" from template

### ISSUE THREAD

**Issue by madskristensen** [aspnet/Templates#253]
The **NuGet.Config** file should be completely removed from the template until VS is able to deal with it.

~~The NuGet configuration file should not be included in the Solution Items folder, like it is today:~~

![nuget config](https://cloud.githubusercontent.com/assets/1258877/10702605/a071df9c-797f-11e5-96c1-e7d89574020c.png)

~~It should still be on disk, just not included in the Solution Items.~~

**Comment by phenning** [comment]
This is actually a tooling issue. Being tracked by TFS bug 153900

**Comment by davidfowl** [comment]
Wont fix :smile:

**Comment by phenning** [comment]
Do we still need the Nuget.Config for canary builds?

**Comment by madskristensen** [comment]
@DamianEdwards Should it be removed for Canary builds too?
