### ISSUE TITLE
The #243 change has introduced implicit paths

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Templates#254]
The #243 PR introduced implicit paths when using error handling middleware. I think that the change hides details of error handling middleware from new users and instead the explicit path argument should be used. In older version that was at least more obvious how error page is displayed (middleware > controller > view). Current change assumes some preexisting knowledge about MVC patterns and can be biased solution.
The docs.asp.net and official home repository samples are written in more obvious, explicit way and are not changed:
https://github.com/aspnet/Docs/blob/master/common/samples/WebApplication1/src/WebApplication1/Controllers/HomeController.cs#L30-L33
https://github.com/aspnet/MusicStore/blob/master/src/MusicStore/Controllers/HomeController.cs#L47-L50
Thanks!

**Comment by rustd** [comment]
Docs will get updated for these template changes when we release this. If you see for other controller actions we never specify the view name. It is inferred by convention.

**Comment by peterblazejewicz** [comment]
Thanks!
