### ISSUE TITLE
Move webroot:wwwroot from project.json to Microsoft.AspNet.Hosting.json

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Templates#257]
https://github.com/aspnet/Templates/blob/dev/src/BaseTemplates/EmptyWeb/project.json#L2
Microsoft.AspNet.Hosting.json:

```
{
  "Hosting:WebRoot": "wwwroot"
}
```

Or

```
{
  "Hosting":
  {
     "WebRoot": "wwwroot"
  }
}
```

@DamianEdwards? I don't recommend promoting WebRoot to a top-level element.
https://github.com/aspnet/dnx/issues/3035
https://github.com/aspnet/Hosting/issues/411

**Comment by Tratcher** [comment]
@davidfowl

**Comment by rustd** [comment]
@Tratcher rc1?

**Comment by Tratcher** [comment]
Yes, rc1

**Comment by phenning** [comment]
This has some tooling impact as well.

**Comment by Tratcher** [comment]
Feedback: remove the Microsoft.AspNet.Hosting.json file from the default templates. The runtime uses intelligent defaults and the file is only needed for customization.

**Comment by scottaddie** [comment]
The `gulpfile.js` file included in the StarterWeb template will need to be adjusted accordingly. It currently pulls in the `project.json` file via `require` and then accesses its `webroot` property.

**Comment by rustd** [comment]
@Tratcher Let's remove the file if the runtime has defaults. The gulpfile will have to be updated to hard code wwwroot as a path.
@Tratcher are you reverting your change?

**Comment by Tratcher** [comment]
I'll take care of the updates today
