### ISSUE TITLE
Updates to all WebApplication templates

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Templates#258]
project.json should look have `emitEntryPoint: true`:

``` JSON
{
  "webroot": "wwwroot",
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-*",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-*"
  },
  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel"
  },
  "frameworks": {
    "dnx451": { },
    "dnxcore50": { }
  },
  "exclude": [
    "wwwroot",
    "node_modules"
  ],
  "publishExclude": [
    "**.user",
    "**.vspscc"
  ]
}
```

The Startup class (of all templates, not just empty) should have a Main in it. See the example below:

``` C#
public class Startup
{
    // For more information on how to configure your application, visit http://go.microsoft.com/fwlink/?LinkID=398940
    public void ConfigureServices(IServiceCollection services)
    {
    }

    public void Configure(IApplicationBuilder app)
    {
        app.Run(async (context) =>
        {
            await context.Response.WriteAsync("Hello World!");
        });
    }

    public static void Main(string[] args) => WebApplication.Run<Startup>(args);
}
```

**Comment by SergeySypalo** [comment]
Hi David,
What "WebApplication" is stand for? I've updated project.json and Startup.cs in my "Blog" project, but Visual Studio cannot resolve WebApplication, proposing me to create property or field, generate class
Best regards, Sergey

**Comment by davidfowl** [comment]
It's a new API. Look at the hosting repository

**Comment by rustd** [comment]
Main should come before ConfigureServices. @davidfowl can you suggest a 1 line comment to let the user know why this is needed?
https://github.com/aspnet/Hosting/issues/430

**Comment by davidfowl** [comment]
Main should come last.

**Comment by davidfowl** [comment]
`// Bootstrap the Startup class`

**Comment by rustd** [comment]
How about this?
`// Entry point for the application.`

**Comment by Eilon** [comment]
@rustd that looks good to me.

**Comment by rustd** [comment]
@phenning please make this change. Note Main should come last.
