### ISSUE TITLE
Small fixes to Gulp/Grunt tasks files in OmniSharp/generator-aspnet#439

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Templates#259]
On the related project that directly uses VS templates there was a PR that changed some source code details in Gulp/Grunt tasks files:
OmniSharp/generator-aspnet#439
The `Gruntfile.js` is not published here, so it won't be possible to update that specific file via PR. 
Can someone review our PR and make updates - if decided to be useful?
Thanks!

**Comment by rustd** [comment]
In the VS templates, there is no Gruntfile. There was a change to the Gulpfile with these changes.
