### ISSUE TITLE
Be explicit about .bowerrc file creation with item template

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Templates#260]
When I want to add a new bower.json file, I select the Bower Configuration File item template via the Add --> New Item context menu item. The thing that comes as a surprise is that a .bowerrc file is also created. The "New Item" menu option implies that 1 item/file is being added, not two files. Please update the description which appears to the right of the item template (once selected), so that it provides some clarification. Right now, the description reads "Configuration file for Bower". My suggestion is to change the description to something like the following:

"Configuration files for Bower: bower.json and .bowerrc"

![untitled](https://cloud.githubusercontent.com/assets/10702007/10734834/2e13420a-7bd3-11e5-9c80-7de70b66c757.png)

**Comment by rustd** [comment]
This is a good suggestion. @phenning let's try to get this in for RC1 if we can.

**Comment by phenning** [comment]
Change to template description as suggested is in for RC1
