### ISSUE TITLE
Rename ASP.NET Configuration File item template's default file name

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Templates#261]
The "ASP.NET Configuration File" item template still uses the old default file name of "config.json" from Beta 7. It's my understanding that this file was renamed to "appsettings.json" with the Beta 8 release. I have the Beta 8 tooling installed and still see the old name.

![config_file](https://cloud.githubusercontent.com/assets/10702007/10735695/44525908-7bd7-11e5-97dc-ecdc7fbae163.png)

**Comment by rustd** [comment]
Thanks! yes we should change the name to appsettings

**Comment by phenning** [comment]
Renamed to appsettings.json for RC1
