### ISSUE TITLE
Remove AssemblyInfo.cs

### ISSUE THREAD

**Issue by madskristensen** [aspnet/Templates#263]
It is considered more of an edge case to use the AssemblyInfo.cs in an ASP.NET 5 project

**Comment by Eilon** [comment]
Why? How do I unit test my MVC controllers?

**Comment by Eilon** [comment]
That is, I probably need to set InternalsVisibleTo or whatever.

**Comment by phenning** [comment]
@Eilon You add the assembly info via the item template.

**Comment by Eilon** [comment]
Kind of a hassle, but ok... I don't see the harm in keeping it, though. But ok :smile:

**Comment by madskristensen** [comment]
Aren't you doing something wrong if you need to unit test your controllers? _Fat controller syndrom_

**Comment by Eilon** [comment]
My controllers are just big boned!
