### ISSUE TITLE
WIKI Building and running

### ISSUE THREAD

**Issue by Anderman** [aspnet/Templates#267]
For running the generated website you have to set dnvm to the correct version.
At this moment I must set my `dnvm use beta8` to run the web from release branche

```
dnvm use beta....
C:\git\Templates\artifacts\build\Test\StarterWeb [dev]> .\run.cmd web
```

**Comment by rustd** [comment]
@phenning thoughts?

**Comment by Anderman** [comment]
More. 
running the starterweb with `run web` works fine

The build will fail when setting the nuget resource to https://www.myget.org/F/aspnetlitedev/ in VS2015. 
and then opening the project in VS2015
Because this nuget feed (https://www.myget.org/F/aspnetlitedev/ ) doesn't seem to online anymore.

Try running this by 'run web` will fail now because  the this (https://www.myget.org/F/aspnetlitedev/) feed is used as primary???

VS2015 seems to work with these package sources

https://api.nuget.org/v3-flatcontainer/
https://www.myget.org/F/applicationinsights-sdk-labs/
https://www.myget.org/F/azureadwebstacknightly/
https://www.myget.org/F/roslyn-nightly/
https://www.myget.org/F/dotnet-corefx/
https://www.myget.org/F/aspnetrelease/api/v2/
https://www.myget.org/F/aspnetvnext/api/v3/flatcontainer/

**Comment by Anderman** [comment]
I found the main source why visual studio doesn't find package but run.cmd does.
Run.cmd uses more feeds and execute dnu restore as:

```
dnu restore 
    -f https://www.myget.org/F/aspnetvnext/api/v3/index.json 
    -f https://www.myget.org/F/applicationinsights-sdk-labs/ 
    -f https://www.myget.org/F/azureadwebstacknightly/ 
    -f https://www.myget.org/F/roslyn-nightly 
    -f https://www.myget.org/F/dotnet-corefx 
    -f https://api.nuget.org/v3/index.json 
    --packages C:\git\Other\Templates\tools\\..\packages
```

The feeds on building and running
- release=https://www.myget.org/F/aspnetrelease/
- dev=https://www.myget.org/F/aspnetlitedev/ (Give 404 error)

Visual studio uses another package cache then the run.cmd
To fix this. 

SET DNX_FEED to the same package cache if not already set and  start visual studio from the command line.

**Comment by rustd** [comment]
@Anderman Is this still an issue? Do we need to update the wiki?

**Comment by Anderman** [comment]
@rustd 
this feed `https://www.myget.org/F/aspnetlitedev/` should be replaced 
`https://www.myget.org/F/aspnetcidev/api/v3/index.json`

It looks that the SET DNX_FEED is not needed any more all the package are available from the dev feed.

**Comment by phenning** [comment]
Updated wiki with new instructions for running under dotnet cli
