### ISSUE TITLE
woff2 does not exists on https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/fonts/glyphicons-halflings-regular.woff2

### ISSUE THREAD

**Issue by Anderman** [aspnet/Templates#268]
Now the new templates used bootstrap 3.3.5 this font should be available on cdn.
see https://github.com/aspnet/Home/issues/959

**Comment by rustd** [comment]
Closing as this is not a template bug. aspnet/Home#959 is tracking this.

**Comment by mohisaini** [comment]
[glyphicons-halflings-regular.zip](https://github.com/aspnet/Templates/files/1028515/glyphicons-halflings-regular.zip)
Check font files in attached zip file, and add these into your local font folder.
