### ISSUE TITLE
usersecrets needed basepath to be set

### ISSUE THREAD

**Issue by Anderman** [aspnet/Templates#269]
after this commit https://github.com/aspnet/Templates/commit/8bfb2b42e5e6729205586c1fadbcf15ef4a14524

I can't use `builder.AddUserSecrets();`
When adding again `.SetBasePath(appEnv.ApplicationBasePath)` everything works fine

version: Clr-x86-1.0.0-rc1-15838

**Comment by rustd** [comment]
This is a regression. @kirthik We need to fix https://github.com/aspnet/UserSecrets/issues/47 for RC1. /cc @divega

**Comment by Eilon** [comment]
@rustd BTW @kirthik is OOF this week - do you have someone else who can revert the change for RC1?

**Comment by Anderman** [comment]
Sorry, I just tested this in the latest dev branches and it works fine

**Comment by muratg** [comment]
Closing based on @Anderman's comment.
