### ISSUE TITLE
Run gulp tasks on build

### ISSUE THREAD

**Issue by rustd** [aspnet/Templates#274]
Currently the gulp task are only hooked up to the prepublish event. Should they be hooked up to the build event as well so the tasks are run when you build the project.

As it is today, if you change site.css, you have to manually run the minification task. It would be nice to run it on build.

**Comment by scottaddie** [comment]
As an alternative to the build event idea, why not add a Gulp watch task that runs the CSS minification task upon saving the file? It might look something like the following:

``` javascript
gulp.task("watch", function(){
  gulp.watch([paths.css, "!" + paths.minCss], ["min:css"]);
});
```

**Comment by madskristensen** [comment]
I like the idea of the watch task. Then we can bind it to the Project Open event

**Comment by scottaddie** [comment]
It would be nice to do the same for JavaScript as well (see below). Want me to submit a PR for this?

``` javascript
gulp.task("watch", function(){
  gulp.watch([paths.css, "!" + paths.minCss], ["min:css"]);
  gulp.watch([paths.js, "!" + paths.minJs], ["min:js"]);
});
```

**Comment by madskristensen** [comment]
Hooking it up in project.json's postbuild event handler might be a good idea too. We did that a long time ago but it was removed again. I don't remember if that was due to perf reasons

**Comment by scottaddie** [comment]
@madskristensen - I see one problem with the "postbuild" script idea. The "watch" task will run twice, since I have both dnx451 and dnxcore50 defined in the `frameworks` section of `project.json`:

``` javascript
  "frameworks": {
    "dnx451": { },
    "dnxcore50": { }
```

Is there a way around this duplicate run when targeting multiple frameworks?

**Comment by scottaddie** [comment]
@madskristensen - One more question for you. Which of these implementations of the "watch" task do you prefer? Option 1 is obviously more concise, but Option 2 is consistent with how the `clean` and `min` tasks were created.

#### Option 1

``` javascript
gulp.task("watch", function () {
    gulp.watch([paths.css, "!" + paths.minCss], ["min:css"]);
    gulp.watch([paths.js, "!" + paths.minJs], ["min:js"]);
});
```

#### Option 2

``` javascript
gulp.task("watch:css", function () {
    gulp.watch([paths.css, "!" + paths.minCss], ["min:css"]);
});

gulp.task("watch:js", function () {
    gulp.watch([paths.js, "!" + paths.minJs], ["min:js"]);
});

gulp.task("watch", ["watch:js", "watch:css"]);
```

**Comment by madskristensen** [comment]
@scottaddie I like Option 1 the best

"postbuild" should not run the watch task. It should run the min tasks. Yes, they will run twice and that may be whey it was removed back then.

**Comment by scottaddie** [comment]
@madskristensen PR submitted: https://github.com/aspnet/Templates/pull/284

**Comment by scottaddie** [comment]
FYI, this PR has been merged. Anything else that needs to be addressed for this issue?

**Comment by phenning** [comment]
PR merged.
