### ISSUE TITLE
Add item template for .bowerrc

### ISSUE THREAD

**Issue by madskristensen** [aspnet/Templates#278]
The content of the file should be:

``` json
{
  "directory": "wwwroot/lib"
}
```

The template should show up everywhere the _Bower Configuration File_ template is

**Comment by phenning** [comment]
@madskristensen We already add a .bowerrc along with the bower.json when dropping the Bower Configuration File. Do we still want to drop the .bowerrc in that case?

**Comment by madskristensen** [comment]
This is for the case when you already have bower.json but not through our templates. It's not an RC1 issue

**Comment by Eilon** [comment]
Closing because we're not using Bower anymore anyway.
