### ISSUE TITLE
Add sensible defaults to templates that use logging

### ISSUE THREAD

**Issue by rynowak** [aspnet/Templates#286]
We've added a bunch of features to logging to improve the local dev story for use with the console logger. Most importantly we want to provide a sensible set of default logging levels for the console logging experience so that users aren't overwhelmed with spam. We want this filtering to more restrictive around log messages provided by the system, and not restrictive around log messages added by the developer, so a single level won't do.

This change adds a configuration file for logging as well as the startup code to wire it up. The configuration file approach is important as a jumping off point for more fine-tuning of what messages are included and excluded.

**Change to constructor**

```
            Configuration = builder.Build();
```

**Becomes**

```
            Configuration = builder.Build().ReloadOnChanged("appsettings.json");
```

**Change to `Configure(...)`**

```
            loggerFactory.MinimumLevel = LogLevel.Information;
            loggerFactory.AddConsole();
            loggerFactory.AddDebug();
```

**Becomes**

```
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();
```

**Add to appsettings.json**

```
{
  "Logging": {
    "IncludeScopes": false,
    "Switches": {
      "Default": "Verbose",
      "System": "Information",
      "Microsoft": "Information"
    }
}
```

**Add to project.json**

```
  "dependencies": {
    ...
    "Microsoft.Extensions.Configuration.FileProviderExtensions" : "1.0.0-*",
    ...
  },
```

**Comment by rustd** [comment]
@phenning we just updated the code changes.

**Comment by phenning** [comment]
e6d34253635d243e1d639d51b98ec038c00f1998
