### ISSUE TITLE
Move logger settings to their own config file

### ISSUE THREAD

**Issue by Eilon** [aspnet/Templates#298]
In their current form, both logger settings and other general app settings are in the same file. See https://github.com/aspnet/Templates/blob/dev/src/Rules/StarterWeb/IndividualAuth/appsettings.json for an example.

By being in a file with other content in it the file change notification will fire more frequently due to unrelated changes. Though it's technically harmless, it seems inefficient.

I recommend splitting the logger settings into their own file, e.g. `logging.json`.

@rynowak @lodejard any thoughts?

**Comment by lodejard** [comment]
Sounds good to me. Should we consider moving config files into Properties or Config folder, to help the app root look less busy?

**Comment by davidfowl** [comment]
Yea more files in the root will piss off @madskristensen  :smile:

**Comment by rynowak** [comment]
:+1:

**Comment by rustd** [comment]
I would like to keep the number of files that show up in app root. The way the template files are laid out it makes the approot less daunting.
Crazy idea: Can the reload logic look for the logging section and only refresh logging if the section changes?

**Comment by Eilon** [comment]
@pranavkm that's not the issue I'm worried about. It's just the fact that the file change notifier will trigger more than needed. It's semantically wrong, not technically wrong.

**Comment by Eilon** [comment]
Oops not @pranavkm , I meant @rustd :smile:

**Comment by sayedihashimi** [comment]
I'm agreeing with @rustd, and that we should keep the templates simple by default. I haven't heard any customer feedback on this and I believe that changing these settings is only happening every once in a while. Based on that I'll close this. If anyone is super passionate about this then grab me offline.
