### ISSUE TITLE
Proposal: Project templates should come in two flavours: With scaffolding code and without.

### ISSUE THREAD

**Issue by SetTrend** [aspnet/Templates#309]
Many Visual Studio project templates - particularly ASP.NET project templates - come with a vast amount of scaffolding/sample code.

It's nice to get this scaffolding code when learning a new version of the framework.

But later, when creating new projects from the same template, this scaffolding code becomes redundant and subject to immediate deletion. This is particularly true when new versions of auxiliary client/server frameworks emerge (e.g. jQuery, Entity Framework), thereby rendering the scaffolding code obsolete.

Wouldn't it be good to have two versions of each project template: One providing "how-to" scaffolding code, and another, providing nothing but project settings, app.config and one initial application start-up file (if any).

Here's my suggestion: I suggest to add a general checkbox to the "New Project" wizard in Visual Studio, providing an option to have Visual Studio create the project with scaffolding code added, or without.

A checkbox like `□ add scaffolding code` would do.

If the "add scaffolding code" option was checked, the following procedure might take place:
1. the empty template is created (mandatory)
2. additional scaffolding files, tagged as something like "IsScaffoldingItem" in the project template manifest, are added to the template

**Comment by rustd** [comment]
With the current experience where you have the following options:
- Empty Template
- Template with No Auth - Empty template + client side scripts + Server side code to return views.
- Template with Auth - Empty template + client side scripts + Server side code to return views + Authentication related code

Does this meet your requirements? or are you looking for something more?

**Comment by SetTrend** [comment]
I understand that this is an option particularly for ASP.NET templates. I want to suggest a more general approach for all the different Visual Studio templates.

TypeScript projects, for example, come with sample code. Unit tests come with sample code. Many other project templates come with sample code. Nice when opening such project types for the first time, but a waste of time for deleting all this sample code when creating new projects on a regular basis.

I have a strong feeling that this forum is the wrong one to suggest this but I was lead here. By the existing plethora of different MS GitHub projects it's hard to track which is the right one.

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/aspnet/Templates/blob/dev/README.md.
