### ISSUE TITLE
NuGet.Config should be renamed to NuGet.config

### ISSUE THREAD

**Issue by yukozh** [aspnet/Templates#310]

**Comment by Eilon** [comment]
@yishaigalatzer @davidfowl what was the final ruling on the recommended casing of this?

**Comment by davidfowl** [comment]
All lowercase

**Comment by yukozh** [comment]
Would the nuget.exe detect the nuget.config(all lower case) in linux？

**Comment by rustd** [comment]
There is no nuget.config in RC1.
