### ISSUE TITLE
Broken shortened link in Project_Readme.html files (404)

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Templates#312]
Originally reported on `generator-aspnet`:
https://github.com/OmniSharp/generator-aspnet/issues/459

The shortened link for `Add Web APIs with MVC 6` needs to be updated:
https://github.com/aspnet/Templates/search?utf8=%E2%9C%93&q=LinkId%3D518009

[http://go.microsoft.com/fwlink/?LinkId=518009](http://go.microsoft.com/fwlink/?LinkId=518009)

Thanks!

**Comment by rustd** [comment]
Fixed. Thanks!
