### ISSUE TITLE
Address the package.json missing fields warnings

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Templates#317]
During restoration of the npm packages, I noticed that the same 3 `package.json` warnings always appear in the Output window's "Bower/npm" view. It seems like the `description` field error would be an easy fix by simply adding something like the following to `package.json`:

``` json
"description": "ASP.NET StarterWeb template",
```

I'm not sure what to suggest for the other 2 field warnings, but it should at least be investigated.

![packagejsonwarnings](https://cloud.githubusercontent.com/assets/10702007/11158821/63a45746-8a20-11e5-9f74-b61f44c25036.png)

**Comment by scottaddie** [comment]
@madskristensen Thoughts on this one?

**Comment by madskristensen** [comment]
Since both `README` and `repository` will be empty, the warning will still show for those if we add a `description`. I don't think it matters unless we can get rid of all the warnings.

**Comment by rustd** [comment]
Can we close this?

**Comment by scottaddie** [comment]
As @madskristensen pointed out, eliminating the warnings for `README` and `repository` may be difficult; however, I still see value in providing a `description` field. It's one less line of noise that would appear in the Output window's "Bower/npm" view. I realize there are bigger fish to fry, but this seems like some low-hanging fruit that would be simple to fix.

**Comment by rustd** [comment]
I don't think fixing one matters since you will still get the warning. Closing this out as there is bigger fish to fry :)
