### ISSUE TITLE
Beta8 artifacts left in EF migration code for RC1

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Templates#318]
hi,
When doing updates for `generator-aspnet` I've found `beta8` references in migration:
https://github.com/aspnet/Templates/blob/f244988958b0744592532093f145fbf37d9fa40f/src/Rules/StarterWeb/IndividualAuth/Migrations/00000000000000_CreateIdentitySchema.Designer.cs#L20
https://github.com/aspnet/Templates/blob/5605c55164a872fcf839d24cbcb1caa5b7e9306c/src/Rules/StarterWeb/IndividualAuth/Migrations/ApplicationDbContextModelSnapshot.cs#L19
while the issue for rc1 is stating migration is done:
https://github.com/aspnet/Templates/commit/0b9137d192ee6221edad74fc4c1198f2f3ff6414

Thanks!

**Comment by rustd** [comment]
@rowanmiller  the RC templates have this in the migrations file. Does this matter for RC1?

``` C#
HasAnnotation("ProductVersion", "7.0.0-beta8")
```

**Comment by rowanmiller** [comment]
I can't think of any issues that would cause, we don't currently consume that info anywhere. The does suggest the migration files haven't been regenerated for a while... we should do that.

**Comment by rustd** [comment]
@phenning this is what we chatted where Migrations should be generated as part of build so we can automate this.

**Comment by phenning** [comment]
A fair amount of engineering effort is required to automate this, so we will instead for now update the migrations a few times a milestone.

**Comment by phenning** [comment]
098ddaa15d5db61f56be3823be1097ad9163e79e
