### ISSUE TITLE
Item Templates should be in GitHub

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Templates#32]
Right now we only have project templates in this repo. We should expand this to also include item templates. That way people can recommend/PR new item templates.

**Comment by sayedihashimi** [comment]
We should open source the item templates as well. I'll work with @rustd and others to see if we can make that happen.

**Comment by joeloff** [comment]
We're going to have to duplicate content to do that as some files are currently shared across multiple item templates for different project types like WAP/WSP

**Comment by sayedihashimi** [comment]
@joeloff thanks for the info

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/aspnet/Templates/blob/dev/README.md.
