### ISSUE TITLE
WebApplication.Run and default project names

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Templates#320]
hi,

I've run into following problem
With `rc1` there is new way to bootstrap and run application in startup:
https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNet.Hosting/WebApplication.cs
https://github.com/aspnet/Templates/pull/270

```
// Entry point for the application.
public static void Main(string[] args) => WebApplication.Run<Startup>(args);
```

The problem is that there is a `WebApplication` concept and in tools like `generator-aspnet` we are reusing that concept to generate `WebApplication` project (with `WebApplication` namespace). 
I think that problem was overlooked when conceiving solution to bootstrap and run app as VisualStudio creates `WebApplication1`, `WebApplication2`, and so on.
I think that problem should be possible to recreate with VS by using `WebApplication` project name (I don't have Windows OS at home, sorry):

```
/Users/piotrblazejewicz/development/WebApplication/Startup.cs(106,51): 
DNXCore,Version=v5.0 error CS0234: 
The type or namespace name 'Run' does not exist in the namespace 'WebApplication' 
(are you missing an assembly reference?)

Build failed.
    0 Warning(s)
    2 Error(s)
```

The fix is to use FQCN:

```
public static void Main(string[] args) => Microsoft.AspNet.Hosting.WebApplication.Run<Startup>(args);
```

I know it is ugly, but `WebApplication` is just such generic term.
I think we will just use FQCN in `generator-aspnet` to overcome that problem. But I want to know your stance on this.
Thanks!

**Comment by rustd** [comment]
Using the FQCN in generator-aspnet is fine. Depending on how this issue https://github.com/aspnet/Hosting/issues/482 gets resolved, we can decide what the long term fix would be.

**Comment by rustd** [comment]
@phenning Let's add the FQCN to the templates as a workaround.

**Comment by peterblazejewicz** [comment]
Thanks guys!

**Comment by CumpsD** [comment]
What is the new way in rc2? `WebApplication` seems to be gone?

**Comment by maartenmensink** [comment]
@CumpsD seems to be moved to using Microsoft.AspNet.Hosting.Internal;

The .Run<Startup> method seems to be missing.

**Comment by phenning** [comment]
@CumpsD RC 2 way:

```
    public static void Main(string[] args)
    {
        var host = new WebHostBuilder()
            .UseServer("Microsoft.AspNetCore.Server.Kestrel")
            .UseApplicationBasePath(Directory.GetCurrentDirectory())
            .UseDefaultConfiguration()
            .UseIISPlatformHandlerUrl()
            .UseStartup<Startup>()
            .Build();

        host.Run();
    }
```
