### ISSUE TITLE
Add a t4 item template

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/Templates#321]
In ASP.NET 5 RC1 we are adding support in VS for .t4 files.

We should add an item template to create a .t4 file. The content should be consistent with the standard C# .t4 file. Maybe we can even use the same item template. This is needed for the next release to make it easier for users to get started with t4 in ASP.NET 5 projects.

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/aspnet/Templates/blob/dev/README.md.
