### ISSUE TITLE
rc1 default template not generating the same as beta8 [cross-post]

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Templates#327]
This is cross-posted feedback from [aspnet/Announcements](https://github.com/aspnet/Announcements/issues/117) project:

> (mostly) identical html/bootstrap is not rendering the same in the default template. see images. all I did was create a beta8 mvc with individual account, and the same in rc1
> ![https://cloud.githubusercontent.com/assets/15947066/11308164/dc6b3c72-8f79-11e5-90bc-35385476cb9d.png](https://cloud.githubusercontent.com/assets/15947066/11308164/dc6b3c72-8f79-11e5-90bc-35385476cb9d.png)
> ![https://cloud.githubusercontent.com/assets/15947066/11308168/dea8eade-8f79-11e5-8188-cbe23d3b2d94.png](https://cloud.githubusercontent.com/assets/15947066/11308168/dea8eade-8f79-11e5-8188-cbe23d3b2d94.png)

https://github.com/aspnet/Announcements/issues/117

/cc
@madmunsterdaddy

**Comment by natelaff** [comment]
sorry I posted it there! it was a mistake.

**Comment by peterblazejewicz** [comment]
The second problem with checkbox having negative offset is a known problem with tag helpers:
https://github.com/aspnet/Mvc/issues/2369
There is no clean solution for that problem yet, unless written by hand or with additional CSS (just to fix rendering) - both are not nice for templates.

**Comment by rustd** [comment]
The first issue is because we switched away from bootstrap touch carousel and are using bootstrap carousel.
The second one we need to address.

**Comment by peterblazejewicz** [comment]
@rustd 
- the first issue requires custom css to be added:
  https://github.com/ixisio/bootstrap-touch-carousel/blob/master/src/less/carousel.less#L88-L95
- the second issue requires custom markup, I've made one already elsewhere:
  https://github.com/peterblazejewicz/aspnet-5-bootstrap-4/blob/abeac62e0738e5a62fb42faf1b43baffeaff4608/WebApplication/Views/Account/Login.cshtml#L37-L39

I'll made two different PR, so you guys could decide.
Thanks!
