### ISSUE TITLE
A 404 error for `Project_README.html`s `Add a Controller and View` shortened link

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Templates#334]
These links:
https://github.com/aspnet/Templates/search?l=html&q=Add+A+Controller&utf8=%E2%9C%93
are not broken (404):

```
<li><a href="http://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
```

Also: https://github.com/aspnet/Tooling/issues/294

Thanks!

**Comment by rustd** [comment]
Fixed. Landing page is https://docs.asp.net/projects/mvc/en/latest/getting-started/first-mvc-app/index.html
