### ISSUE TITLE
Losing special characters and accents

### ISSUE THREAD

**Issue by penihel** [aspnet/Templates#335]
I have this problem when I put a message with accent on the View.
Example on .cshtml:

``` html
"Uma inscrição com este E-mail já foi realizada"
```

But, the browser output

```
"Uma inscri��o com este E-mail j� foi realizada"
```

and it happens too when I put a message to be displayed in the ValidationSummary.

See on Action (Controller)

``` c#
 ModelState.AddModelError("", "Uma inscrição com este E-mail já foi realizada");
```

On View

``` html
 <div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
```

Or when i put the string in ViewBag/Viewdata

``` c#
ViewBag.Test = "Uma inscrição com este E-mail já foi realizada"
```

But, the browser output

```
Uma inscri��o com este E-mail j� foi realizada
```

See a similar problem here:[/aspnet/Configuration/issues/241](https://github.com/aspnet/Configuration/issues/241)

**Comment by penihel** [comment]
I think that i found the problem.

Some files from template (all views *.cshtml and others...) are in ASCII encoding.
So i changed the encoding to UFT8,  and then the most of the problems was solved.

but i'm still checking all cases...

**Comment by phenning** [comment]
It looks like the template content is correctly set to UTF-8 with BOM in the Common7\IDE\WebTemplates\DNX\CSharp\1033 folder, so it doesn't look like a problem with the templates themselves, but it looks like it may be an issue farther downstream.

**Comment by rustd** [comment]
@penihel Can you please outline detailed repro steps on how did you create a project and these files?

**Comment by penihel** [comment]
hi @rustd
I've installed the latest version of VS2015 and ASP.NET WEB tools
I created a ASPNET5 Default Template Project.

I just follow this tutorial https://docs.asp.net/en/latest/tutorials/your-first-aspnet-application.html

When i add a new **"Add Scaffold "** controller in option **"MVC 6 Controller with views, using Entity Framework"**, then all added files (controller and views) are in ASCII enconding.

You know ?

**Comment by rustd** [comment]
Thank you. This is an issue with the files being added by Scaffolding. I have opened https://github.com/aspnet/Scaffolding/issues/151
