### ISSUE TITLE
Bootstrap updated to 3.3.6 version

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Templates#340]
The BS has been updated to 3.3.6:
http://blog.getbootstrap.com/2015/11/24/bootstrap-3-3-6-released/
https://github.com/twbs/bootstrap/releases/tag/v3.3.6
https://github.com/twbs/bootstrap/issues?q=milestone%3Av3.3.6+is%3Aclosed

An update to templates could be quick for most of contributors, but it should not be done without updating MS Ajax CDN resources to support 3.3.6 first:
[Bootstrap Releases on the CDN](http://www.asp.net/ajax/cdn#Bootstrap_Releases_on_the_CDN_14)

You could accepts PR related to 3.3.6 version but you should not merge them or release them before CDN is updated.

So this issues is in fact a request to provide BS 3.3.6 version on MS Ajax CDN, so the project could adopt updates from BS.

:+1: 

Thanks!

**Comment by rustd** [comment]
Thank you. This is not an issue with the Templates so I am closing this. We will follow it up and update CDN.

**Comment by peterblazejewicz** [comment]
Sure!

**Comment by peterblazejewicz** [comment]
This is no longer issue, CDN is updated:
http://www.asp.net/ajax/cdn#Bootstrap_Releases_on_the_CDN_14
