### ISSUE TITLE
Upgrade dnx451 framework references

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Templates#341]
I'm specifically talking about the "StarterWeb", "EmptyWeb", and "WebAPI" templates; however, this may apply to other templates as well. In the `project.json` files, we have this:

``` json
  "frameworks": {
    "dnx451": { },
    "dnxcore50": { }
  },
```

Shouldn't the `dnx451` references be replaced with either `dnx452` or `dnx46`? Since support for .NET 4.5.1 ends on January 12th (as noted [here](https://support.microsoft.com/en-us/gp/framework_faq)), it seems logical. Let me know if a PR should be submitted for this.

**Comment by phenning** [comment]
@scottaddie, This should be handled by #160  We've had issues with everything working as expected this prior to RC2, so we ended up rolling back the changes. We'll be reintroducing this back into the templates for RC2, as the Visual Studio tooling changes are already (mostly) done.

**Comment by rustd** [comment]
#160 is a generic fix for this.
