### ISSUE TITLE
[Dotnet CLI] Template changes for 

### ISSUE THREAD

**Issue by muratg** [aspnet/Templates#342]
``` JSON
{
   "server": "Micrsoft.AspNet.Server.Kestrel"  
}
```

cc @davidfowl

**Comment by rustd** [comment]
@muratg Can you please add more details on what needs to be changed?

**Comment by muratg** [comment]
I believe @davidfowl was talking about the "server" field. Not sure what else is needed.

**Comment by rustd** [comment]
@muratg please add more details on what change is required.

**Comment by muratg** [comment]
@rustd Add to `project.json`:

```
{
   "server": "Micrsoft.AspNet.Server.Kestrel"  
}
```

@davidfowl / @Tratcher  anything else needed?

**Comment by Tratcher** [comment]
Not project.json, that goes in hosting.json.

**Comment by Tratcher** [comment]
@JunTaoLuo, sync up with @rustd about all your recent hosting changes.

**Comment by muratg** [comment]
Yeah, my bad, `hosting.json`

**Comment by JunTaoLuo** [comment]
Please take a look at https://github.com/aspnet/Announcements/issues/131

**Comment by phenning** [comment]
Looking at the announcement, it looks like we've done all the required updates.

Closing this out.
