### ISSUE TITLE
Add UseOverrideHeaders to templates

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Templates#343]
x-forwarded-for and x-forwarded-proto support are being removed from UseIISPlatformHandler. Add UseOverrideHeaders to the templates to handle these headers.
https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNet.HttpOverrides/OverrideHeaderExtensions.cs

There's some pending feature work for UseOverrideHeaders that will require configuration, so talk to me before you add it.

**Comment by Tratcher** [comment]
UseIISPlatformHandler is only needed for Windows Auth at the moment. We'll add client certs to it as well during RC2.

**Comment by rustd** [comment]
@Tratcher let us know when the changes are done.

**Comment by Tratcher** [comment]
The following middleware should go early in the pipeline, before any auth middleware or anything else that might consider the request scheme:

```
            app.UseForwardedHeaders(new ForwardedHeadersOptions
            {
                ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
            });
```

And UseIISPlatformHandler is now only needed for windows authentication and client certificate scenarios.

**Comment by Tratcher** [comment]
Reference: https://github.com/aspnet/BasicMiddleware/blob/dev/samples/HttpOverridesSample/Startup.cs

**Comment by phenning** [comment]
@Tratcher 

A few questions:
In Main(), I noticed we now have  .UseIISPlatformHandlerUrl(). 

Is this now needed for all scenarios?  Should we not include this for the service fabric scenarios?

Do we want/need to add the forwarding code for ALL scenarios, include the NoAuth and Empty templates?

**Comment by Tratcher** [comment]
`UseIISPlatformHandlerUrl` should be in main for any template you'd expect to run in IIS. It probably doesn't apply to service fabric. @glennc?

@rustd @DamianEdwards how about Empty? I think you'd remove UseIISPlatformHandler that's currently there and replace it with UseForwardedHeaders. Otherwise your request scheme can be wrong. https://github.com/aspnet/Templates/blob/dev/src/BaseTemplates/EmptyWeb/Startup.cs#L24

**Comment by phenning** [comment]
We need to keep UseIISPlatformHandler in the templates since you can change to windows auth via the property page, and we do not want to inject code into Startup.cs to enable this.

**Comment by rustd** [comment]
sounds good to me. @Tratcher ?

**Comment by Tratcher** [comment]
_shrug_ it's harmless.

**Comment by sayedihashimi** [comment]
Closing based on @rustd comments
