### ISSUE TITLE
dev branch feed listed in wiki not found

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Templates#345]
The wiki lists a "dev" branch myget.org feed in the Visual Studio section [here](https://github.com/aspnet/Templates/wiki/Building-and-Running#visual-studio). When navigating to that link or when attempting to connect to it from Visual Studio, a not found error is returned:

![myget_feed](https://cloud.githubusercontent.com/assets/10702007/11646775/c09f3524-9d26-11e5-8e52-e43decbb9905.png)

**Comment by phenning** [comment]
Updated wiki
