### ISSUE TITLE
Update Project_readme

### ISSUE THREAD

**Issue by rustd** [aspnet/Templates#347]

**Comment by sayedihashimi** [comment]
Is this happening for rc2? Do we have an updated design?

**Comment by rustd** [comment]
RC2 is only about content updates for branding etc. Please track the updated design work separately.

**Comment by sayedihashimi** [comment]
@rustd are we updating links for RC2? If so do you have the final links?

**Comment by rustd** [comment]
The page should be updated for the branding change. If anything is missing then we can update the content now.

**Comment by rustd** [comment]
Closing #472 is tracking the remaining work
