### ISSUE TITLE
Update JS and CSS libraries to latest available version

### ISSUE THREAD

**Issue by rustd** [aspnet/Templates#348]

**Comment by rustd** [comment]
Here are the versions:
Bootstrap                         3.3.6
jQuery                              2.2.0
JSON.NET                         ~~8.0.2~~ 8.0.3

**Comment by ajaybhargavb** [comment]
Made a change to the above JSON.NET version
cc' @Eilon

**Comment by phenning** [comment]
#452 only updates jQuery and bootstrap
