### ISSUE TITLE
Unify conventions of using built-in Configuration providers in templates

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Templates#350]
I've found this when moving content between different web projects. The configuration sections are sometimes different in web templates. For example:
https://github.com/aspnet/Templates/blob/dev/src/BaseTemplates/StarterWeb/Startup.cs#L18-L20

```
// Set up configuration sources.
var builder = new ConfigurationBuilder()
  .AddJsonFile("appsettings.json")
  .AddEnvironmentVariables();
```

https://github.com/aspnet/Templates/blob/dev/src/Rules/StarterWeb/AI/IndividualAuth/Startup.cs#L23-L36

```
var builder = new ConfigurationBuilder()
    .AddJsonFile("appsettings.json")
    .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true);
...
builder.AddEnvironmentVariables();
```

https://github.com/aspnet/Templates/blob/dev/src/Rules/WebAPI/AI/NoAuth/Startup.cs

```
// Set up configuration sources.
var builder = new ConfigurationBuilder()
    .AddJsonFile("appsettings.json");
...
builder.AddEnvironmentVariables();
```

I mean: that is standard routine/convention and it could be beneficial to unify it the sources.

Thanks!

**Comment by rustd** [comment]
All the non Windows Authentication templates should be similar.
