### ISSUE TITLE
Add information about how to enable development mode to Error.cshtml

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/Templates#351]
Development mode (`IHostingEnvironment.IsDevelopment()`) is only set by default when running from VS. This means if you run from OSX/Linux (without setting the environment variable) you just get Error.cshtml rather than our more helpful error pages.

We should add some info to Error.cshtml instructing folks how to enable development mode if they want to see more info (with a warning not to do it in production). This is a similar idea to what we used to do with the yellow screen of death.

**Comment by rowanmiller** [comment]
@rustd this is part of the overall improvements to make database stuff easier. This bit would help with local development, when you are outside of VS. It would help you end up on the Database Error Page to help with migrations. Any pushback on the idea?

**Comment by rowanmiller** [comment]
I'm happy to work on the changes if the idea seems ok

**Comment by rustd** [comment]
When you are outside of VS, most likely you will get the templates through yo. So shouldn't this change be in the yo generators only?

I am open to seeing your changes

**Comment by peterblazejewicz** [comment]
@rowanmiller 
Start issue or PR on generator/aspnet.
Some additional information is added to generator as compared to VS (e.g. Dockerfile's). The entry in unit test will be created to cover availability of added content in source files to avoid override during updates from VS templates.
Thanks!

**Comment by sayedihashimi** [comment]
It should not be limited to `yo aspnet`, users can run into this if a project is created in VS and then a team member using OS X starts developing the application. The changes should go into both the VS templates as well as `yo aspnet`. Also users in VS can set the config setting to Production where they would run into this as well.

@rowanmiller do you have some specific changes in mind? If you could attach an updated error.cshtml we can discuss it here.

**Comment by rowanmiller** [comment]
> It should not be limited to  yo aspnet , users can run into this if a project is created in VS and then a team member using OS X starts developing the application.

:+1: 

I can put together some proposed changes

**Comment by rustd** [comment]
@rowanmiller once you have a proposal we can consider this for 1.0 release

**Comment by rowanmiller** [comment]
PR is out for review https://github.com/aspnet/Templates/pull/431
