### ISSUE TITLE
Return URL persistence in ASP.NET 5 web application template with individual accounts

### ISSUE THREAD

**Issue by joshcomley** [aspnet/Templates#359]
The template does not currently persist any return URL information as you navigate around registering for a new account, for example. Return URLs are standard in the login process. The links and forms need to be updated to persist this data, one such solution is outlined in my blog post here:

http://overengineer.net/Using-OpenIddict-to-easily-add-token-authentication-to-your-.NET-web-apps/#almost-done

**Comment by kevinchalet** [comment]
:+1: :clap: 

/cc @HaoK

**Comment by rustd** [comment]
This is a good suggestion. @joshcomley would you be open to sending a PR to the templates repo?
