### ISSUE TITLE
Update templates for Hosting API changes

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Templates#361]
Announcement was posted for Hosting API updates here: https://github.com/aspnet/Announcements/issues/131

The main changes required for templates are 
1. `project.json`
   Remove `webroot` property. This is read from `hosting.json` now and is defaulted to `wwwroot` so it's most likely not required.
   Update the `web` command to be the name of the assembly, which is in general the name of the app
   Add `"emitEntryPoint": true` to `compilationOptions`.
2. `hosting.json`
   Add `"server": "Microsoft.AspNet.Server.Kestrel"` to specify the server to be used for self host.
3. Startup.cs
   Add a `Main`:

``` c#
       public static void Main(string[] args)
        {
            var application = new WebApplicationBuilder()
                .UseConfiguration(WebApplicationConfiguration.GetDefault(args))
                .UseStartup<Startup>()
                .Build();

            application.Run();
        }
```

As an example, look at the changes made to samples in  https://github.com/aspnet/Diagnostics/commit/c476f91152f8b1e25a52f37e8a744f2c5bf2b293 and https://github.com/aspnet/KestrelHttpServer/commit/bd10d507f8d9530d601ed17edce1c6d0b0e19f15.

**Comment by davidfowl** [comment]
This might need some tweaking while we finalize some APIs.
