### ISSUE TITLE
EF command in RC2 in Individual Auth template.

### ISSUE THREAD

**Issue by phenning** [aspnet/Templates#364]
See comment here:
https://github.com/aspnet/Templates/pull/363/files#r48389518

"The reason why we removed multiple commands in our samples is to prepare for the move towards dotnet cli where commands don't exist. Maybe we should do the same here and remove ef ."

**Comment by rustd** [comment]
@rowanmiller  FYI. How would a user run EF migrations in RC2?

**Comment by rowanmiller** [comment]
We'll have EF commands in whatever the CLI commands story ends up being. And Package Manager Console commands should light up for RC2 as well.

**Comment by rustd** [comment]
Should the EF command be there and if how should it be registered?

**Comment by rowanmiller** [comment]
EF commands are just standard .NET CLI commands, here is what you want in the project.json

```
  "tools": {
    "dotnet-ef": "1.0.0-*"
  },
```

**Comment by rustd** [comment]
Thanks! What is the package name of the tool and are the changes available in coherence-signed builds? Or put it differently when were these changes checked in for EF?

**Comment by phenning** [comment]
I've seen this in the current builds I'll update the template this week. We are already including the tool package in the package cache.
- Phil

On Mar 7, 2016, at 4:16 PM, Pranav Rastogi <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks! What is the package name of the tool and are the changes available in coherence-signed builds? Or put it differently when were these changes checked in for EF?

**Comment by rustd** [comment]
@phenning can you please do this before Thursday so I can include this in the templates review.
