### ISSUE TITLE
Poor user and dev experience in Identity email confirmation

### ISSUE THREAD

**Issue by natelaff** [aspnet/Templates#365]
There are two issues using the default template for identity when using email confirmation.

Following the guide here: http://docs.asp.net/en/latest/security/authentication/accconfirm.html

Poor user experience: When you click "Register" it sends the email off, but just redirects the user to the Home controller. Redirecting to something else to indicate they have to confirm their account would be a better example. Perhaps the default template should have such a view OOTB.

Poor dev experience: When logging in with an external account (lets say Facebook) if the account doesn't exist you get thrown into AccountController.ExternalLoginConfirmation, great. This screen requires an email, so you complete the registration then you're logged in but never shoots off the email confirmation link here. Perhaps a commented out section in this action to deal with this would improve the dev experience here.

**Comment by rustd** [comment]
Thank you for your suggestion. We will look into improving this.

**Comment by Ponant** [comment]
When will this be addressed? It is one year old. A related issue [https://github.com/aspnet/Templates/issues/832](https://github.com/aspnet/Templates/issues/832) .

**Comment by Eilon** [comment]
This issue was moved to aspnet/templating#124

**Comment by Eilon** [comment]
This issue was moved to aspnet/templating#125
