### ISSUE TITLE
Consider removing WebAPI shim from the template

### ISSUE THREAD

**Issue by rynowak** [aspnet/Templates#366]
We've got enough stuff in the template, this just seems like noise. 

We haven't had a lot of positive feedback about the shim being definitely useful, or much feedback about confusion/difficulty of porting legacy webapi code to MVC6. 

Should we just take it out?

**Comment by rustd** [comment]
@rynowak where are you seeing the shim? Can you point to the code file?

**Comment by davidfowl** [comment]
Did we remove it? I can't find it.

**Comment by rustd** [comment]
We removed it in RC1
