### ISSUE TITLE
Split Startup into Program.cs and Startup.cs

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Templates#367]
Something like this https://github.com/davidfowl/dotnetcli-aspnet5/tree/master/HelloWeb. So we have a clear separation between the Startup logic and the hosting logic.

/cc @DamianEdwards @lodejard @Tratcher @glennc

**Comment by DamianEdwards** [comment]
Agreed

**Comment by phenning** [comment]
PR Sent on this.

**Comment by phenning** [comment]
Merged 7a22d5767ed58375758fc218ffa02e7dbdec1023
