### ISSUE TITLE
Invalid package.json name property value

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Templates#369]
Per the `package.json` file's [property specs](https://github.com/npm/validate-npm-package-name#naming-rules), the `name` property's value cannot contain uppercase letters. The quickest way to test this is to open a command shell and run `npm init`:

![package_json_name](https://cloud.githubusercontent.com/assets/10702007/12124220/73fd76f0-b3aa-11e5-9396-7a359d89aa26.png)

The default value in the ASP.NET 5 templates is "ASP.NET", which violates the spec. I can submit a PR to address the project templates, but are there any preferences on a new value?

The "NPM Configuration File" item template will also need to be changed to reflect this new value, as it currently contains this:

``` json
{
    "version": "1.0.0",
    "name": "ASP.NET",
    "private": true,
    "devDependencies": {
    }
}
```

**Comment by scottaddie** [comment]
@madskristensen Yet another piece to this proposed change is to enforce lowercase via a pattern property regex in the SchemaStore repo. Thoughts?

**Comment by madskristensen** [comment]
Makes sense
