### ISSUE TITLE
Minor formatting issues with project.json and _references.js in some templates

### ISSUE THREAD

**Issue by balachir** [aspnet/Templates#373]
Minor formatting issues with project.json and _references show up when checking out project from source control.

project.json
![image](https://cloud.githubusercontent.com/assets/8246794/12209827/85c354b0-b60a-11e5-97ef-0111ac29622e.png)

_references.js
![image](https://cloud.githubusercontent.com/assets/8246794/12209823/7da4e604-b60a-11e5-8385-0b23fcaee0cf.png)

**Comment by rustd** [comment]
Closing as fixed
