### ISSUE TITLE
Update template code for OIDC changes

### ISSUE THREAD

**Issue by rustd** [aspnet/Templates#376]
This is a tracking bug for RC2

**Comment by rustd** [comment]
@Tratcher Please let us know when you have the changes checked in for RC2.

**Comment by Tratcher** [comment]
The only change I see here (https://github.com/aspnet/Templates/blob/dev/src/Rules/StarterWeb/OrganizationalAuth/Single/Startup.cs) is that `AutomaticChallenge = true` is now the default and doesn't need to be specified.  Same for https://github.com/aspnet/Templates/blob/dev/src/Rules/StarterWeb/OrganizationalAuth/Multiple/Startup.cs#L71

**Comment by rustd** [comment]
@phenning here you go! @Tratcher are there more coming for RC2?

**Comment by Tratcher** [comment]
I don't expect any for Single. The Events in Multiple may change still.

**Comment by rustd** [comment]
@Tratcher anything remaining for RC2?

**Comment by Tratcher** [comment]
This needs updating: https://github.com/aspnet/Templates/blob/dev/src/Rules/StarterWeb/OrganizationalAuth/Multiple/Startup.cs#L93
OnAuthenticationValidated was removed. Use OnTicketReceived instead.

**Comment by rustd** [comment]
Thanks! @phenning assigning to you

**Comment by phenning** [comment]
Will update as soon as we have a coherence-signed with the change.

**Comment by phenning** [comment]
Updated and merged
