### ISSUE TITLE
Add comment in web.config to use appsetting file for adding appsetting

### ISSUE THREAD

**Issue by rustd** [aspnet/Templates#377]

**Comment by phenning** [comment]
For empty web, given that we do not load appsettings.json by default, do we want to have that template also have the comment? Do you have any preferred verbage for the comment?

**Comment by rustd** [comment]
Adding a generic comment is fine for all templates. This should go above the configuration section

**Comment by phenning** [comment]
merged 555382228102b427919ed6c779833275ca8aa899
