### ISSUE TITLE
Update EF migrations

### ISSUE THREAD

**Issue by rustd** [aspnet/Templates#378]
Tracking bug to update EF migrations with each new package insertion.

**Comment by rustd** [comment]
Reopening this bug to keep it open for RC2. We should be updating migrations with each insertion of EF packages.

**Comment by phenning** [comment]
Updated migrations b10caa8719d3dbab88db8ce974a6c5f7233acdfd

Minimal update. This should be final update for RC2

**Comment by phenning** [comment]
Verified final rc2 build had migrations up to date.
