### ISSUE TITLE
MVC Template Should Apply ResponseCache Attribute to Error Action

### ISSUE THREAD

**Issue by ardalis** [aspnet/Templates#382]
HomeController.Error() should be updated:

```
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View();
    }
```

There is no good scenario where you would want errors to be cached, either on the client or via a proxy, or to have error information stored in such caches (especially if it might contain sensitive information in stack traces, etc.).

**Comment by Eilon** [comment]
This issue was moved to aspnet/templating#123
