### ISSUE TITLE
Logging: Add code for live refresh of logging

### ISSUE THREAD

**Issue by rustd** [aspnet/Templates#385]
We remove the following code https://github.com/aspnet/Templates/blob/dev/src/BaseTemplates/StarterWeb/Startup.cs#L22 in RC2. 
Actual

``` C#
Configuration = builder.Build();
```

Expected

``` C#
Configuration = builder.Build().ReloadOnChanged("appsettings.json");
```

**Comment by phenning** [comment]
Last I looked ReloadOnChanged doesn't support optional files, right? It would be nice if we could do this for the environment specific app settings since we actually ad one if it exists. Just mentioning this, for now I'll do the change we _can_ do.

```
            .AddJsonFile("appsettings.json")
            .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
```

**Comment by rustd** [comment]
Correct ReloadOnChanged doesn't support optional files.
