### ISSUE TITLE
Incorrect PW too long error message in RegisterViewModel

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Templates#393]
To repo:
1. Create a new MVC 6 web app with authen.
2. Change max string length from 100 to 10 for easy testing.
3. Enter 11 chars on the PW field when registering.
   You get the min. error, not the max error

The Password must be at least 6 characters long.

**Comment by rustd** [comment]
The error message is coming from Identity which has no knowledge of MaxStringLength. You should change the passwordvalidator if you want to change the complexity of the password.

**Comment by Rick-Anderson** [comment]
I DON"T want to change the complexity - I'm just showing you the max length violation is reporting incorrectly. 

That is our generated code and our code does not work. Our generated code uses 100, I have tested it with 100, and at 101 characters you get the same incorrect message

The Password must be at least 6 characters long.

The correct error message should be

The Password must NOT be 100+ characters long. (It's too long, not too short)

**Comment by Rick-Anderson** [comment]
@rustd If this isn't the right place to open this bug please tell me where. I can't open a localization bug on this template until this bug is fixed.

**Comment by rustd** [comment]
This is a bug in the templates. In https://github.com/aspnet/Templates/blob/dev/src/Rules/StarterWeb/IndividualAuth/Models/AccountViewModels/RegisterViewModel.cs#L17
we should update the error message as follows
[StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
