### ISSUE TITLE
Rename ASP.NET 5 to ASP.NET Core 1

### ISSUE THREAD

**Issue by rustd** [aspnet/Templates#400]
Update comments, Project_readme.html, template content, description and One ASP.NET dialog.
Refer to https://github.com/aspnet/Announcements/issues/144 for the new names.
- ASP.NET 5 => ASP.NET Core 1
- MVC6 => ASP.NET Core MVC
- EntityFramework 7=> Entity Framework Core 1

**Comment by phenning** [comment]
663ad176d7309db53b445cb78935ba437cede4bf
