### ISSUE TITLE
Default Framework version should be dnx452 instead of dnx451

### ISSUE THREAD

**Issue by rustd** [aspnet/Templates#402]
Per this blog [post,](http://blogs.msdn.com/b/dotnet/archive/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1.aspx) starting January 12, 2016 Microsoft will no longer provide security updates, technical support or hotfixes for .NET 4, 4.5, and 4.5.1 frameworks.

The default version should be dnx452. @BillHiebert @phenning @DamianEdwards thoughts?

**Comment by phenning** [comment]
No longer applicable with the move to netstandardapp
