### ISSUE TITLE
rimraf is depricated?

### ISSUE THREAD

**Issue by esargent** [aspnet/Templates#404]
looks like rimraf is depricated in favor of a recipe. See https://github.com/robrich/gulp-rimraf

Would it make sense to change the out-of-box template to the new option?

**Comment by scottaddie** [comment]
The `gulpfile.js` file included in the templates is using the raw [`rimraf`](https://github.com/isaacs/rimraf) module instead of this deprecated plugin, so I don't see a need to change anything.

**Comment by rustd** [comment]
@madskristensen thoughts?

**Comment by madskristensen** [comment]
No need to change

**Comment by rustd** [comment]
Thanks!
