### ISSUE TITLE
Stop loading Bootstrap from the ASP.NET CDN because glyphicons don't work

### ISSUE THREAD

**Issue by Eilon** [aspnet/Templates#407]
Related to: https://github.com/aspnet/Mvc/issues/3741

Currently the ASP.NET CDN doesn't properly serve the Bootstrap glyphicons due to an issue with CORS (or something). The default template becomes difficult to use in a real site because once you start using glyphicons in your site they don't work in production (glyphicons work locally, but not from the ASP.NET CDN).

I recommend removing the CDN references for Bootstrap from the template because of this limitation.

If we can get the ASP.NET CDN to support loading the fonts, then that's fine, and we can close/revert this.

Note: this is also related to, but different from these issues:
- https://github.com/aspnet/Templates/issues/333
- https://github.com/aspnet/Templates/issues/268

cc @DamianEdwards @rustd

**Comment by rustd** [comment]
The ASP.NET CDN has bee updated so you should be able to load font files.
