### ISSUE TITLE
Missing msbuild dotnet files?

### ISSUE THREAD

**Issue by jhermsen** [aspnet/Templates#411]
I know it might not be the right place to ask, but I can't find out how to get it installed.

In the template project files there is are some refernces to files in $(VSToolsPath)\DotNet. 
I don't have the folder. Please help.

**Comment by rustd** [comment]
What are you trying to install and do?

**Comment by rustd** [comment]
If you are using the RC1 tooling bits with latest ASP.NET Core runtime packages, then you will not be able to open this projects until there is a new tooling update with works against the latest runtime packages.
