### ISSUE TITLE
Update images in the carousel

### ISSUE THREAD

**Issue by rustd** [aspnet/Templates#412]
Update the branding of ASP.NET and they are not high resolution

**Comment by rustd** [comment]
This includes the files in this directory https://github.com/aspnet/Templates/tree/dev/src/BaseTemplates/StarterWeb/wwwroot/images

**Comment by rustd** [comment]
- ASP.NET 5 should be ASP.NET Core

**Comment by rustd** [comment]
The 4 images in the Images folder in can be losslessly compressed to save a total of 13kb. Let's use this tool to compress the images before we check them in. https://visualstudiogallery.msdn.microsoft.com/a56eddd3-d79b-48ac-8c8f-2db06ade77c3

**Comment by rustd** [comment]
@phenning I have emailed you the new images.

**Comment by phenning** [comment]
Merged 0ed618d4ab69c1a0f1784b82837ae0d7c1baba23
