### ISSUE TITLE
Don't create Project_Readme.html for ASP.NET 5 Empty

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/Templates#423]
I created an empty project for both ASP.NET 4 and ASP.NET 5. The ASP.NET 5 project had a Project_Readme.html and the ASP.NET 4 one did not. I'm not aware if that was on purpose or not, but we should be consistent with the empty projects. I think we should not add the Project_Readme.html for all Empty projects.

**Comment by rustd** [comment]
It was added for ASP.NET Core since it was new and we wanted to help customers getting started with ASP.NET Core.

**Comment by Eilon** [comment]
This issue was moved to aspnet/templating#121
