### ISSUE TITLE
Inconsistency in the icons for Class/ Console projects for .NET Core

### ISSUE THREAD

**Issue by rustd** [aspnet/Templates#436]
As seen below the icons for File-New Class/Console projects are different than the ones shown in Solution Explorer. They should be consistent

![default net core](https://cloud.githubusercontent.com/assets/1132652/13689328/fb610c14-e6dc-11e5-97af-34efee75213c.PNG)
![filenew netcore](https://cloud.githubusercontent.com/assets/1132652/13689329/fb718cc4-e6dc-11e5-9087-4f94506d2fdf.PNG)

**Comment by rustd** [comment]
@cartermp @rchande FYI. Incoming bug for RC2

**Comment by cartermp** [comment]
/cc @sayedihashimi as we had been chatting about icons with One ASP.NET

At least for RC2 I think we should have the icons in the New Project dialog be the icons that show up in Solution Explorer.  We can revisit icons later for RTM if we feel it's necessary.  Thoughts?

**Comment by rustd** [comment]
Phil, I sent you an email with the new icons. Can you please update the icons.
