### ISSUE TITLE
Add copyright to templates

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/Templates#441]
I was looking at standard C# projects and they include Copyright in the `AssemblyInfo.cs` file by default. This looks to be missing from our templates (copyright value going into `project.json`). I'd like to add the same default value for copyright. In standard C# projects the default copyright is `Copyright ©  <year>`.

**Comment by Eilon** [comment]
I would do this for _class library_ templates, but not sure it's useful in _web app_ projects.

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/aspnet/Templates/blob/dev/README.md.
