### ISSUE TITLE
Web App Work & School Account: Add code to read AD graph end point.

### ISSUE THREAD

**Issue by rustd** [aspnet/Templates#443]
When you select the read option while creating Work & School Accounts, the templates should show code to read the graph end point. We can base it on the following sample
https://github.com/aspnet/Security/tree/dev/samples/OpenIdConnect.AzureAdSample

It would be great if we can get this in for RC2. If not then let's do it soon after as it requires a new threat model.

**Comment by rustd** [comment]
We will move it to RTM if this doesn't fit.

**Comment by sayedihashimi** [comment]
Moving to rtm based on @rustd comments.

**Comment by rustd** [comment]
Attaching the sample
[WebAppReadSampleFullFx.zip](https://github.com/aspnet/Templates/files/235633/WebAppReadSampleFullFx.zip)

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/aspnet/Templates/blob/dev/README.md.
