### ISSUE TITLE
What should be the defaults for ResponseType for OIDC

### ISSUE THREAD

**Issue by rustd** [aspnet/Templates#445]
Moving https://github.com/aspnet/Security/issues/744 to templates

The current default is IdToken + Code. However, this requires the client secret to redeem the Code. This is problematic for some of the templates.

The current recommendation is to override the defaults in the template to IdToken and then followup on fixing the tooling so it can use the normal default IdToken + Code. No changes are recommended for the Security repo.

**Comment by phenning** [comment]
Judging by the other thread, it looks like we have the right default here for the template (IdToken)

Closing.

**Comment by rustd** [comment]
@Tratcher can you please confirm?
