### ISSUE TITLE
Updates for AspNetCoreModule

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Templates#450]
Updated web.config
Package: Microsoft.AspNetCore.IISPlatformHandler -> Microsoft.AspNetCore.Server.IISIntegration
Package: Microsoft.AspNetCore.HttpOverrides - Remove, this is added by Microsoft.AspNetCore.Server.IISIntegration
IWebHostBuilder.UseIISPlatformHandlerUrl() -> IWebHostBuilder.UseIIS
IApplicationBuilder.UseIISPlatfrormHandler() - Remove, this is added via UseIIS.
IApplicationBuilder.UseForwardedHeaders() - Remove, this is added via UseIIS. 
@rustd @DamianEdwards

**Comment by Tratcher** [comment]
https://github.com/aspnet/IISIntegration/issues/95

And add the publish-iis tool.
project.json:

```
    "tools": {
      "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-*"
    },
    "scripts": {
      "postpublish": "dotnet publish-iis --publish-folder %publish:OutputPath%"
    }
```

**Comment by phenning** [comment]
Merged
