### ISSUE TITLE
ValidationSummary.All should be replaced with ModelOnly

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Templates#451]
All the views in the Accounts folder use
`<div asp-validation-summary="ValidationSummary.All" class="text-danger"></div>`

They should just use 
`<div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>`

So you get each error twice. 

![image](https://cloud.githubusercontent.com/assets/3605364/13896326/ae916ee2-ed2b-11e5-8bf5-f9ad5246e82c.png)

**Comment by Eilon** [comment]
This issue was moved to aspnet/templating#119
