### ISSUE TITLE
Create content for Learn More links in One ASP.NET dialog

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/Templates#459]
Each template in the One ASP.NET dialog has a `Learn more` link. Today each link just goes to `http://www.asp.net/vnext`, which is not what we want. Each page should have its one doc for that specific template.

@danroth27 are you aware of any doc work to get `Learn more` links for each VS template created? If not can we get that scheduled? The current experience is not up to par. I'd like to have landing pages for each link by the time we RTW.

**Comment by rustd** [comment]
Sayed, please cover this as part of One ASP.NET dialog on how should these fwlinks show up. They show up for templates and the auth options

**Comment by Rick-Anderson** [comment]
#623

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/aspnet/Templates/blob/dev/README.md.
