### ISSUE TITLE
Minor error in Index.cshtml

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/Templates#460]
Duplicate text in Pranav page (Project_Readme.html) at.
https://github.com/aspnet/Templates/blob/0ed618d4ab69c1a0f1784b82837ae0d7c1baba23/src/BaseTemplates/StarterWeb/Views/Home/Index.cshtml#L72

Duplicate text is `ASP.NET ASP.NET Core MVC`.

**Comment by rustd** [comment]
@phenning can you please update this?

**Comment by phenning** [comment]
Actually the error was in index.cshtml, not the Pranav page/project_readme.html
