### ISSUE TITLE
Update feedback link in Project_Readme.html

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/Templates#461]
In the Project_Readme.html page the feedback link goes to https://aspnet.uservoice.com/forums/41199-general-asp-net. Wouldn't it make more sense to link this to https://github.com/aspnet/templates/issues since users are likely to report feedback on templates with that link?

cc @rustd

**Comment by rustd** [comment]
The feedback link is about the ASP.NET product rather than templates specifically.
