### ISSUE TITLE
MVC: Use feature folders

### ISSUE THREAD

**Issue by poimis** [aspnet/Templates#462]
Currently MVC-template uses folders per concept (Controller, Views, Models). This solution does not really scale and a better solution would be so called feature folders.
Many are doing it already and imho it would really be a better practice to promoto.

Some examples:
http://timgthomas.com/2013/10/feature-folders-in-asp-net-mvc/
http://www.meadow.se/wordpress/grouping-by-feature-in-asp-net-mvc/
http://www.chwe.at/2014/04/introducing-the-asp.net-mvc-feature-folders-project-structure/

**Comment by Eilon** [comment]
Using a feature folder certainly seems like it could be a good practice for a larger app (or perhaps even small apps). However, the goal of the templates in VS are to be a good starting point for any type of application, so it is kept relatively simple with only what is needed to get started.

**Comment by poimis** [comment]
Well, the current template already gives more than the bare minimum. And as we both know, too few people take the time (god heavens, many minutes!) to organise the folders and write (copypaste) the customised view location code needed so the world is filled with badly organized solutions.

Actually this is not only a template issue, they should fix it MVC razorengine to make the default work with feature folders.

**Comment by Eilon** [comment]
Feature folders are one of many ways to lay out a project. From the projects I've seen (which is hundreds, from lots of different companies), it's not a very common one. We often choose a fairly generic-yet-simple structure for the project templates. Adding more layers, such as feature folders, probably won't help a new user approach MVC any better.

**Comment by rustd** [comment]
Closing as per @Eilon comment.
