### ISSUE TITLE
External login confirmation text explicitely describes user name while expecting email

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Templates#463]
```
Please enter a user name for this site below and click the Register button to finish
```

```
<input asp-for="Email" class="form-control" />
```

https://github.com/aspnet/Templates/blob/7b83d3628ed40a2637fe36946ba8185ac232a190/src/Rules/StarterWeb/IndividualAuth/Views/Account/ExternalLoginConfirmation.cshtml#L16
http://docs.asp.net/en/latest/security/authentication/sociallogins.html

Thanks!

**Comment by rustd** [comment]
good catch. @phenning can you please update the text to say enter an email instead of user name.
