### ISSUE TITLE
Feedback on new project experience

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/Templates#464]
I'm starting to get more involved in the template space in a formal manner. I'm curious to hear thoughts about the new project experience as a whole. We already have a specific issue to discuss the One ASP.NET dialog at https://github.com/aspnet/Templates/issues/422 so for topics specific to that we can use that thread.

I'm specifically interested in hearing thoughts about.
- Ideas about the command line experience to create web projects
- Any thoughts on what we should be striving for in terms of long term goals which we may not be currently considering

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/aspnet/Templates/blob/dev/README.md.
