### ISSUE TITLE
Extra dot to remove

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Templates#465]
`ForgotPassword` template:
https://github.com/aspnet/Templates/blob/7b83d3628ed40a2637fe36946ba8185ac232a190/src/Rules/StarterWeb/IndividualAuth/Views/Account/ForgotPassword.cshtml
The title ends with dot:
https://github.com/aspnet/Templates/blob/7b83d3628ed40a2637fe36946ba8185ac232a190/src/Rules/StarterWeb/IndividualAuth/Views/Account/ForgotPassword.cshtml#L6
where `Title` variable end with question mark.
So template renders:

```
Forgot your password?.
```

**Comment by Eilon** [comment]
Is that a bug?.

**Comment by Eilon** [comment]
(That was a joke :smile: )

**Comment by sayedihashimi** [comment]
Lol @eilon
