### ISSUE TITLE
Use new fwlinks for learn more links in One ASP.NET templates

### ISSUE THREAD

**Issue by rustd** [aspnet/Templates#469]
Use a different fwlink for ASP.NET Core templates.ASP.NET 4.6 templates will have separate fwlinks

**Comment by rustd** [comment]
Web App: http://go.microsoft.com/fwlink/?LinkID=784881
Web API: http://go.microsoft.com/fwlink/?LinkID=784882
Empty: http://go.microsoft.com/fwlink/?LinkID=784883

**Comment by phenning** [comment]
@rustd 
The current default FWlink for ASP.NET 4 templates is:
http://go.microsoft.com/fwlink/?LinkId=517593

**Comment by rustd** [comment]
@sayed Can you please update this fwlink http://go.microsoft.com/fwlink/?LinkId=517593 so it lands on content specific to ASP.NET 4.6. http://www.asp.net/visual-studio could be a good place for now.

**Comment by rustd** [comment]
Assigned to Sayed for the following:
 Can you please update this fwlink http://go.microsoft.com/fwlink/?LinkId=517593 so it lands on content specific to ASP.NET 4.6. http://www.asp.net/visual-studio could be a good place for now.

**Comment by sayedihashimi** [comment]
I have updated http://go.microsoft.com/fwlink/?LinkId=517593 to point to http://www.asp.net/visual-studio. Let me know if there is more action required on my part here.

**Comment by rustd** [comment]
Thanks! Closing
