### ISSUE TITLE
Add Microsoft.Extensions.Options.ConfigurationExtensions to the default templates

### ISSUE THREAD

**Issue by HaoK** [aspnet/Templates#471]
We'd like the Configure method to be available automatically

**Comment by rustd** [comment]
what is the code change? Just add this namespace to Startup?

**Comment by HaoK** [comment]
Just need to add the reference to project.json by default

**Comment by phenning** [comment]
For all templates including Empty?

**Comment by rustd** [comment]
@Haok which Configure method are you talking about. https://github.com/aspnet/Templates/blob/dev/src/BaseTemplates/EmptyWeb/Startup.cs#L22 is already in the templates.
ping me offline for a quick chat

**Comment by rustd** [comment]
Moving this to RTM  as per chat with @divega. We need to figure out if we really need to add this

**Comment by divega** [comment]
Customers feeling the pain of this not being in: https://github.com/aspnet/Options/issues/142.

**Comment by divega** [comment]
Was this automatically punted to tooling RTM because we renamed the milestone? Can't we get it in for preview2 instead? I keep seeing customers looking for those APIs. @rustd @phenning

**Comment by rustd** [comment]
@sayedihashimi who owns templates now.

**Comment by phenning** [comment]
Talked this over with @mlorbetske. We'll add this package for preview2

**Comment by phenning** [comment]
Adding for all but Empty since Empty does not pull in Configuration at all.
