### ISSUE TITLE
Updates needed to Project_Readme page for RC2

### ISSUE THREAD

**Issue by balachir** [aspnet/Templates#472]
Changes for RC2:
1. RUN & DEPLOY section
   a. Section "Run commands in your project.json" must be replaced with a section for running tools defined in project.json
   b. Why have two entries for "Run your app" and "Run your app on .NET Core"? Are these both still applicable for the new templates?
2. OVERVIEW section
   a. We should have a section that links to clear guidance around project.json changes in RC2 such as .NET Platform Standard, frameworks vs runtimes (maybe a doc describing project.json in general)
   b. dotnet cli (?)
   c. It would be nice to have an entry about "Dependency Injection" given that it's such a fundamental concept for ASP.NET Core apps.
3. GENERAL
   a. [Minor nit] Why do some entries end with "." and others don't? I think we can just drop the "." in all the entries.

Below is what the page looks like today:

![image](https://cloud.githubusercontent.com/assets/8246794/14163069/83645bba-f6a6-11e5-8182-65a5562acb05.png)

**Comment by rustd** [comment]
Fixed
