### ISSUE TITLE
Email address verification for external login flow

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Templates#474]
The individual auth template's AccountController has commented out code for sending e-mail verification messages for the normal Register action (used with local accounts), but it does not have this code for the ExternalLoginConfirmation action. The e-mail field is editable for local and remote account flows and should be verified the same way.

**Comment by Tratcher** [comment]
Duplicate of https://github.com/aspnet/Templates/issues/365?

**Comment by rustd** [comment]
Yes it is. Closing this one.
