### ISSUE TITLE
Description of Class/ Console templates

### ISSUE THREAD

**Issue by rustd** [aspnet/Templates#479]
The current description says preview. Please update the description.

![classrc2](https://cloud.githubusercontent.com/assets/1132652/14217250/c32a94ba-f801-11e5-9945-263cc42ec8ce.png)
![consolerc2](https://cloud.githubusercontent.com/assets/1132652/14217249/c32a4776-f801-11e5-92dc-21154fc9fde9.png)

**Comment by rustd** [comment]
@cartermp @rchande can you please update this for RC2

**Comment by cartermp** [comment]
I think we should keep "PREVIEW" in the description text.  It's still preview bits that are shipping with RC2 (at least in the sense that it's pre-.NET Core 1.0).

**Comment by richlander** [comment]
Our quality level should be front and center. I like the idea of including the "Preview" term.

**Comment by rustd** [comment]
Closing as per @richlander comment.
