### ISSUE TITLE
Install Dev14 U2 + RC2 + Azure SDK 2.9, cannot create Cloud Service with Web Role

### ISSUE THREAD

**Issue by balachir** [aspnet/Templates#480]
You get no templates when trying to create a web role

![image](https://cloud.githubusercontent.com/assets/8246794/14222500/31021bd8-f826-11e5-9b02-22bc66e90c21.png)

**Comment by phenning** [comment]
Thanks, this is due to an incorrect check against the new filtering we added to the one asp.net dialog. I'm testing a fix now.

**Comment by phenning** [comment]
Checked in a fix to tooling.
