### ISSUE TITLE
Suggestion: Rename the "Empty Application" to "Web Empty Application"

### ISSUE THREAD

**Issue by jeffschwMSFT** [aspnet/Templates#481]
The yomen generators have options for "Empty, Console, Web, Web Basic, Web API, Nancy, Class Lib, and Unit test".  Given the broad reach of these templates, I would recommend that Empty be named more inline with how VS categorizes it and what it contains.  Empty is not an empty project, but rather a barebones Web app.

**Comment by rustd** [comment]
This repo is about ASP.NET templates that ship in VS. For yomen generators, please file an issue https://github.com/OmniSharp/generator-aspnet
