### ISSUE TITLE
Remove any temporary workaround for RC2

### ISSUE THREAD

**Issue by rustd** [aspnet/Templates#488]
We have checked in a few workarounds to unblock the builds so we can get an E2E experience going for RC2. Once we have a stable build, we should remove the workarounds and fix the underlying issues.
@phenning this is for tracking purpose. You can add details as needed.

**Comment by phenning** [comment]
- [x] Enable Razor Tooling for Full Framework Starter Web
- [x] Enable dotnet-ef tool for Full Framework Starter Web
- [x] Enable Scaffolding tool for Full Framework Starter Web

**Comment by rustd** [comment]
Do we need to enable IIS tool as well for Full Framework?

**Comment by phenning** [comment]
It already is.
- Phil

On Apr 19, 2016, at 3:16 PM, Pranav Rastogi <notifications@github.com<mailto:notifications@github.com>> wrote:

Do we need to enable IIS tool as well for Full Framework?

##
