### ISSUE TITLE
Add tests to project templates

### ISSUE THREAD

**Issue by OzieGamma** [aspnet/Templates#492]
Hi,

Testing is unfortunately a part of most of our jobs. I don't know if it is already planned/done but in visual studio when I create a new ASP.NET MVC 6 (or is it Core 1 ? Not sure) there are no tests. This is particularly annoying for the template including user accounts. I spent a few hours writing tests for the included templates.

I was wondering whether other people would be interested ?

**Comment by sayedihashimi** [comment]
@OzieGamma to be clear are you asking for a unit test project template? Or are you looking for ways to test your website itself?

> ASP.NET MVC 6 (or is it Core 1 ? Not sure)

The branding is:
- ASP.NET Core
- ASP.NET MVC Core

**Comment by OzieGamma** [comment]
No I have managed to test mz projects. It just bothers me to receive templates without unit tests. )I am thinking of the one including authentification). I think it should come with some sort of testing.

Thx for the branding !

**Comment by phenning** [comment]
There are other tests which test the templates after they are imported into Visual Studio which you do not see in this repo. Unfortunately, we've had to disable the unit tests in this repo due to the churn of the runtime.

**Comment by OzieGamma** [comment]
No, no, I understand the templates are tested. It would be nice to have those tests in my solution when I create a project.

In other words when I scaffold a project, Id like to scaffold the Test project at the same time.

Eg:
- Example
  -> project.json
  -> Startup.cs
  -> Views
  -> Controllers
      -> AccountController.cs
- Example.Test (missing)
  -> Controllers (missing)
      -> AccountControllerTest.cs (missing)

**Comment by Eilon** [comment]
This issue was moved to aspnet/templating#117
