### ISSUE TITLE
Error Building Template

### ISSUE THREAD

**Issue by rhizalpatrax64bit** [aspnet/Templates#499]
## Templates>.\build

> EXEC : error : Unable to resolve 'Libuv (>= 1.9.0-rc3-20541)' for '.NETCoreApp,Version=v1.0'. [C:\Users\rhizalpatra\Documents\Templates\test\VerifyTemplates.csproj]
## dotnet --info

> .NET Command Line Tools (1.0.0-rc2-002353)
> 
> Product Information:
>  Version:     1.0.0-rc2-002353
>  Commit Sha:  1a0b9bba98
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.10586
>  OS Platform: Windows
>  RID:         win10-x64

![error](https://cloud.githubusercontent.com/assets/6958755/14492504/d9243832-01a9-11e6-901f-598396bd6490.png)

**Comment by phenning** [comment]
@rhizalpatrax64bit Thanks for the report. I've submitted some fixes to both our release and dev branches which should resolve this for any non CI-build.

**Comment by rhizalpatrax64bit** [comment]
Found new error

##.\build

>  error CS1061: 'IConfigurationBuilder' does
>  not contain a definition for 'SetProjectPath' and no extension method 'SetProjectPath' accepting a first argument of type 'IConfigurationBuilder' could be found (are
>  you missing a using directive or an assembly reference?)

![error2](https://cloud.githubusercontent.com/assets/6958755/14519347/6df997ec-0248-11e6-8e03-e4bb8f46804b.png)
