### ISSUE TITLE
Accidental commit without code review

### ISSUE THREAD

**Issue by madskristensen** [aspnet/Templates#500]
I accidently committed [694c14d](https://github.com/aspnet/Templates/commit/694c14d74f7db198a9692a2d9a58ecae6ff9e9da) when I intended to create a pull request. Feel free to revert it.

The commit was about adding 4 missing `role="option"` attributes to index.cshtml in the StarterWeb template. Without this change, the template doesn't meet accessibility validation.

**Comment by rustd** [comment]
@madskristensen It's ok. @phenning can you please merge @madskristensen changes in release?
