### ISSUE TITLE
Multiple versions of JSON.Net get restored with default StarterWeb project.

### ISSUE THREAD

**Issue by phenning** [aspnet/Templates#509]
Most everything includes 8.0.3, with the following exceptions. A few examples follow, attached is the project.json and project.lock.json files.

7.0.1:

``` json
      "Microsoft.Extensions.DependencyModel/1.0.0-rc2-002392": {
        "type": "package",
        "dependencies": {
          "Microsoft.DotNet.InternalAbstractions": "1.0.0-rc2-002392",
          "Microsoft.Extensions.PlatformAbstractions": "1.0.0-rc2-20459",
          "Newtonsoft.Json": "7.0.1",
          "System.Diagnostics.Debug": "4.0.11-rc2-24008",
          "System.Dynamic.Runtime": "4.0.11-rc2-24008"
        },
```

6.0.4:

``` json
      "NuGet.RuntimeModel/3.5.0-beta-1167": {
        "type": "package",
        "dependencies": {
          "NETStandard.Library": "1.5.0-rc2-24008",
          "Newtonsoft.Json": "6.0.4",
          "NuGet.Frameworks": "3.5.0-beta-1167",
          "NuGet.Versioning": "3.5.0-beta-1167",
          "System.Dynamic.Runtime": "4.0.11-rc2-24008",
          "System.ObjectModel": "4.0.12-rc2-24008"
        },
```

[project.lock.json.txt](https://github.com/aspnet/Templates/files/221907/project.lock.json.txt)
[project.json.txt](https://github.com/aspnet/Templates/files/221910/project.json.txt)

**Comment by rustd** [comment]
@Eilon is this expected for RC2?

**Comment by Eilon** [comment]
Talked to @NTaylorMullen and @rustd .

Every `tools` item needs to also be listed under `dependencies`, which will help "lift" all dependencies to a mutually agreeable version.

However, please note that due to https://github.com/dotnet/cli/issues/2505, commands will still not work on .NET Framework in some cases.

**Comment by rustd** [comment]
Assigning to Phil to list ef and scaffolding tools under dependencies.

**Comment by NTaylorMullen** [comment]
Clarification: Only ef, scaffolding and Razor need to exist in both the tools and dependencies nodes. All other tools that I'm aware of can exist only in the tools section.

**Comment by phenning** [comment]
Correct, I'm leaving the IIS tools in dependency section only.

**Comment by phenning** [comment]
Updated dependencies

4e45dda3ae29b96ffe91134cf5ea573b646112a4
