### ISSUE TITLE
Use Server GC

### ISSUE THREAD

**Issue by rynowak** [aspnet/Templates#510]
Is there any reason not to turn on server GC in our templates? This is possible now with dotnet so we should do it :+1: 

/cc @DamianEdwards @Eilon

**Comment by DamianEdwards** [comment]
Yes we should be turning it on for sure. Need this change for RC2.

**Comment by rustd** [comment]
@rynowak what is the change?

**Comment by rynowak** [comment]
Add this configuration block to the project.json for web app projects

https://github.com/aspnet/Performance/commit/33e17e83def17a3d13334151feea3974a7ce3e0e

**Comment by rustd** [comment]
@phenning assigning to you for RC2. Can you fix this?

**Comment by phenning** [comment]
@rustd @DamianEdwards 

Any thoughts on where we want to place this section in the templates? I was thinking below the compilationOptions section before dependencies. 

In the project.jsons in the linked commit, they were below content, but I don't think we should break the continuity of tools/content/exclude/scripts.

**Comment by rustd** [comment]
Move the compilationOptions after dependencies and put the runtimeOptions there. This is what the final ordering would look like.

usersecretId

dependencies

tools

frameworks

compilationOptions

runtimeOptions

content

exclude

scripts

**Comment by phenning** [comment]
@rustd Should class and console also have their compilation options moved? Do we have buy off from all parties?

On Apr 19, 2016, at 9:27 AM, Pranav Rastogi <notifications@github.com<mailto:notifications@github.com>> wrote:

Move the compilationOptions after dependencies and put the runtimeOptions there. This is what the final ordering would look like.

usersecretId

dependencies

tools

frameworks

compilationOptions

runtimeOptions

content

exclude

scripts

##

**Comment by phenning** [comment]
@rustd , oh and "runtimes" should come after "frameworks" but before "compilationOptions", right?  (For Full framework)
