### ISSUE TITLE
Update templates for new publish-iis and web.config location

### ISSUE THREAD

**Issue by moozzyk** [aspnet/Templates#511]
- publish-iis now takes a new --framework parameter (https://github.com/aspnet/Announcements/issues/169)
- web.config was moved to the application root from wwwroot

**Comment by rustd** [comment]
@phenning can you please make the changes to project.json for .NET framework and Core

**Comment by phenning** [comment]
web.config moving was already done. sent PR for --frameowkr parameter

**Comment by phenning** [comment]
4e45dda3ae29b96ffe91134cf5ea573b646112a4
