### ISSUE TITLE
Need to set the default output path to ".\bin\"

### ISSUE THREAD

**Issue by BillHiebert** [aspnet/Templates#513]

**Comment by rustd** [comment]
I am assuming this is for RC2. @phenning Assigning to you. Can you please check with @BillHiebert

**Comment by phenning** [comment]
Yes this is for RC2, Bill sent a mail on this today.

**Comment by phenning** [comment]
After talking to bill, we should also update the intermediatepath to ".\obj"

**Comment by phenning** [comment]
0d5ace2839b61dc306fed6782da8cb842898f307
