### ISSUE TITLE
Changes to Org Auth templates 

### ISSUE THREAD

**Issue by rustd** [aspnet/Templates#516]
- Templates with the Read Check box should have code in Startup to read the client secret.
- ResponseType settings https://github.com/aspnet/Templates/blob/release/src/Rules/StarterWeb/OrganizationalAuth/Single/Startup.cs#L73
  -- For Non read case middleware will have the right defaults, so remove the code from the templates
  -- For read case, set it to Id+Token

**Comment by rustd** [comment]
@Tratcher FYI. @phenning This will have to be done once the runtime changes are done.

**Comment by rustd** [comment]
Referencing the runtime bug https://github.com/aspnet/Security/issues/744

**Comment by phenning** [comment]
551dfbd0a08339768d1f99548ff0ff54d6a23438
78bf98229f5ae502b9815ed4330ef6fb054b75b5
