### ISSUE TITLE
Include self-host launch settings by default

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Templates#519]
The templates currently include a profile for launching IIS Express, but nothing for self-host. Self-host should be included by default.

Something like this in the launchSettings.json:

```
    "self-host": {
      "commandName": "Project",
      "launchBrowser": true,
      "launchUrl": "http://localhost:5000/",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
```

**Comment by davidfowl** [comment]
YES, dunno about the name self host, but we need something

**Comment by rustd** [comment]
Moving this to RTM. There is an option in property pages for creating a new profile.

**Comment by davidfowl** [comment]
Uh, no, can we do this for RC2.

**Comment by phenning** [comment]
Or consider the tooling could auto create such a profile so we don't need to specify it for every template.

**Comment by rustd** [comment]
TFS 215173 is tracking this to be triaged for RC2. Clearing the milestone
