### ISSUE TITLE
.NET CLI userSecret tool should be added by default

### ISSUE THREAD

**Issue by rustd** [aspnet/Templates#520]
We should add the this tool to the templates (authentication ones) that use user-secrets. This will make it easier to use this tool.
Without this integration, it is hard to discover/ install this tool. A user has to add the following for the tool to work

``` json
    "dotnet-user-secrets": {
      "version": "1.0.0-rc2-20581",
      "imports": [
        "portable-net45+win8+dnxcore50",
        "portable-net45+win8"
      ]
    },
```

**Comment by phenning** [comment]
May not actually need "portable-net45+win8" as one of the imports, the dnxcore50 one may suffice

**Comment by rustd** [comment]
This should be enabled for all templates where we use usersecrets in Startup.cs

**Comment by phenning** [comment]
https://github.com/aspnet/Templates/pull/530/commits/835726607969a773bb43ed6861eee3182e4fa1ab
