### ISSUE TITLE
Remove duplicate .ReloadOnChanged("appsettings.json") in Startup.cs

### ISSUE THREAD

**Issue by HaoK** [aspnet/Templates#523]
This is redundant with the earlier setting of ReloadOnChanged for the source, and will be removed soon.  All Startups should have this call removed so we can remove the API from configuration

cc @divega

**Comment by divega** [comment]
cc @rustd since he was going to file this.

**Comment by phenning** [comment]
It looks like this is only in the individual auth version of starterweb

**Comment by phenning** [comment]
Opened TFS# 216273

**Comment by phenning** [comment]
2f75105617ecc2c29b27563a93935d63556988e9
