### ISSUE TITLE
Feedback from RC2 Review

### ISSUE THREAD

**Issue by rustd** [aspnet/Templates#525]
- [x] Move the server gc section to app.config for Full FX templates
  For all templates targeting Full FX, move the servergc section to app.config. This will be a new file added to the template at the root. See this [link ](https://msdn.microsoft.com/library/ms229357.aspx)for enabling this in app.config
- [x] Templates targeting Full FX: Remove the runtimes section
- [x] Template descriptions to have (framework) in description as follows:

Web Node
- ASP.NET Web Application (.NET Framework)
- ASP.NET Core Web Application (.NET Core)
- ASP.NET Core Web Application (.NET Framework)

.NET Core Node
- ASP.NET Core Web Application (.NET Core)
- [x] https://github.com/aspnet/Templates/issues/520
- [x] All templates : Remove comment from https://github.com/aspnet/Templates/blob/dev/src/BaseTemplates/EmptyWeb/Program.cs#L12
  and 
  https://github.com/aspnet/Templates/blob/release/src/BaseTemplates/StarterWeb/Startup.cs#L17
- [x] All templates: Remove setter for Configuration https://github.com/aspnet/Templates/blob/dev/src/BaseTemplates/StarterWeb/Startup.cs#L30

``` csharp
public IConfigurationRoot Configuration { get; }
```
- [x] Add a new line before staticfiles https://github.com/aspnet/Templates/blob/release/src/Rules/StarterWeb/IndividualAuth/Startup.cs#L89
- [x] project.json: dependencies section should start with Microsoft.NETCore.App and it will be alphabetical order after that. We should use the single line format with version coming in first. This format should be used everywhere we add tools/ dependency.

``` json
"Microsoft.NETCore.App": { "version": "1.0.0-rc2-3002426", "type": "platform" },
```
- [x]  Remove the following dependencies from Individual Auth template
  Microsoft.AspNetCore.Identity/ Microsoft.AspNetCore.Mvc.TagHelpers/ Microsoft.Extensions.Configuration.FileExtensions

**Comment by phenning** [comment]
Do we still have a server GC section in the project.json for core templates?

**Comment by rustd** [comment]
Yes server GC is in project.json for Core only

**Comment by rustd** [comment]
TFS 216369 is tracking this.

**Comment by phenning** [comment]
After talking to @DamianEdwards we will not use single line format for dep/tools due to CTRL-K-D formatting in VS.
