### ISSUE TITLE
Remove code for EF migration from Startup

### ISSUE THREAD

**Issue by rustd** [aspnet/Templates#526]
In case we don't get the tooling support for publishing, can we move the code to create the database from Startup to closer to DbConext.

**Comment by rustd** [comment]
If you can send me a sample then I can merge it in.

**Comment by rowanmiller** [comment]
The idea was to just make a method on the context and then call it from Startup.cs - so that you get one neat line in Startup.cs rather than the more complicated logic. With the PR that @ajcvickers sent (which has now been merged) we no longer create a scope etc. so I think it's probably ok to leave it as-is... and deployment should get rid of the code altogether before we release.

**Comment by rustd** [comment]
The idea was to not see the code in Startup. Even with PR we have the try-catch block so it needs to be moved to DbContext. Let's wait for the deployment story and see what happens.

**Comment by rowanmiller** [comment]
Agreed. Just to make sure we are on the same page... there would still be one line of code here (that would call the static method on the context).

**Comment by rustd** [comment]
Yup. we are on the same page :)

**Comment by rustd** [comment]
@phenning please remove the try-catch and the comment above it as well.

**Comment by phenning** [comment]
TFS: [220760](https://devdiv.visualstudio.com/defaultcollection/DevDiv/_workitems?id=220760&_a=edit)

**Comment by peterblazejewicz** [comment]
@rowanmiller @rustd we need a scenario for non-VS tooling scaffolding. I'm applying #562 to OmniSharp/generator-aspnet web project and it needs a data scaffolding. Let me know what you think.
Thanks!

**Comment by rustd** [comment]
This code was only needed for server-side production scenarios. At dev time, you will get a Database error page which is same as VS. I am going to upload latest templates for RC2 which will have these changes.

**Comment by peterblazejewicz** [comment]
OK. Thanks!

**Comment by peterblazejewicz** [comment]
> At dev time, you will get a Database error page which is same as VS. I am going to upload latest templates for RC2 which will have these changes.

By default env is production. No one will ever see error details I'm afraid and get stacked  into middle of reading docs.asp.net tutorial
https://github.com/OmniSharp/generator-aspnet/issues/713

**Comment by rustd** [comment]
You need to set the env to development.

**Comment by rowanmiller** [comment]
There should be details about how to enable development environment on the error page you get if you aren't running in development environment. Though there is some discussion about removing that text (cc @glennc).

**Comment by peterblazejewicz** [comment]
Thanks folks!. Yes, I know this and this works. I'll move discussion to `generator-aspnet` as it needs to reflect tooling configuration changes required to accommodate to this.
