### ISSUE TITLE
 nuget.config file needs to be an ItemTemplate

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/Templates#528]
Originally posted by @ciel at https://github.com/aspnet/Tooling/issues/447

Is it possible to add a `NuGet Configuration File` to the item templates? I find myself making a lot of them, and I always have to just pick another one and rename it, and copy/paste from another one.

**Comment by peterblazejewicz** [comment]
There is one in OmniSharp/generator-aspnet for the very same purpose: `yo aspnet:nuget` or `yo aspnet:nuget --unstable` when working with prerelease content (e.g. with RC2)

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/aspnet/Templates/blob/dev/README.md.
