### ISSUE TITLE
React to project model changes in project.json

### ISSUE THREAD

**Issue by mikes-gh** [aspnet/Templates#533]
Although this change is backwards compatible compilationOptions gives warning in latest dotnet build.
I am not sure what cli rc2 will ship with but users don't like seeing warnings.

[edit]
build console output

```
C:\Users\mikes\Repos\cli-samples\HelloMvc>dotnet --version
1.0.0-rc2-002543

C:\Users\mikes\Repos\cli-samples\HelloMvc>dotnet build
Project HelloMvc (.NETCoreApp,Version=v1.0) will be compiled because Input items
 removed from last build
Compiling HelloMvc for .NETCoreApp,Version=v1.0
C:\Users\mikes\Repos\cli-samples\HelloMvc\project.json(6,26): warning DOTNET1015
: The 'compilationOptions' option is deprecated. Use 'buildOptions' instead.

Compilation succeeded.
    1 Warning(s)
    0 Error(s)

Time elapsed 00:00:03.0795778



C:\Users\mikes\Repos\cli-samples\HelloMvc>
```

**Comment by rustd** [comment]
What is the corresponding runtime issue for this so we can track all the other changes to project.json

**Comment by mikes-gh** [comment]
https://github.com/dotnet/cli/issues/792
The commit is in the thread

**Comment by rustd** [comment]
https://github.com/aspnet/Announcements/issues/175

**Comment by phenning** [comment]
aa31cb93ac1a39bd82d0c839eaa6e1d678202b65
14824f6d315d5a6bfdf52847aba38bd3907d127a
53b562ef3fea0c919e2dcedac8bebc8b27b00ae4
