### ISSUE TITLE
Wrong splash screen for ASP.NET Core Web Site - Empty 

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Templates#538]
Actual result:

![image](https://cloud.githubusercontent.com/assets/1165805/15022270/b38a5d68-11df-11e6-9760-8988e32f4fc3.png)

Where it actually is a middleware based app, without views and and without Gulp/Bower files.

**Comment by peterblazejewicz** [comment]
@sebastienros 
At the moment the VS team provides an unified starter noob document. They are seeing the problem with that model though:
https://github.com/aspnet/Templates/issues/498

**Comment by Eilon** [comment]
This issue was moved to aspnet/templating#116
