### ISSUE TITLE
Update the Startup.cs to have a placeholder for external auth

### ISSUE THREAD

**Issue by analogrelay** [aspnet/Templates#540]
Right now the Startup.cs has a line like this:

``` csharp
// To configure external authentication please see http://go.microsoft.com/fwlink/?LinkID=532715
```

It's not clear that the middleware configuration should go there, and not elsewhere in the file. This isn't helped by the docs not being super clear (https://github.com/aspnet/Docs/issues/1187) but our templates could improve this as well but indicating that external auth middleware should go there.

``` csharp
// To configure external authentication please see http://go.microsoft.com/fwlink/?LinkID=532715
// Place external authentication middleware configuration here
```

**Comment by rustd** [comment]
Let's combine them as a single comment as follows.
// Add external authentication middleware below. To configure them please see http://go.microsoft.com/fwlink/?LinkID=532715

**Comment by phenning** [comment]
TFS: [219293](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?_a=edit&id=219293)
