### ISSUE TITLE
Need an Angular2 SPA template

### ISSUE THREAD

**Issue by damienbod** [aspnet/Templates#541]
VS should provide a template for Angular 2 (RC onwards) with an ASP.NET Core MVC API
- includes a systemjs build for production and dev (Webpack as an option)
- Breakpoint debugging possible in VS for Angular 2 
- Implicit Flow OpenID Connect client as an option

**Comment by scottaddie** [comment]
@damienbod It sounds like Steve Sanderson may already be working on something related to this. Read more [here](http://blog.stevensanderson.com/2016/05/02/angular2-react-knockout-apps-on-aspnet-core/).

**Comment by damienbod** [comment]
Hi @scottaddie Thanks for the link, looks promising.
Greetings Damien

**Comment by damienbod** [comment]
Maybe something like this with Webpack
https://github.com/damienbod/Angular2WebpackVisualStudio

**Comment by scottaddie** [comment]
@damienbod Have you already seen the following Angular 2 template? https://github.com/aspnet/JavaScriptServices/tree/master/templates/Angular2Spa. It seems like you might get a little more traction over there.

**Comment by damienbod** [comment]
Hi @scottaddie yes, I saw that, but its using the old angular2. (Pre RC1). Webpack provides a really good solution which could be used in production and not just demos unlike many of the existing blogs/examples for using Visual studio, aspnetcore and angular 2.

Greetings and thanks for your reply Damien

**Comment by damienbod** [comment]
@scottaddie It got updated today :) Thanks for the link

**Comment by scottaddie** [comment]
@damienbod No problem. I know they're looking for feedback on those templates. I'd encourage you to submit PRs to help mold the Angular template into something you'd actually want to use.

**Comment by Eilon** [comment]
This was done a while ago.
