### ISSUE TITLE
DnxInvisibleContent item type name change

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Templates#543]
Now that DNX is gone as of RC2, are there plans to rename the `.xproj` file's `DnxInvisibleContent` item type to something more meaningful? Here's specifically what I'm talking about in the "StarterWeb" project template:
https://github.com/aspnet/Templates/blob/dev/src/BaseTemplates/StarterWeb/StarterWeb.xproj#L19-22

**Comment by Eilon** [comment]
Closing because this doesn't apply anymore.
