### ISSUE TITLE
Move NetCoreApp Dependency into tfm-specific dependendencies

### ISSUE THREAD

**Issue by rynowak** [aspnet/Templates#544]
The project.json created by VS includes the following in the top-level dependencies node.

```
        "Microsoft.NETCore.App": {
          "version": "1.0.0-rc2-3002426",
          "type": "platform"
        }
```

This is annoying if you want to add another TFM because this dependency only works on netcoreapp. Also, the error you get if you add `net46` refers to `System.Runtime.Loader` as incompatible with that framework. Hard to puzzle out since you don't have a direct reference to `System.Runtime.Loader`.

If we add this dependency in the tfm-specific dependencies for netcoreapp by default we can skip this whole thing.

**Comment by rustd** [comment]
What would the project.json look like?

**Comment by rynowak** [comment]
https://github.com/rynowak/mvc-sandbox/blob/rc2-signoff-diagnostics/WebApp/project.json

**Comment by rustd** [comment]
@anurse to check why we added it in the dependencies section?

**Comment by analogrelay** [comment]
Not sure. It would probably be better to put it in the framework-specific dependencies section.

**Comment by rustd** [comment]
@DamianEdwards @davidfowl what do you think? should we move Microsoft.NETCore.App in framework dependencies? What should we do for RC2?

**Comment by DamianEdwards** [comment]
Yeah we should do that. Assuming we have another tooling build scheduled already, let's get this change into the templates for RC2. @rynowak & @anurse do either of you predict any risk in doing this?

**Comment by rynowak** [comment]
@anurse would know better than I, I'm just here to throw things :laughing: 

Based on my limited experience this change would have no semantic impact on the content of the project.json as configured in the template, and would just make it easier to maintain.

**Comment by rustd** [comment]
Assigning to Phil. @anurse please comment on the risk of this change?

**Comment by phenning** [comment]
TFS: [220101](https://devdiv.visualstudio.com/defaultcollection/DevDiv/_workitems?id=220101&_a=edit)

**Comment by analogrelay** [comment]
No risk that I'm aware of

**Comment by kevinchalet** [comment]
On a related note, should `"Microsoft.NETCore.Platforms" : "1.0.1-*"` be added in the global dependencies?

https://github.com/dotnet/cli/issues/2956#issuecomment-217951884

**Comment by phenning** [comment]
@moozzyk, @anurse, @DamianEdwards, should we add Microsoft.NETCore.Platforms as a base dependency or as a netxxx dependency only as mentioned in the above referenced issue?

**Comment by phenning** [comment]
Another question, should we also move this for console/class libs as well?

//cc: @Pilchie

**Comment by analogrelay** [comment]
> should we also move this for console/class libs as well?

Yes.

> On a related note, should "Microsoft.NETCore.Platforms" : "1.0.1-*" be added in the global dependencies?

Maybe not the global dependencies (though it wouldn't really do any harm). It certainly should be in the `net4X` target.

**Comment by davidfowl** [comment]
Microsoft.NETCore.Platforms should be removed for RTM. It will be a dependency for packages that need it.

**Comment by analogrelay** [comment]
Agree, but for RC2?

**Comment by phenning** [comment]
If we're going to have this for Console/Class, shouldn't this also be in the dotnet new version of those templates as well?

**Comment by analogrelay** [comment]
ugh, yeah probably... I don't think we're going to get that change in though. I think we just have to live with the mild inconsistency. AFAIK, `dotnet new` only creates `netcoreapp1.0` projects, so it's not **that** inconsistent.

**Comment by phenning** [comment]
@anurse, I was thinking the same thing, but wanted to bring it up

**Comment by rustd** [comment]
@cartermp can you please track this change for dot net new. I am not sure what repo tracks that work

**Comment by analogrelay** [comment]
dotnet/cli, as with anything starting `dotnet.exe` :)

**Comment by barrytang** [comment]
I am hearing that we shouldn't take this for RC2 for VS. Let me know otherwise.

**Comment by rustd** [comment]
Moving to RTM

**Comment by phenning** [comment]
N/A for msbuild
