### ISSUE TITLE
Duplicate entry in project.json for Individual Auth template

### ISSUE THREAD

**Issue by rustd** [aspnet/Templates#545]
Following package appears twice. I had the AI option checked.
    "Microsoft.Extensions.CodeGenerators.Mvc": "1.0.0-rc2-20801",

**Comment by phenning** [comment]
TFS: [219705](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?_a=edit&id=219705)

**Comment by phenning** [comment]
a48d453c3d0c264894024370cc9f20d34f6f709b
