### ISSUE TITLE
WebApp With ApplicationInsights does not work

### ISSUE THREAD

**Issue by rustd** [aspnet/Templates#546]
It fails with the following 2 errors

The type or namespace name 'OptionsModel' does not exist in the namespace 'Microsoft.Extensions' (are you missing an assembly reference?)
@using Microsoft.Extensions.OptionsModel

An error occurred during the compilation of a resource required to process this request. Please review the following specific error details and modify your source code appropriately.
/Views/Shared/_Layout.cshtml
'IHtmlHelper<dynamic>' does not contain a definition for 'ApplicationInsightsJavaScript' and no extension method 'ApplicationInsightsJavaScript' accepting a first argument of type 'IHtmlHelper<dynamic>' could be found (are you missing a using directive or an assembly reference?)
@Html.ApplicationInsightsJavaScript(TelemetryConfiguration)

**Comment by rustd** [comment]
This is with the 118 bundle build

**Comment by phenning** [comment]
TFS: [220097](https://devdiv.visualstudio.com/defaultcollection/DevDiv/_workitems/edit/220097)
