### ISSUE TITLE
Should be buildOptions in template, not compilationOptions 

### ISSUE THREAD

**Issue by lajones** [aspnet/Templates#548]
VS build 14.0.25123.00 Update 2
ASP.NET and Web Tools 2015.1 (RC2) 14.1.20425.0

File | New | Project
Select Visual C# | .NET Core | Console Application (.NET Core)
Open up project.json

I see the project.json included below. `compilationOptions` is underlined in green and when I hover over it it says "The compilationOptions option is deprecated. Please use buildOptions instead."

It still builds fine either way.

```
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-3002426"
    }
  },

  "frameworks": {
    "netcoreapp1.0": {}
  }
}
```

**Comment by phenning** [comment]
Fixed with latest templates.
