### ISSUE TITLE
Update template dependencies

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/Templates#549]
I looked through the dependencies of the current templates and some of them look out of date. I created a new wiki page to help us keep track of this easier https://github.com/aspnet/Templates/wiki/Template-dependencies.

For the final release if possible we should get the latest versions of all packages.

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/aspnet/Templates/blob/dev/README.md.
