### ISSUE TITLE
Update rendering of the "name" field in bower.json files

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Templates#550]
Updated Bower renders now warnings when a name field is not _safe_ name, including lower case enforcement. This was wrongly implemented in Bower < 1.7.9 as an error, not as the warning, so users could hit a problem.
I think the VS templates use a hardcoded key(?), which will cause a warning in Bower 1.7.9:

> bower                     invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes

https://github.com/aspnet/Templates/blob/dev/src/BaseTemplates/StarterWeb/bower.json#L2
https://github.com/bower/bower/issues/2233

Thanks!

**Comment by rustd** [comment]
@madskristensen critical for RC2?

**Comment by madskristensen** [comment]
Not critical for RC2, but it is a super low risk change so we might consider doing it for RC2 based on that

**Comment by rustd** [comment]
What would the value of name be?

**Comment by madskristensen** [comment]
The same as in package.json which is "asp.net" I believe

**Comment by rustd** [comment]
Yes. Phil, please do a bar check. This is a low risk change so it should be fine.

**Comment by phenning** [comment]
TFS: [220129](https://devdiv.visualstudio.com/defaultcollection/DevDiv/_workitems?id=220129&_a=edit)

**Comment by peterblazejewicz** [comment]
Thanks!
