### ISSUE TITLE
Commented-out code in Manage/Index.cshtml has errors

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/Templates#553]
Line 47:

```
<text><a asp-controller="Manage" asp-action="AddPhoneNumber" class="btn-bracketed">Add</a>
```

This is missing the closing `</text>` node, so it will cause an error once you uncomment it.

Also it's inconsistent with the docs at http://docs.asp.net/en/latest/security/authentication/2fa.html, which show the surrounding block enclosed in square-bracket chars, whereas the actual code in the file doesn't have those chars - instead it has the CSS class `btn-bracketed` on the `<a>` elements.

**Comment by peterblazejewicz** [comment]
Steve,
I've been a spirit behind the change. The idea was to simplify markup (a lot) by removing both `<text></text>` wherever possible (it appeared <text> are removed completely from the source after the fix) and to remove a noice from markup, those brackets and hardcoded spaces  - to have clean, html markup and only custom tag that are based on TagHelpers (ScriptTagHelper/EnvironmentTagHelper, etc) for new users (like me).
I've made a fix with PR
I could update docs as well, if requested
Thanks!
