### ISSUE TITLE
Add 'dotnet watch' tool to templates by default

### ISSUE THREAD

**Issue by kichalla** [aspnet/Templates#556]
During development I typically use Kestrel so that I can see the log output (I know I could use Debug logger but I do not want to use the Debug mode though). I would like to have the similar experience of IIS Express regarding making a modification and see it take affect immediately. Can we add the `dotnet watch` tool by default to our templates?

@victorhurdugaci

**Comment by sayedihashimi** [comment]
@kichalla what's the experience if you start `dotnet watch` from the command line and then use VS to edit?

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
This could be useful for x-plat experience.

**Comment by kichalla** [comment]
> what's the experience if you start `dotnet watch` from the command line and then use VS to edit?

`dotnet watch` restarts the application when it sees changes to files its watching for

**Comment by sayedihashimi** [comment]
@kichalla so you didn't run into any issues with VS when you started `dotnet watch` from the command line? If so will that work for you?

**Comment by kichalla** [comment]
Like the ask here is to add `dotnet watch` to the template generated projects by default, so that I do not have to add it every time. Basically it gives parity to the experience that we have with IISExpress where the changes are automatically picked up.

**Comment by sayedihashimi** [comment]
@kichalla I understand. I'm trying to understand if using `dotnet watch` today with VS works well or is the scenario blocked and we need any updates for VS?

**Comment by kichalla** [comment]
Ah Ok, got it. Sure it works well with VS.

**Comment by shanselman** [comment]
Let's do this so it works out of the box with VSCode.

**Comment by Neftedollar** [comment]
Hi, is any progress with this feature?

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/aspnet/Templates/blob/dev/README.md.
