### ISSUE TITLE
New template: For more information on enabling MVC for empty projects, visit <not helpful>

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Templates#559]
To repro the problem: (copy/paste of instructions from https://docs.asp.net/en/latest/tutorials/first-mvc-app/adding-view.html )

Right click on the Views/HelloWorld folder, and then Add > New Item.
In the Add New Item - MvcMovie dialog

In the search box in the upper-right, enter view
Tap MVC View Page
In the Name box, keep the default Index.cshtml
Tap Add

The new view has the following content:

```
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
```

The link LinkID=397860
is not very helpful. 
Suggest you remove the entire comment.
@danroth27  or @ardalis might know a better link

**Comment by balachir** [comment]
Agree, at the very least, we should fix the fwlink to point to the correct documentation. I had previously opened bug 153492 in TFS for this same issue as well.

**Comment by rustd** [comment]
Updating the landing page to https://docs.asp.net/en/latest/tutorials/first-mvc-app/adding-view.html
