### ISSUE TITLE
Error page talks about 'development mode'

### ISSUE THREAD

**Issue by glennc** [aspnet/Templates#560]
The error page that we have in the current template tells people that they can get more details by switching into `development mode`.

What was the reasoning for adding this text? It has already started to cause some internal people to hit errors, and it doesn't seem like the right thing to have here. I would expect the error page to be the sort of thing I would be happy to leave in all the way to production. Is there a strong reason not to do that?

**Comment by phenning** [comment]
Motivation is here:  #351

**Comment by glennc** [comment]
@rowanmiller Can we chat about this when you get a chance?

**Comment by rowanmiller** [comment]
@glennc yep, lets chat tomorrow. The main problem is that if you aren't using VS then it's really hard to discover how to get meaningful errors out of your app. @coolcsh hit this prepping for a demo, which is where the idea of adding the text came from.

**Comment by sayedihashimi** [comment]
@rowanmiller @glennc closing this. When you close on a plan reopen if this is needed.
