### ISSUE TITLE
Consider removing unused namespaces in template files

### ISSUE THREAD

**Issue by phenning** [aspnet/Templates#565]
Specifically:

System
System.Linq
System.Collections.Generic
System.Threading.Tasks

**Comment by phenning** [comment]
@DamianEdwards @rustd @Eilon

**Comment by phenning** [comment]
Issue brought up here: 
https://github.com/aspnet/Templates/issues/563

**Comment by Eilon** [comment]
This is 100% by design, please do not change this.

**Comment by Eilon** [comment]
(And it's by design for the reason you mentioned in the other bug.)

**Comment by rustd** [comment]
This is by design. Please don't change this. Closing this.

**Comment by dougbu** [comment]
Discussed this issue offline w/ @Eilon. Filed OmniSharp/omnisharp-vscode#315, "VS Code extension: Do not warn about unused `using`s".

Side note: My concern was specific to project templates. But I understand doing one thing everywhere.
