### ISSUE TITLE
Unable to build 

### ISSUE THREAD

**Issue by locdognec** [aspnet/Templates#567]
When i run the build.cmd i got this error. Can you help ? 
C:\Users\user\Downloads\Templates-dev\src\BaseTemplates\BaseProjectTemplates.csproj(118,5): error : Last line in a
file must be a non-blank line terminated with \r\n: BaseProjectTemplates.csproj line 150, '</Project>'
C:\Users\user\Downloads\Templates-dev\src\BaseTemplates\BaseProjectTemplates.csproj(118,5): error : Last line in a
file must be a non-blank line terminated with \r\n: ClassLibrary.vstemplate line 28, '</VSTemplate>'
C:\Users\user\Downloads\Templates-dev\src\BaseTemplates\BaseProjectTemplates.csproj(118,5): error : Last line in a
file must be a non-blank line terminated with \r\n: ClassLibrary\Class1.cs line 16, '}'
C:\Users\user\Downloads\Templates-dev\src\BaseTemplates\BaseProjectTemplates.csproj(118,5): error : Last line in a
file must be a non-blank line terminated with \r\n: ClassLibrary\ClassLibrary.xproj line 21, '</Project>'
C:\Users\user\Downloads\Templates-dev\src\BaseTemplates\BaseProjectTemplates.csproj(118,5): error : Last line in a
file must be a non-blank line terminated with \r\n: ClassLibrary\project.json line 13, '}'
C:\Users\user\Downloads\Templates-dev\src\BaseTemplates\BaseProjectTemplates.csproj(118,5): error : Last line in a
file must be a non-blank line terminated with \r\n: Common\Properties\AssemblyInfo.cs line 19, '[assembly: Guid("$guid1
$")]' 
........

**Comment by phenning** [comment]
Interesting, it looks like when you download the repo as a zip either the zip process or unzip process is causing the CR+LF to be converted to LF in the source files. 

You can work around this for now by cloning the repo and working with it directly. I'll see what I can do to add a parameter to disable that validation step as a more permanent workaround

**Comment by locdognec** [comment]
Thanks, that worked fine. After the temples are created i copy them to VS but when i try to create a new project i got this error
![capture](https://cloud.githubusercontent.com/assets/19325273/15248802/d0f45b28-1924-11e6-81f5-32fb75c59104.PNG)

**Comment by phenning** [comment]
You don't have the latest VS tooling. 

This repo is used for development of in-flight releases, so there is occasionally lag time between the tooling releases and what is present in the repository.

Also keep in mind from https://github.com/aspnet/Templates/wiki/Building-and-Running:

> Do not extract the contents of these zips manually to your Visual Studio template folders, doing so can later cause issues when upgrading to a later official build of the templates.
> The build also produces samples which are extracted from the generated template content. You can find these generated samples in the intermediate\test folder. This generated sample content is also used by the unit tests.

You can however run the samples by running **dotnet run** from the command line in the sample's intermediate\test folder. By using dotnet run, you bypass the visual studio experience, but you can at least run the samples.

**Comment by locdognec** [comment]
any idea when VS15 will support the new release?

**Comment by phenning** [comment]
@locdognec, You can find download links via the following announcement: https://blogs.msdn.microsoft.com/webdev/2016/05/16/announcing-asp-net-core-rc2/
