### ISSUE TITLE
AI+ Work & School Account + SSO (no Read/Write) broken

### ISSUE THREAD

**Issue by rustd** [aspnet/Templates#569]
With bundle 128
Create a Web App template with Work & School Account and you get the following error:
The project fails at runtime with a runtime exception.

![orgauthsso](https://cloud.githubusercontent.com/assets/1132652/15255284/f0edcd68-18ef-11e6-9b7d-434d953c9d55.PNG)

**Comment by phenning** [comment]
Templates.xml is wrong.

**Comment by rustd** [comment]
@phenning can you please open a TFS bug for triage. I think we should fix it because this is broken right now

**Comment by phenning** [comment]
TFS: [221575](https://devdiv.visualstudio.com/defaultcollection/DevDiv/_workitems?id=221575&_a=edit)

**Comment by MaxxDelusional** [comment]
As a workaround I copied the Startup.cs file from `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\WebTemplates\DNX\CSharp\1033\Rules\StarterWeb\AI\OrganizationalAuth\Single\NoRead` and placed it in the parent directory.
