### ISSUE TITLE
ASP.NET templates do not appear together in the New Project dialog - Visual C# node

### ISSUE THREAD

**Issue by balachir** [aspnet/Templates#571]
VS 2015 U2 + DotNetCore RC2 Tooling Preview1
1. File > New Project

ACTUAL
At first glance, it appears that only the "ASP.NET Web Application (.NET Framework)" template is there in the list. I can see "Class Library (.NET Core)" and "Console Application (.NET Core)".

The other templates "ASP.NET Core Web Application (.NET Core)" and "ASP.NET Core Web Application (.NET Framework)" are actually also there in the list but you need to scroll down and they seem to be at random locations

![image](https://cloud.githubusercontent.com/assets/8246794/15306223/a3c3613e-1b7d-11e6-8a10-84bbd7bd666a.png)

EXPECTED
ASP.NET Core Web Application templates should appear together. And possibly higher up in the list of templates as well

**Comment by sayedihashimi** [comment]
Looks like we did not set the num rollup correctly.

**Comment by phenning** [comment]
This is all based on the sort orders in the vstemplates.

Current sort orders for templates:

ASP.NET Web Application (.NET Framework) - 15
ASP.NET Core Web Application (.NET Core) - 25
ASP.NET Core Web Application (.NET Framework) - 35

Class Library (.NET Core) - 18
Console Application (.NET Core) - 19

The following one is from the .NET Core node and we should probably set NumberOfParentCategoriesToRollUp = 0 for this one to prevent it from being duplicated with the one above.
ASP.NET Core Web Application (.NET Core) - 100

**Comment by phenning** [comment]
We could try setting the following:

ASP.NET Core Web Application (.NET Core) -  16
 ASP.NET Core Web Application (.NET Framework) - 16

Setting them to be the same will then cause them to be sorted alphabetically and right after the ASP.NET Web Application (.NET Framework) template which is at 15. If we want these first, we could try setting the sort order to both these to 14.

And remove the rollup categories from the .NET Core node Core Web App vstemplate.

**Comment by sayedihashimi** [comment]
Here is what we discussed today, let's make sort order to 15 for:
- ASP.NET Web Application
- ASP.NET Core Web Application (.NET Core)

**Comment by phenning** [comment]
Assuming this is the desired order:

ASP.NET Web Application (.NET Framework)
ASP.NET Core Web Application (.NET Core)
ASP.NET Core Web Application (.NET Framework)

We need to have Web Application = 14, and the other two set = 15. If we set everything to 15, then the non DotNet templates will appear first, both here AND in the Web node.

The following templates are already in the sort order, so this is really the only option to wedge ourselves in at the rollup level.

15 -- Shared Project (ProjectTemplates\CSharp\Windows Root\Windows\1033\SharedProject) 
14 -- Hub Application (ProjectTemplates\CSharp\Windows Root\Store Apps\Universal Apps\1033\SharedHubApplication)

**Comment by phenning** [comment]
Resulting UI, as suggested:

![image](https://cloud.githubusercontent.com/assets/2433750/15334587/b6b2b604-1c23-11e6-8c9a-2d831a3864ff.png)

**Comment by balachir** [comment]
@phenning I believe we wanted to show only the following templates in the top-10 list
ASP.NET Web Application (.NET Framework)
ASP.NET Core Web Application (.NET Core)

The template below can remain lower down in the list (where it is now)
ASP.NET Core Web Application (.NET Framework)

This is so that we don't completely take over the top-10 list of Visual C# node with all the ASP.NET templates.

**Comment by phenning** [comment]
Updated in WTE
