### ISSUE TITLE
A template for "Class Library (.Net Framework)" that will use the new project structure.

### ISSUE THREAD

**Issue by fredrikn** [aspnet/Templates#572]
If we craete a "Asp.Net Core (.Net Framework)" project, and then will add a Class Library. We have three templates:

Class Library - Uses the old project structure with .csproj

Class Library (Portable) - Like a hybrid with project.json and .csporj file.

Class Library (.Net Core) - Uses the new project structure but by default target the .Net Standard Library.

It's possible to add a Class Library (.Net Core)  and do changes in the project.json to the following:

{
  "version": "1.0.0-*",

  "dependencies": { },

  "frameworks": {
    "net461": { }
  }
}

 and then it will work to add it as a reference to a "Asp.Net Core (.Net Framework)" project (but by default the "Class Library (.Net Core)" doesn't). So what would be nice is a "Class Library (.Net Framework)" which uses the new project structure.

**Comment by davidfowl** [comment]
When we make the shift to msbuild in the next version of visual studio. Not enough things work end to end to have a template right now.
