### ISSUE TITLE
Individual Auth template should contain multiple _ViewImports.cshtml for each view folder.

### ISSUE THREAD

**Issue by phenning** [aspnet/Templates#573]
The current content of this file is problematic when you want to add a controller and views that have models to display on the Index page because ManageViewModels contains an IndexViewModel class already.

```
@using IndividualAuth
@using IndividualAuth.Models
@using IndividualAuth.Models.AccountViewModels
@using IndividualAuth.Models.ManageViewModels
@using Microsoft.AspNetCore.Identity
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
```

Instead we should have the root _ViewImports just contain:

```
@using IndividualAuth
@using IndividualAuth.Models
@using Microsoft.AspNetCore.Identity
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
```

Then add a _ViewImports to the Manage and Account Views folders:

`@using Microsoft.Models.ManageViewModels`

**Comment by mlorbetske** [comment]
Let's figure out how this story completes - if we do a ViewImports per area it creates a sort of cascade in where to figure out where usings are coming from and we should make the template versus the editing experiences consistent. Should adding a new view to a subfolder generate a viewimports for that location?

**Comment by Eilon** [comment]
This issue was moved to aspnet/templating#114
