### ISSUE TITLE
Edit does not scaffold Id field

### ISSUE THREAD

**Issue by dvdobrovolskiy** [aspnet/Templates#584]
[HttpPost]
[ValidateAntiForgeryToken]
public async Task<IActionResult> Edit(int id, [Bind("RSOTimeToResponce,RiseToRSO,Title,UKOTimeToResponce,ZayavkaReasonType,ZayavkaType,ZayavkaAskTime")] Reason reason)

No Id field in Bind("...") so it cannot update row

**Comment by phenning** [comment]
Opened scaffolding bug:
https://github.com/aspnet/Scaffolding/issues/243

Closing this one
