### ISSUE TITLE
Configure logging from Program.Main() instead of injecting ILoggerFactory in Startup.Configure

### ISSUE THREAD

**Issue by kevinchalet** [aspnet/Templates#586]
Currently, the logging listeners are added in `Startup.Configure`. Ideally, the ASP.NET Core templates should use the new `WebHostBuilder.ConfigureLogging` method instead of injecting `ILoggerFactory` via `Startup.Configure`:

``` csharp
namespace OpenIdConnectSample
{
    public static class Program
    {
        public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .ConfigureLogging(options => options.AddDebug(LogLevel.Information))
                .Build();

            host.Run();
        }
    }
}
```

**Comment by sayedihashimi** [comment]
@DamianEdwards @davidfowl thoughts?

**Comment by davidfowl** [comment]
Not sure about this, I thought about it as well but if you configure logging based on the configuration system we'll end up reading `appsettings.json` in the `Program.Main` which I'm not a fan of. Ideally host configuration and `Startup` configuration would remain separate.
