### ISSUE TITLE
Make No Auth the default for web projects

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/Templates#587]
I'm having a discussion with @davidfowl @DamianEdwards @shanselman @coolcsh and we are thinking to change the default for web projects to be `No Auth`.

**Comment by brockallen** [comment]
+1

**Comment by peterblazejewicz** [comment]
We (at work) usually create couple of interim short projects in VS to test ideas before trashing them completely or moving good parts of implementation to other project we are working on. That is a frustrating UX experience to always uncheck Auth to check to No Auth. I 100% prefer generator quick and dirty starter web project with no auth (as the only option).

**Comment by sayedihashimi** [comment]
Reopening
Please make No Auth the default across all templates that we own.

**Comment by phenning** [comment]
Fixed for all templates we own, including ASP.NET 4
