### ISSUE TITLE
Follow RESTful conventions in new Web App project templates

### ISSUE THREAD

**Issue by eavonius** [aspnet/Templates#588]
I have been messing around with the aspnet core 1.0 rc2 release and I'd like to make a few suggestions. When you create a new aspnet core "Web Application" using the template and "Individual User" authentication, the default controllers and views that are generated are a mish-mash of actions and views that don't enforce good RESTful MVC resource naming conventions.

In most MVC apps (rails, ASP.NET MVC, expressjs, etc.) models and their relationships are the heart of the application's structure. If the models and their relationships are designed well, the rest of the application's controllers and views follow suit by consistently following the resource naming conventions.

As an example, the devise framework used in many rails applications also provides user authentication, profile management, and typical things like password recovery as is also the case in this generated code. However, that framework follows RESTful MVC conventions and so the generated code's conventions are no different than that which a developer would create themselves.

I would like to see the generated Account and Manage controllers restructured to follow RESTful resource conventions. Account should have its own create, edit, update, show views. Edit is currently essentially the Manage->Index view. Manage is not a resource/model, so why is it a controller? Passwords should have their own controller if there are separate views for editing your password for example, not shoved into the Manage controller. For example, if your app allows users to edit a password, this goes in the Passwords controller, Edit action. If passwords don't need an index or show page, just don't create them - but don't bundle password management into "Manage". Login should be Sessions->New and logout Sessions->Destroy. Again, take a look at devise - they do this very well.

Another suggestion would be to have a ViewModels root folder instead of adding it as a sub-directory of Models, with sub-directories named after the controller. For example ViewModels\Account or ViewModels\Password. The classes within are named after the action, for example ViewModels\Account\Create.cs, ViewModels\Account\Edit.cs.

Thanks for your consideration.

**Comment by davidfowl** [comment]
@eavonius Can you make a sample application with exactly what you'd like to see in a github repository? That would be easier to look at.

**Comment by eavonius** [comment]
I'm about 3/4ths of the way done with an example from refactoring this. One issue I ran into though is that I moved the user related controllers and views into an area and now the layout is not being rendered.

Is it possible for an area to reuse the "default" layout, or do you have to re-implement the layout again?

**Comment by eavonius** [comment]
My initial project is here so you can see where I'm going with it. I still need to fix the layout issue in the area and refactor the rest of the "Manage" controller actions into appropriate REST resources.

https://github.com/eavonius/aspnetcore-restful-auth-sample

**Comment by peterblazejewicz** [comment]
@eavonius 
I'll try to help you wit this. Thanks!

**Comment by phenning** [comment]
@eavonius you need to set asp-area="" in any shared layout you want to use in an area. We recently changed this in the template.

Editted, oh you meant the layout wasn't being rendered.

**Comment by eavonius** [comment]
@phenning I worked around this by adding a _ViewStart to the area's Views folder that specifies the layout - this fixed that problem. I do believe there may be a defect I found though in that any forms that have the asp- attributes on them aren't updated at runtime. I tried adding a _ViewImports to the Area that matches the one in the root "Views/Shared" folder but then I get lambda exceptions from the core of MVC.

Perhaps there is a defect with Areas and using the tag helpers?

**Comment by eavonius** [comment]
Just to clarify (you'll see this in the README for my example project) the philosophy behind the changes I'm recommending is that it is critical in MVC architectures to always think through what resources are being modified and how they fit into the standard Index/Details/Create/Edit/Delete pattern of REST. 

Without demonstrating this in out of the box code from Microsoft, it leads to developers putting actions on controllers that can be named everything which leads to the typical "service" pattern which is just a grab bag of methods. I know this might seem like "splitting hairs" but the nice thing is that then you can have other assets in a project (unit tests, security policy enforcement, test fixture data) that follow the same naming conventions (controller name->action name) and auto-load things by convention instead of configuring them. I know the .NET community doesn't have as many extensions for MVC as rails but there's no reason why it can't if REST is adhered to.

Totally open to discussing the implications of this - I know it would mean a significant refactoring to several of the existing templates to achieve this.

**Comment by Eilon** [comment]
This issue was moved to aspnet/templating#112
