### ISSUE TITLE
Add better Console template for writing command line apps

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Templates#59]
This is a proposal issue. Looking at https://github.com/aspnet/UserSecrets/tree/dev/src/Microsoft.Framework.SecretManager, we can create a template that helps people author command line applications. We can take the base functionality and make something that acts as a starting point.

**Comment by peterblazejewicz** [comment]
The link needs to be updated:
https://github.com/aspnet/UserSecrets/blob/dev/src/Microsoft.Extensions.SecretManager/Program.cs

**Comment by phenning** [comment]
Our team does not own the console templates any more.
