### ISSUE TITLE
Include asp-area="" in links under Views/Shared/ views

### ISSUE THREAD

**Issue by javiercn** [aspnet/Templates#591]
- It teaches the customers what the right thing to do when they share views.
- It prevents issues that happen when a customer decides to include an area and their layout links suddenly change depending on whether they are rendering a view within an area or not.
- It will prevent a flood of incoming issues like https://github.com/aspnet/Mvc/issues/4815

**Comment by phenning** [comment]
Thoughts? Preview2 tooling or post?

//cc @mlorbetske @sayedihashimi @Eilon

**Comment by Eilon** [comment]
I'm not too concerned about adding this at all. Most sites don't use areas, so I don't really want to add extra stuff to the template in case someone adds areas. There's lots of other stuff we also don't put in the templates that you might need if you then make other changes to the template.

**Comment by phenning** [comment]
This one seems rather ugly though for customer to fix, and its not obvious what you need to do in order to fix it.

**Comment by Eilon** [comment]
Ok, thought about it some more, would be nice to add this. But perhaps not super urgent, so if it's too busy for this release, it can wait.

**Comment by phenning** [comment]
Thanks Eilon, we'll be able to get this in along with #595 easily.
