### ISSUE TITLE
Add Areas to publishOptions

### ISSUE THREAD

**Issue by rynowak** [aspnet/Templates#595]
See user-reported issue here: https://github.com/aspnet/Mvc/issues/4827#issue-159058385

Can we just include `Areas/**/Views` by in the template?

**Comment by phenning** [comment]
If we add this, we should definitely do #593 as well.

@Eilon

**Comment by phenning** [comment]
#591 the issue, #593 is the PR for it

**Comment by Eilon** [comment]
Ok, thought about it some more, would be nice to add this. But perhaps not super urgent, so if it's too busy for this release, it can wait.
