### ISSUE TITLE
Re-arrange asp-area tag attribute placement

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Templates#597]
The https://github.com/aspnet/Templates/pull/593 adds `asp-area` (in this order). 

```
<li><a asp-controller="Home" asp-area="" asp-action="Index">Home</a></li>
```

Can the order be:

```
<li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
```

The tag attributes should follow MVC framework mantra: area/controller/action I think.
Thanks!

**Comment by phenning** [comment]
Good idea, we should do this now.

**Comment by peterblazejewicz** [comment]
Thanks!
