### ISSUE TITLE
missing /Account/AccessDenied method/view for unauthorized requests

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Templates#608]
By default, when you 

```
return new ChallengeResult();
```

for unauthorized requests, you are redirected to 

http://localhost:port/Account/AccessDenied?ReturnUrl=<where you were>

The account controller needs an AccessDenied method/view.

**Comment by phenning** [comment]
What did you use for the base template?

Do you have a repro project? 

I can't repro this with either NoAuth or IndividualAuth.

**Comment by Rick-Anderson** [comment]
Closing until I come up with a repro

**Comment by Rick-Anderson** [comment]
1. Create a new web app with auth
2. Update the contact method in the home controller with the following:

```
public IActionResult Contact()
{
    ViewData["Message"] = "Your contact page.";

    //return View();
    return new ChallengeResult();
}
```

Launch and Tap on Contact. You are redirected to the log in page. 
Tap the register link and register.
Tap the Contact link again. This time you're redirected to http://localhost:2207/Account/AccessDenied?ReturnUrl=%2Fcontacts%2FEdit%2F1

which does not exist so you get a 404 on some browsers, nothing on others.

**Comment by phenning** [comment]
@Haok, should we add an AccessDenied action here for the CookieAuthentication handler to handle this?

preview2 or post?

@mlorbetske @sayedihashimi

**Comment by HaoK** [comment]
Yeah probably a nicer error experience

**Comment by phenning** [comment]
I talked to @barrytang, we'll take this post preview2, for now if people run into this they can add the view and code in the referenced pull request.

**Comment by Rick-Anderson** [comment]
@phenning  thanks. I'll document this. Do you need `[AllowAnonymous]` ? The request in authenticated at this point.

**Comment by phenning** [comment]
Actually, I don’t think we need to use AllowAnonymous in this case.
