### ISSUE TITLE
Correct or replace link for `AddUserSecrets()`

### ISSUE THREAD

**Issue by dougbu** [aspnet/Templates#612]
The link in the comment below (from `Startup` in most templates) takes the user to https://github.com/aspnet/Home/wiki/DNX-Secret-Configuration This is an old page; should instead take user to https://docs.asp.net/en/latest/security/app-secrets.html

``` c#
// For more details on using the user secret store see http://go.microsoft.com/fwlink/?LinkID=532709
```

I haven't checked other `fwlink` URIs in the generated files. Might contain more stale links.

See also aspnet/Docs#1390

**Comment by phenning** [comment]
We should update the fwlink pointer for link 532709

**Comment by sayedihashimi** [comment]
FWLink updated to https://docs.asp.net/en/latest/security/app-secrets.html
