### ISSUE TITLE
Please uniform some words in the standard template

### ISSUE THREAD

**Issue by sgjsakura** [aspnet/Templates#614]
_I don't know where to post this issue. Please move it to a more suitable place if possible, thanks!_

In ASP.NET Core default templates, the default use logon related action are named as "Login" and "LogOff", I think this is not standardized. 

In Chapter 3.1 (_Word Choices_) of the Book _Framework Design Guidelines: Conventions, Idioms, and Patterns for Reusable .NET Libraries_, (The .NET Guideline book recommended in MSDN library), it says:

> DO use the word "Log On" and "Log Off"， DO NOT use the words "Login" and "Logout"

So I think all the word `Login` in the .NET Core library and template should be renamed into `LogOn`. Maybe it is difficult to renaming the member idenfiers for backward compatiblity, however I think changing a word in the template is not a so difficult work.

If you guys really like the words "login" , or you pick this word cause the library has a class named `ExternalLoginInfo` and you may want to keep in line with it, please at least make the naming style uniform and just change the name "logoff" into "logout" and it will make much more sense :-(

The coding style of the BCL and standard template will reflect the product quality for all users, so please be more careful to non-ciritcal problems like this and make it better :-)

**Comment by peterblazejewicz** [comment]
On the other hand: [Sign in to or out of Windows](http://windows.microsoft.com/en-us/windows-8/sign-in-out-of-windows) 😸

**Comment by sgjsakura** [comment]
@peterblazejewicz The terms "Sign In" and "Sign Out" is ok since we never say "Sign on" or "Sign off". The .NET Core BCL also uses these words in some places (e.g. `SignInManager<TUser>`). This issue is only related to words started with "log" :-)

**Comment by phenning** [comment]
If anything we should probably update Logoff to Logout to be consistent with CookieAuthenticationDefaults (https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationDefaults.cs)

In any event, this does not meet the bar for preview2 release.

**Comment by mlorbetske** [comment]
Let's change "logoff" to "log out"
