### ISSUE TITLE
Site homepages claim it uses Gulp, but it no longer does

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/Templates#616]
This is also mentioned in https://github.com/aspnet/Templates/issues/538, but that issue is slightly different as it's specific to the "Empty" template. This issue covers Gulp being mentioned in the non-empty template too - we should not mention Gulp at all, as it's not in there by default.

**Comment by scottaddie** [comment]
@SteveSandersonMS @phenning I believe this was already addressed with PR https://github.com/aspnet/Templates/pull/605.

**Comment by phenning** [comment]
Indeed fixed by #605
