### ISSUE TITLE
"Run tools such as EF..." takes the user to cli tools which don't mention EF

### ISSUE THREAD

**Issue by moozzyk** [aspnet/Templates#620]
![image](https://cloud.githubusercontent.com/assets/1438884/16162449/6686ace4-3488-11e6-9f2b-36cd82cd36f1.png)

Takes the user to:
https://dotnet.github.io/docs/core-concepts/core-sdk/cli/index.html

which does not mention EF at all since these are basic CLI tools.

**Comment by mlorbetske** [comment]
Let's update the FWLink for this one to point at more EF centric documentation

**Comment by Eilon** [comment]
This issue was moved to aspnet/templating#111
