### ISSUE TITLE
update "Learn more" link on Change Authentication/Individual User accounts

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Templates#623]
![learnmore](https://cloud.githubusercontent.com/assets/3605364/16167970/8825bb32-34b1-11e6-8e66-93d81a5a99ca.PNG)

The link goes to http://www.asp.net/visual-studio/overview/2013/creating-web-projects-in-visual-studio#auth

**Comment by phenning** [comment]
The templates don't drive this Learn more link, this particular learn more link is just in tooling and is the same fwlink depending on auth type chosen in VS 2013 and VS 2015.

IndividualAuth: 299423
NoAuth:  299422
Work and School: 299424
WindowsAuth: 299425

**Comment by phenning** [comment]
Moving to backlog since this is not specific to DotNet templates, and has been this way through all o VS 2015.

**Comment by phenning** [comment]
@sayedihashimi, @mlorbetske FYI

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/aspnet/Templates/blob/dev/README.md.
