### ISSUE TITLE
Consider changing to standard Boostrap form layout instead of "form-horizontal"

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Templates#626]
The templates currently use the [horizontal form layout from Bootstrap](http://getbootstrap.com/css/#forms-horizontal), which results in a **lot** more markup being required for the forms in the template. We should consider changing to the [standard Bootstrap form layout](http://getbootstrap.com/css/#forms-example) as it results in much simpler template markup while retaining a perfectly usable form layout.

Example of markup required for horizontal form layout:

``` html
<form class="form-horizontal">
  <div class="form-group">
    <label for="email" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
      <input type="email" class="form-control" id="email" placeholder="Email">
    </div>
  </div>
  <div class="form-group">
    <label for="password" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-10">
      <input type="password" class="form-control" id="password" placeholder="Password">
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="checkbox">
        <label>
          <input type="checkbox"> Remember me
        </label>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Sign in</button>
    </div>
  </div>
</form>
```

Example of simpler, standard layout form markup:

``` html
<form>
  <div class="form-group">
    <label for="email">Email</label>
    <input type="email" class="form-control" id="email" placeholder="Email">
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input type="password" class="form-control" id="password" placeholder="Password">
  </div>
  <div class="checkbox">
    <label>
      <input type="checkbox"> Remember me
    </label>
  </div>
  <button type="submit" class="btn btn-default">Sign in</button>
</form>
```

**Comment by mikes-gh** [comment]
@DamianEdwards I see your point but I prefer horizontal. Just my 2c 
I did actually use most of the template markup as is for individual accounts so it saved me a lot of work and seemed to be good for mobile and desktop in the horizontal.
I actually learnt horizontal forms from the template.

**Comment by DamianEdwards** [comment]
@mikes-gh no doubt that some get a benefit with the way it is now, but I think we need to optimize for the simplest, functional example in the template. The different in this case is quite dramatic.

**Comment by mikes-gh** [comment]
Yeh I don't have a problem with that.  Make as simple as possible there's enough to take in.

**Comment by peterblazejewicz** [comment]
```
<form asp-controller="Account" asp-action="Login" method="post">
    <div asp-validation-summary="All"></div>
    <div class="form-group">
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control" placeholder="Email">
        <span asp-validation-for="Email" class="help-block"></span>
    </div>
    <div class="form-group has-error">
        <label asp-for="Password"></label>
        <input asp-for="Password" class="form-control" placeholder="Password">
        <span asp-validation-for="Password" class="help-block" >Error description</span>
    </div>
    <div class="checkbox">
        <label>
            <input asp-for="RememberMe" />
            @Html.DisplayNameFor(m => m.RememberMe)
        </label>
    </div>
    <button type="submit" class="btn btn-default">Log in</button>
</form>
```

The checkbox cannot be nicely written in Razor yet: https://github.com/aspnet/Mvc/issues/2369

This will render in current templates (out-of-the-box):
![image](https://cloud.githubusercontent.com/assets/14539/16243745/ff603ee4-37f8-11e6-9372-0fbc2b700d02.png)

The `has-error`and error message are just added to present validation state.

**Comment by Eilon** [comment]
This issue was moved to aspnet/templating#106
