### ISSUE TITLE
Update-Database does not work as suggested in Template error page

### ISSUE THREAD

**Issue by HaoK** [aspnet/Templates#627]
When accessing database after create a new Individual Auth Web App, error page shows:

In Visual Studio, you can use the Package Manager Console to apply pending migrations to the database:
PM> Update-Database 

This actually does not work by default, either this text should be removed, or something needs to be fixed?

**Comment by phenning** [comment]
EF is responsible for the content of this page, it is not coming from the template,

**Comment by HaoK** [comment]
I'll move this to EF, thanks

**Comment by HaoK** [comment]
https://github.com/aspnet/EntityFramework/issues/5840
