### ISSUE TITLE
ApplicationDbContextModelSnapshot is referring to -rc3

### ISSUE THREAD

**Issue by moozzyk** [aspnet/Templates#631]
The product version in ApplicationDbContextModelSnapshot is hardcoded to `1.0.0-rc3`

https://github.com/aspnet/Templates/blob/26b9b046d5d858995021a53e6479ab0fb62cbbfa/src/Rules/StarterWeb/IndividualAuth/Data/Migrations/ApplicationDbContextModelSnapshot.cs#L18

```
.HasAnnotation("ProductVersion", "1.0.0-rc3")
```

After talking to @bricelam "1.0.0" should be fine.

Related issue in the EF repo: https://github.com/aspnet/EntityFramework/issues/5846

**Comment by phenning** [comment]
Does this break anything?

**Comment by moozzyk** [comment]
No. It's not breaking. We talked with @Eilon and @bricelam and we are not rebuilding because of this.

**Comment by phenning** [comment]
Resolving this, as we'll update the migrations again post 1.0, and we'll catch this then
