### ISSUE TITLE
 Incorrect casing in Bower item template description #622 

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/Templates#637]
From https://github.com/aspnet/Tooling/issues/622 @scottaddie
The "Bower Configuration File" item template will create a file named `bower.json`. The template's description should reflect that name exactly. Please convert the uppercase "B" to lowercase.

![bowerjson](https://cloud.githubusercontent.com/assets/10702007/16420128/cca22018-3d15-11e6-9eca-b4e47680288a.png)

The screenshot above depicts what I'm seeing in VS 2015 Update 3.

**Comment by phenning** [comment]
Easy fix, we should also update the description and remove the awkward wording:

Bower Configuration Files: bower.json and .bowerrc
and for WAP and websites it should read:
Bower Configuration File: bower.json

**Comment by phenning** [comment]
Fix checked into WTE

**Comment by scottaddie** [comment]
@phenning Thanks for the quick turnaround on this! It's very much appreciated.
