### ISSUE TITLE
Could we have lightweight template?

### ISSUE THREAD

**Issue by barrytang** [aspnet/Templates#642]
Opened on behalf of @miloush.

Something between Empty and Web?
 That wouldn't have any packages, javascript code or functional structure - just say one static view and one controller saying hello? Kind of minimum MVC...

Because currently when you want to create a new project, you either go with Empty and don't really know what you need, or you go with Web, deleting everything until it breaks...

The Web template is good for learning how to do things, but not to do them.

**Comment by sayedihashimi** [comment]
Hi @miloush thanks for the suggestion.

I've discussed with @madskristensen and he is going to start looking at this along with @Ladynaggaga I believe. Once we get more details we can see if we have the right content, and then figure out in what release we may be able to include this.

**Comment by madskristensen** [comment]
2 new templates are now available here https://visualstudiogallery.msdn.microsoft.com/31a3eab5-e62b-4030-9226-b5e4c9e1ffb5

**Comment by miloush** [comment]
That looks great, thanks Mads, I will give it a try!

**Comment by ArgTang** [comment]
These templates work great!

**Comment by miloush** [comment]
Well, same issue with ASP.NET Core 2.0 and Visual Studio 2017. This should really be part of the built-in templates.

**Comment by Eilon** [comment]
This issue was moved to aspnet/templating#105
