### ISSUE TITLE
[Identity] ResetPassword is using FindByNameAsync, not FindByEmailAsync

### ISSUE THREAD

**Issue by brockallen** [aspnet/Templates#643]
Moved here from: https://github.com/aspnet/Identity/issues/865

The template is using the wrong API to find the account for password resets. It should be based on email, not the username. This makes it easier for people who use the template and don't use email for the username.

**Comment by phenning** [comment]
Fixed by PR #665

**Comment by brockallen** [comment]
Thanks.
