### ISSUE TITLE
Work and School Accounts - The operation could not be completed

### ISSUE THREAD

**Issue by wangkanai** [aspnet/Templates#644]
I'm not sure what is wrong the template ASP.NET Core with Work and School Accounts authentication i get the following error when trying to build a **clean** project.

> The operation could not be completed, The parameter is incorrect.

![work-school-accounts](https://cloud.githubusercontent.com/assets/10666633/16541824/2b617044-40b9-11e6-98f9-7e8f60fba07a.png)

Visual Studio 2015 Update 3
ASP.NET Core 1.0 RTM
ASP.NET Tooling Preview 2

**Comment by wangkanai** [comment]
```
Visual Studio 2015 Update 2
ASP.NET Core 1.0 RTM
ASP.NET Tooling Preview 2
```

**Comment by phenning** [comment]
This is fixed in current releases
