### ISSUE TITLE
Clean up assemblyinfo.cs

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/Templates#647]
There are some entries in assemblyinfo.cs that is not needed and should be removed, for example `ComVisible`. Originally reported at https://twitter.com/jcansdale/status/749029292093374465.

**Comment by jcansdale** [comment]
![comvisible](https://cloud.githubusercontent.com/assets/11719160/16595938/7f04997e-42e9-11e6-8e7f-010617029587.png)

I noticed that COM has been mostly scrubbed from the new .NET releases, but it was a shame to see new project templates marked with `ComVisible` and `Guid` attributes. Thanks for looking in to this!

**Comment by jcansdale** [comment]
BTW, the .NET Core, 'Add New Item' / 'Assembly Information' file has the same issue:

![netcore_addnewitem](https://cloud.githubusercontent.com/assets/11719160/16727211/f9ac9510-4757-11e6-885f-91dd6f1334b3.png)

```
// Setting ComVisible to false makes the types in this assembly not visible
// to COM components.  If you need to access a type in this assembly from
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("401c34a3-b0a7-427f-8f02-7c0131e7f82b")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version
//      Build Number
//      Revision
//
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
```

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/aspnet/Templates/blob/dev/README.md.
