### ISSUE TITLE
Ensure all templates have a unique FWLink for Learn More

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/Templates#648]
I noticed that the Azure\* templates all share the same FWLink https://go.microsoft.com/fwlink/?LinkID=517593, which is not ideal. Each template should have a unique FWLink (even if it points the the same final dest).

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/aspnet/Templates/blob/dev/README.md.
