### ISSUE TITLE
Consider changing debugType to portable for .NET Core projects

### ISSUE THREAD

**Issue by bitcrazed** [aspnet/Templates#650]
Since one of the major selling points for .NET Core is project portability across platforms, it might make sense to set buildOptions.debugType to "portable" by default.

This req' comes following my attempt at [trying to debug ASP.Net project using VSCode](https://twitter.com/bitcrazed/status/751464295121063936).

**Comment by mlorbetske** [comment]
@bitcrazed it seems like this should be the case for projects generated with `dotnet new` for sure, is this the right default for templates created in VS? @davidfowl any thoughts?

**Comment by sayedihashimi** [comment]
We discussed different options here. I think where we landed was that we don't want to change the default in the csc task, but we can use "dotnet build" (or msbuild targets) to define the default based on platform. The change required was to risky for the previous release so we decided to do a template update.

**Comment by phenning** [comment]
@mlorbetske This was implemented in the SDK? Closable?

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/aspnet/Templates/blob/dev/README.md.
