### ISSUE TITLE
GeoChart Google Visualization not showing certain countries in ASP.NET

### ISSUE THREAD

**Issue by Ponant** [aspnet/Templates#651]
Hi, This bug has been submitted to google visualization on GitHub and Stackoverflow, but it seems to us it is more related to asp.net templates because it works without ASP.NET in VS. 
http://stackoverflow.com/questions/38346452/geochart-google-visualization-not-showing-certain-countries-in-asp-net

**Comment by mlorbetske** [comment]
@Ponant how does the current template content interfere with this? I've read the issue, but don't understand the link between the issue you're seeing and what's in the templates

**Comment by Ponant** [comment]
@mlorbetske , it is unfortunately difficult for me to give you a good indication. The only thing I can say is that the issue occurs when I use the code shown in Stackoverflow in an ASP.NET app. By creating only an html file on the desktop, the issue disappears. If you wish, you can follow the simple steps in the link above and check it out.

**Comment by Ponant** [comment]
http://stackoverflow.com/questions/38346452/geochart-google-visualization-not-showing-certain-countries-in-asp-net
