### ISSUE TITLE
Microsoft.Extensions.Options.ConfigurationExtensions v 1.0.0

### ISSUE THREAD

**Issue by mbharodia** [aspnet/Templates#652]
Earlier I had reference to 1.0.0-rc2-final for Microsoft.Extensions.Options.ConfigurationExtensions. 

As 1.0.0 is official now I have upgraded the package to 1.0.0. As soon as I did it, the build failed. The following extension method did not work. (Note: I have also upgraded other packages to 1.0.0. I was trying to move from beta to 1.0.0. So whatever seemed to be upgradable, I upgraded that)

services.Configure<EmailSettings>(Configuration.GetSection("EamilSettings"), true);

![2016-07-13 16_23_52-ccclients - microsoft visual studio](https://cloud.githubusercontent.com/assets/10344641/16821921/6234f4c8-4916-11e6-93bc-d031c38cec61.png)

I am sure I am missing something. I really appreciate any help. Thank you very much.

**Comment by phenning** [comment]
@mbharodia Were you still blocked by this issue?

**Comment by mbharodia** [comment]
No. Thanks for have a look at it.
