### ISSUE TITLE
Views in Areas are not getting published

### ISSUE THREAD

**Issue by rynowak** [aspnet/Templates#654]
Here's the globs we have in publish options for the Web Application template:

```
"publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "Areas/**/Views",
      "appsettings.json",
      "web.config"
    ]
  }
```

The problem with this is that the glob `Areas/**/Views` is not getting published, none of it! This is a CLI bug, tracked here: https://github.com/dotnet/cli/issues/3286

We want to try and make a tactical fix to work around the problem. I've tested `Areas/**/*.cshtml` and `Areas/*/Views/**/*.cshtml`.

**Comment by mlorbetske** [comment]
TFS Bug#240969

**Comment by rynowak** [comment]
Best suggestion we have so far is to replace `Areas...` and `Views` with `**/*.cshtml`

**Comment by mlorbetske** [comment]
cc @phenning
