### ISSUE TITLE
Incorrect wording in gulp item template comment

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Templates#657]
Add a new `gulpfile.js` via the Gulp Configuration File item template, and notice the following comment at the top of the file:

``` javascript
/*
This file in the main entry point for defining Gulp tasks and using Gulp plugins.
Click here to learn more. http://go.microsoft.com/fwlink/?LinkId=518007
*/
```

The third word of the first sentence is "in". It should be replaced with "is".

**Comment by mlorbetske** [comment]
@scottaddie thanks for pointing this out :)

**Comment by phenning** [comment]
Fix checked into WTE branch
