### ISSUE TITLE
Add support for Subresource integrity to external javascript files

### ISSUE THREAD

**Issue by blowdart** [aspnet/Templates#667]
See https://www.troyhunt.com/protecting-your-embedded-content-with-subresource-integrity-sri/

**Comment by mlorbetske** [comment]
Pretty much the work here is:
- Find all CDN script references in all templates
- Compute hashes for the expected contents for all those files
- Use the methodology mentioned in the link to get supported browsers to do the validation of the script before validation
- Add a fallback to the production script references to point to the app local copy of the script
