### ISSUE TITLE
External Logins does not set the Email

### ISSUE THREAD

**Issue by rustd** [aspnet/Templates#67]
- Enable Facebook Login
- Login using Facebook for the first time
- Email field is blank. It should be set from what we got from Facebook

**Comment by peterblazejewicz** [comment]
``` cs
app.UseFacebookAuthentication(options =>
            {
                options.AppId = Configuration["Authentication:Facebook:AppId"];
                options.AppSecret = Configuration["Authentication:Facebook:AppSecret"];
                options.Scope.Add("email");
            });
```

http://docs.asp.net/en/latest/security/authentication/sociallogins.html
The documentation does not mention that requirement. That's not guaranted that email will be returned from FB.

**Comment by Eilon** [comment]
Moved to https://github.com/aspnet/templating/issues/127
