### ISSUE TITLE
[parity] Create .net core templates

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/Templates#671]
We should create the following templates:
- .NET Core console app
- .NET Core class library
- ASP.NET Core templates

**Comment by peterblazejewicz** [comment]
Do you mean the same as in dotnet/cli (for `new` command)? I was wondering about this topic recently Thanks!

**Comment by sayedihashimi** [comment]
@peterblazejewicz yes. Eventually I'm hoping to integrate `dotnet new` (or it's components to be more precise) into `yo aspnet`, but we are not quite there yet.

**Comment by phenning** [comment]
@sayedihashimi Closing this, as I think we have achieved all this given the scope
