### ISSUE TITLE
Remove web.config from ASP.NET Core templates

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Templates#674]
In #422 @sayedihashimi  hints that _web.config_ is needed for deployment to IIS. But `Debug=false` has no impact on an ASP.NET Core app.

I like the opt in philosophy of ASP.NET Core, can we do the same with the templates?  When do you need _web.config_?

**Comment by Rick-Anderson** [comment]
cc @Tratcher - I need to explain when/why you would need _web.config_

**Comment by Tratcher** [comment]
web.config is required to run the app in IIS/Express. It turns on the AspNetCoreModule in IIS to launch your application. It may also be used to configure other IIS settings/modules.

**Comment by Rick-Anderson** [comment]
Does IIS/Express mean IIS and IIS-Express? I delete it and it doesn't seem to have any impact on IIS-Express.

So if you're deploying to IIS, you need it to enable AspNetCoreModule .
You can configure modules or settings in IIS, but  typically you won't need to do that for new ASP.NET Core apps.

**Comment by Tratcher** [comment]
Yes, IIS and IIS-Express. If the file is missing I recall that VS recreates it for you.

**Comment by Rick-Anderson** [comment]
@Tratcher  Thanks - all this from customer questions and I'm adding it to the config doc.
