### ISSUE TITLE
Add a friendly 404 route/page

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Templates#675]
The web application (starter web) template does not have a friendly 404 experience, you end up with a blank page. There should be a default route/page with a simple message similar to the Error page.

**Comment by Tratcher** [comment]
@rynowak

**Comment by peterblazejewicz** [comment]
https://github.com/h5bp/html5-boilerplate/blob/master/dist/404.html
https://github.com/h5bp/html5-boilerplate/blob/master/dist/404.html#L60
https://github.com/h5bp/html5-boilerplate/pull/1443#issuecomment-25915714
https://webmasters.googleblog.com/2008/08/make-your-404-pages-more-useful.html
https://blogs.msdn.microsoft.com/ieinternals/2010/08/18/friendly-http-error-pages/
hth

**Comment by mlorbetske** [comment]
@sayedihashimi can you take a look at this?

**Comment by sayedihashimi** [comment]
@Damianedwards any thoughts about what default content we want for a 404 page? If not I can work on a proposal and send it your way.

**Comment by Eilon** [comment]
This issue was moved to aspnet/templating#104
