### ISSUE TITLE
Exclude _references.js artifact from publish

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Templates#676]
A `_references.js` file is included in the "Web Application" project template's `wwwroot` folder. It's currently being published with the application artifacts; however, it provides no value outside of the IDE. I was going to submit a PR for this, but I know that things are shifting from `project.json` back to the MSBuild/csproj world. To resolve this issue in `project.json`, the following could be added to the `publishOptions` property:

``` json
    "exclude:": [
      "wwwroot/_references.js"
    ],
```

Can this minor tweak be addressed when things are migrated back to csproj?

**Comment by mlorbetske** [comment]
@phenning let's add this to the globbing patterns in the template to remove the CopyToPublish metadata

**Comment by eriksendc** [comment]
Hi All,

Just wanted to give a +1 to the general idea of not publishing this artifact by default (when creating a new project from scratch). We're in the process of upgrading from rc1 to 1.0.1 RTM and hit this. We'll use the "exclude" section as mentioned above for now. Thanks for having this issue out there, and thank goodness for Google! :)

It'd be great to get an announcement once we change from excluding via project.json to the csproj.

Thanks!
-Brian Eriksen

**Comment by mlorbetske** [comment]
Just merged the PR to exclude this from publish by default. Thanks for pointing this out! This change should be available in the next release of Visual Studio 2017
