### ISSUE TITLE
Update UserSecrets code in Startup.cs to pass in the assembly

### ISSUE THREAD

**Issue by Eilon** [aspnet/Templates#694]
We need to update the code in Startup.cs that adds the UserSecrets config provider to call the 1.0.1 overload that takes in the assembly identity (i.e. `typeof(Startup).GetTypeInfo().Assembly`). Need to make sure this is the right code for both .NET Core and .NET Framework.

Note: We can't use any new 1.0.3 User Secrets config APIs because those don't ship in VS yet.

cc @muratg @DamianEdwards @barrytang @seancpeters

**Comment by Eilon** [comment]
The branch to check this into for this release is: `rel/tools-1.0.0-preview3`

**Comment by natemcmaster** [comment]
> We can't use any new 1.0.3 User Secrets config APIs because those don't ship in VS yet.

The overload that takes `typeof(Startup).GetTypeInfo().Assembly` is in "1.0.3" release. The only other API we have is `.AddUserSecrets(string userSecretId)`.

**Comment by DamianEdwards** [comment]
Eilon and I looked in what we thought was the 1.0.1 branch and saw the API there. We're we wrong?

**Comment by natemcmaster** [comment]
The "rel/1.0.1" version of aspnet/Configuration is in the November "1.0.3" release. Repos version unto themselves.

**Comment by Eilon** [comment]
Yeah oops, closing this because we can't do it.

We'll look at patching 1.0.3 to do some smarter lookups instead.

**Comment by natemcmaster** [comment]
Do templates currently scaffold Microsoft.Extensions.Configuration.UserSecrets 1.0.0 for MSBuild? If so, that package won't work at all as there is no longer a file named "project.json".

**Comment by Eilon** [comment]
@natemcmaster right, we'll do a patch for "1.0.3" to do a smarter lookup (e.g. scan all loaded assemblies for the new attributes and use the 1 we find. If there are 0 or there are more than one, throw.)
