### ISSUE TITLE
Add a readme.md for dotnet new scenarios

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/Templates#700]
In VS we have a new start page for ASP.NET projects, the result is that the Project_Readme.html will  **not** be a part of the project. For dotnet new scenarios we should create a `readme.md`.

**Comment by mlorbetske** [comment]
@sayedihashimi what should the content for these be?

**Comment by peterblazejewicz** [comment]
@mlorbetske the generator content used scrapped version of html page converted to markdown:
https://github.com/peterblazejewicz/missing-aspnet-readme

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/aspnet/Templates/blob/dev/README.md.
