### ISSUE TITLE
update fwlinks on templates

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Templates#709]
Create a new web app core project with VS 2015 (or 2017 RC 1)

Conceptual overview of what is ASP.NET Core - http://go.microsoft.com/fwlink/?LinkId=518008
That should be changed to
Conceptual overview of ~~what is~~ ASP.NET Core
I think the link you want is https://docs.microsoft.com/en-us/aspnet/core/

Working with Data -> http://go.microsoft.com/fwlink/?LinkId=398602
should go to https://docs.microsoft.com/en-us/ef/ 
Check with @rowanmiller  where this should go 

Add a Controller and View - http://go.microsoft.com/fwlink/?LinkID=398600
should go to https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc

Add an appsetting in config and access it in app.  Remove this link - it's not useful

**Comment by sayedihashimi** [comment]
I have made the following FWLink updates
518008 -> https://docs.microsoft.com/en-us/aspnet/core/
398602 -> https://docs.microsoft.com/en-us/ef/
398600 -> https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc

@Rick-Anderson where are you seeing the text "Conceptual overview of what is ASP.NET Core"?

**Comment by rowanmiller** [comment]
The suggested EF link is correct.

**Comment by Rick-Anderson** [comment]
LGTM

**Comment by phenning** [comment]
@Rick-Anderson, can you clarify 

"Add an appsetting in config and access it in app. Remove this link - it's not useful"

Which fwlink are you referring to here, do we want to link removed, or just updated?

**Comment by Rick-Anderson** [comment]
Sorry, my bad. In the template generated web app
_Views\Home\Index.cshtml_
remove the following:
            `<li><a href="http://go.microsoft.com/fwlink/?LinkID=699562">Add an appsetting in config and access it in app.</a></li>`
