### ISSUE TITLE
Add <PackageTargetFallback> to .NETCore Console App template

### ISSUE THREAD

**Issue by JoyceLiang** [aspnet/Templates#710]
Could you add below Fallback element to the template. 
`<PropertyGroup>
    <PackageTargetFallback>$(PackageTargetFallback);portable-net45+win8+wp8+wpa81;   </PackageTargetFallback>
  </PropertyGroup>`

**Comment by srivatsn** [comment]
@yishaigalatzer @rrelyea @dsplaisted @nguerrera thoughts?

**Comment by nguerrera** [comment]
I don't think this belongs in the templates. Packages using portable profiles that are compatible with netstandard/netcoreapp should be made to just work by some means other than an artifact in the user's project file. cc @terrajobst

**Comment by AArnott** [comment]
Thanks for looking, @nguerrera. The idea of getting the build to automatically know what all the fallback frameworks are without the user (Or template) having to specify them sounds good to me.
We have a significant Connected Service feature blocked on this, so getting this resolved in d15prerel soon would calm my nerves significantly for our next prerelease.

**Comment by nguerrera** [comment]
@AArnott Given that, I'd be OK with adding this to the template as an unblocking mechanism for you, but we should be tracking to get to the right solution by RTW.

**Comment by srivatsn** [comment]
If we are putting in temp measures I'd rather we put that in the SDK so that we don't pollute users' csproj files.

**Comment by davidfowl** [comment]
Ugh can we not do this and just fix those packages. It's been over a year now. Let's make it a high priority isssue to track down those packages and fix them.

**Comment by davidfowl** [comment]
@aarnot which specific packages need these in our default experiences

**Comment by srivatsn** [comment]
Do we have a list? Last someone checked (for web projects) it was just MEF

**Comment by dsplaisted** [comment]
Why don't we just fix it in NuGet?  There's no reason you should need a workaround like this to use a perfectly functioning portable NuGet package.

**Comment by davidfowl** [comment]
Even the seemingly "correct" imports can break your project. They are also order sensitive and depending on the packages you have installed and the order of imports declared, you can get different results. They are a fixed number of imports that are safe (the ones that match exact pcl profile numbers). Anything else is a guessing game.

**Comment by nguerrera** [comment]
> They are a fixed number of imports that are safe (the ones that match exact pcl profile numbers)

We should make this fixed set just work.

**Comment by dsplaisted** [comment]
See also dotnet/sdk#391

**Comment by AArnott** [comment]
@JoyceLiang Can you please provide the transitive closure of nuget packages that you need to install so that @davidfowl can see which ones need to be updated to support the new nuget packaging structure?

I would sure like nuget to support backward compatibility in packaging structure as well. Having nuget package authors repeatedly republish effectively the same version, just to support newer frameworks or packaging conventions seems like a never-ending battle.

**Comment by davidfowl** [comment]
@nguerrera one thing I like about imports is that we can do this in the default props without baking it into nuget. Much easier to change.

@AArnott, yes that's why we made netstandard.

**Comment by dsplaisted** [comment]
@davidfowl 

> @nguerrera one thing I like about imports is that we can do this in the default props without baking it into nuget. Much easier to change.

It's easier to change, but I think if the logic is in NuGet then I think we can make it work better than restricting to the PCL profiles that exactly match a .NET Standard version, and without worrying about the ordering of PackageTargetFallbacks.  Also, NuGet is basically becoming the source of truth for determining whether one target framework can reference another, so it makes sense that this would go there.

> @AArnott, yes that's why we made netstandard.

[![Fortunately, the charging one has been solved now that we've all standardized on mini-USB. Or is it micro-USB? Shit.](http://imgs.xkcd.com/comics/standards.png)](https://xkcd.com/927/)

I'm sorry, I couldn't help myself :-)

**Comment by davidfowl** [comment]
😁, the nuget team can determine how risky the change is. I'm merely a consultant at this point. It should be safe to add though.

**Comment by AArnott** [comment]
So what is it going to be? I agree adding the project template tag is sub-par. It's quick and easy, but better solutions are:

1. Set the property in the .targets/.props file
1. Enhance the NuGet engine to work better with these legacy packages.
1. Get the several package authors to re-publish with support for netstandard.

I don't know which of these we can get done in a short period of time. We can and will push for the last option with the Azure team. In the meantime, can we hope for one of the first two options to be taken care of by someone on this thread?

**Comment by terrajobst** [comment]
Should this be closed now? I think we a different route.

**Comment by AArnott** [comment]
I don't think this is resolved yet. Last I tried, this property is still required to install PCL packages into netstandard or netcoreapp projects.

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/aspnet/Templates/blob/dev/README.md.
