### ISSUE TITLE
Add global.json back to CSPROJ based projects

### ISSUE THREAD

**Issue by muratg** [aspnet/Templates#716]
Per Zlatko, this is still supported - at least the "sdk" property.

This is required on environments where multiple SDKs exists. Like Antares.

**Comment by muratg** [comment]
(Also, could someone from the Tooling team file the corresponding issue on CLI templates?  Not sure what repo they're using for the templates.

cc @blackdwarf

**Comment by peterblazejewicz** [comment]
> (Also, could someone from the Tooling team file the corresponding issue on CLI templates? Not sure what repo they're using for the templates.

https://github.com/dotnet/cli/tree/rel/1.0.0/src/dotnet/commands/dotnet-new
