### ISSUE TITLE
Templates should use bootstrap columns to set form element width, not CSS max-width property

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Templates#723]
Setting the `max-width` of form elements is not the recommend way to set form elements width when using bootstrap.

They currently do this [here](https://github.com/aspnet/Templates/blob/dev/src/Rules/StarterWeb/IndividualAuth/wwwroot/css/site.css#L17).

Instead, they should be putting form elements in `<div>` elements and use bootstrap column width classes to set the desired width, in accordance with the [recommendations in the bootstrap documentation](http://getbootstrap.com/css/#forms-control-sizes). Failure to do this results in other features of bootstrap not working correctly, e.g. [input groups](http://getbootstrap.com/components/#input-groups).

![image](https://cloud.githubusercontent.com/assets/249088/20539287/5c44f0c2-b0a9-11e6-9a5a-06a16215c9a6.png)

**Comment by Eilon** [comment]
This issue was moved to aspnet/templating#101
