### ISSUE TITLE
Incorrect default file names used for item templates

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Templates#736]
In VS 2017 RC, the default file names used for many of the item templates (e.g., **Visual C#** --> **ASP.NET Core** --> **Web** --> **General**) are incorrectly suffixed with "1". For example, add a new "npm Configuration File" item template to an ASP.NET Core project and notice that the default file name provided in the *Name* textbox is `package1.json`. Since no `package.json` file exists on disk, this behavior is unexpected. Furthermore, a file name of `package1.json` wouldn't be recognized by npm.

Follow these steps to reproduce:
1.	Create a new "ASP.NET Core Web Application (.NET Core)" project using the "Web Application" template in VS 2017 RC.
2.	Add a new `package.json` file via the "npm Configuration File" item template.
3.	Notice that the default file name VS wants to use is `package1.json`:
![item_template_defect](https://cloud.githubusercontent.com/assets/10702007/20932751/5e61c2d4-bb9b-11e6-9f6c-201b0805aa6b.png)

**Comment by phenning** [comment]
This is resolved in the next VS 2017 release

**Comment by scottaddie** [comment]
@mlorbetske @phenning Thank you for the quick turnaround on this one!
