### ISSUE TITLE
Wiki update needed to "How to run generated samples"

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Templates#766]
The Wiki's **Command Line** section [here](https://github.com/aspnet/Templates/wiki/Building-and-Running#command-line) references an invalid directory path. Replace the following:

C:\git\Templates\intermediate\\**Test**\StarterWeb [dev]> dotnet run

With this:

C:\git\Templates\intermediate\\**ProjectTemplates**\StarterWeb [dev]> dotnet run

![projecttemplates](https://cloud.githubusercontent.com/assets/10702007/21361892/9a444d88-c6ab-11e6-8e2a-5ff63097aaaf.png)

The same folder update should be made in the **Visual Studio** section [here](https://github.com/aspnet/Templates/wiki/Building-and-Running#visual-studio).

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/aspnet/Templates/blob/dev/README.md.
