### ISSUE TITLE
Update Template dependencies table in Wiki

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Templates#767]
The **Template dependencies** table [here](https://github.com/aspnet/Templates/wiki/Template-dependencies) still assumes that `gulpfile.js` is part of the project templates. In addition to the "from gulp" bullet point, the following 5 table rows should be removed:
1. gulp
2. rimraf
3. gulp-concat
4. gulp-cssmin
5. gulp-uglify

**Comment by phenning** [comment]
Updated!
