### ISSUE TITLE
Make templates StyleCop ready

### ISSUE THREAD

**Issue by olivif** [aspnet/Templates#768]
I enabled StyleCop on the sample ASP.NET Core web app and I have 800 StyleCop warnings 😢 

It would be awesome if these were StyleCop ready.

**Comment by phenning** [comment]
Classes of Stylecop warnings we are seeing:

warning SA1652: Enable XML documentation output
warning SA1633: The file header is missing or not located at the top of the file.
warning SA1200: Using directive must appear within a namespace declaration
warning SA1101: Prefix local calls with this
warning SA1513: Closing brace must be followed by blank line (Individual Auth Account Controller)
warning SA1120: Comments must contain text (controller action method comments)
warning SA1005: Single line comment must begin with a space. (commented out code)
warning SA1309: Field '_userManager' must not begin with an underscore (all controller fields)
warning SA1201: A enum should not follow a method  (ManageMessageId enum in ManageController.cs)
warning SA1205: Partial elements must declare an access modifier (ApplicationDbContextModelSnapshot)
warning SA1516: Elements must be separated by blank line
warning SA1124: Do not use regions (Helper region in AccountController)

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/aspnet/Templates/blob/dev/README.md.
