### ISSUE TITLE
Update css file for project overview page

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/Templates#776]
We have a new css file that should be used in the Project Overview page. @mlorbetske has the .css file in his inbox. 

I've attached the .css file at [Provider_stylesheet.css.txt](https://github.com/aspnet/Templates/files/683603/Provider_stylesheet.css.txt). Note: to upload here I had to change the extension from `.css` to `.css.txt`.

**Comment by phenning** [comment]
Fixed
