### ISSUE TITLE
Remove Microsoft.NETCore.App package reference from templates

### ISSUE THREAD

**Issue by dsplaisted** [aspnet/Templates#777]
As of https://github.com/dotnet/sdk/pull/450, the Microsoft.NETCore.App package will be referenced implicitly when targeting netcoreapp.  So the PackageReference for it can be removed from the templates.

@mlorbetske @vijayrkn

**Comment by vijayrkn** [comment]
@phenning

**Comment by mlorbetske** [comment]
This is done and inserted, available in builds 26015.6 and higher @dsplaisted
