### ISSUE TITLE
Add a web.config item template

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/Templates#778]
We should add item template for the `web.config` file. I'm still working on finalizing the content, but my proposal for file content is below. Note: related to this we are hoping to make some updates where the `web.config` will not be required, and at that time we will be removing it from the project template. So when that happens we certainly need an item template for this.

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>


  <!-- To customize the asp.net core module uncomment and edit the following section. 
  For more info see https://go.microsoft.com/fwlink/?linkid=838655 -->
  <!--
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified"/>
    </handlers>
    <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
  </system.webServer>
  -->

</configuration>
```

**Comment by phenning** [comment]
Fix checked in for RTW
