### ISSUE TITLE
ExternalLoginConfirmation breaks if the username is already taken

### ISSUE THREAD

**Issue by blowdart** [aspnet/Templates#793]
Copied from https://github.com/aspnet/Identity/issues/1080

Repro:

Login with a new Facebook account
In the "ExternalLoginConfirmation" page enter an email that already exists on the system
Press Register
The page reloads, the validation error is displayed saying "User name 'blah@example.com' is already taken." and all of the ViewData is now lost including the ReturnUrl of the form and the LoginProvider used in the h2 and intro paragraph.

**Comment by Eilon** [comment]
This issue was moved to aspnet/templating#98
