### ISSUE TITLE
AccountController ForgotPassword should check the UserId before ResetPassword

### ISSUE THREAD

**Issue by HaoK** [aspnet/Templates#804]
Moved from: https://github.com/aspnet/Home/issues/1911#issuecomment-275184195

Today we are passing in the userId from ForgotPassword:  https://github.com/aspnet/Templates/blob/dev/src/Rules/StarterWeb/IndividualAuth/Controllers/AccountController.cs#L282

But not using it when we reset: https://github.com/aspnet/Templates/blob/dev/src/Rules/StarterWeb/IndividualAuth/Controllers/AccountController.cs#L321

We should check that the User with userId matches the user that is retrieved via FindByEmail as well.

cc @blowdart

**Comment by Eilon** [comment]
This issue was moved to aspnet/templating#96
