### ISSUE TITLE
Error on F5 when using Work or School Single Org with Read

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/Templates#808]
Here's an issue from an internal partner, we have an existing email thread that a few of us are on.

I am trying to create a simple web application and register it with an Azure Active directory like I've done many times in the past. I've started to run in to problems, not sure if its because the framework version or what it may be.

Here are my steps.

1. Create a new Azure AD, add a new user.
2. Open Visual Studio 2015 Update 3 as an administrator and choose File | New | Project | Templates | Visual C# | Cloud | ASP.Net Web Application (.Net Framework). I am using version 4.6 of the .Net Framework.
3. Choose an MVC style app.
4. Select the Change Authentication button and choose Work or School accounts. Here, I will enter my full domain name like xxxxxxxxxx.onmicrosoft.com, Single Cloud Organization and Read directory data. I sign in to Azure.
5. The VS app finishes the creation process. I can look at my web.config file and see the changes that have been made for connectivity to Azure AD.
6. When I select F5 to run the app, I get this error regarding System.Spatial:

![spatial](https://cloud.githubusercontent.com/assets/1283154/22492588/65654dba-e7df-11e6-8603-780d1bbf862c.jpg)

From Vittorio I heard that the “spatial” issue can be solved by simply deleting the binding, given that it isn’t really used.

**Comment by phenning** [comment]
Note, that this is only an issue with the legacy templates, which are not maintained in the repo.

**Comment by Eilon** [comment]
This issue was moved to aspnet/templating#95
