### ISSUE TITLE
Add Activity information to generated error page

### ISSUE THREAD

**Issue by glennc** [aspnet/Templates#827]
Part of finishing the e2e for https://github.com/aspnet/Hosting/issues/939 we want to modify the generated error page in ASP.NET Core applications to contain information about the current activity.

**Comment by glennc** [comment]
@phenning would this be you?

**Comment by phenning** [comment]
@glennc  I was looking at the linked bug, but I wasn't able to see what exactly we need to do here. Has anyone on the runtime team done anything meaningful with the existing error page which shows how we want to update the templates?

**Comment by Eilon** [comment]
This issue was moved to aspnet/templating#93
