### ISSUE TITLE
StarterWeb template isn't bundling on build

### ISSUE THREAD

**Issue by kstreith** [aspnet/Templates#835]
The StarterWeb template includes bundleconfig.json, site.min.js and site.min.css. Yet, the templates aren't performing bundling on build or publish to create updated versions of the minified files.

It appears the fix is to add `<PackageReference Include="BuildBundlerMinifier" Version="__version__" />` to the .csproj. Is this an accidental oversight with the templates?

I'm using the templates in VS2017 Final.

**Comment by mlorbetske** [comment]
cc @madskristensen

**Comment by shravan2x** [comment]
I have the same problem (And was just about to post an issue myself). This works too:

```
<Target Name="PrepublishScript" BeforeTargets="PrepareForPublish">
    <Exec Command="SET PATH=$(ExternalToolsPath);%PATH% &amp;&amp; bower install" />
    <Exec Command="dotnet bundle" />
</Target>
```

**Comment by sayedihashimi** [comment]
I'm not sure if calling Exec here to set the path will impact the second call to `dotnet bundle`.

**Comment by Eilon** [comment]
This issue was moved to aspnet/templating#89
