### ISSUE TITLE
Can not open in Visual Studio for Mac

### ISSUE THREAD

**Issue by daspuru** [aspnet/Templates#839]
Hi, 

Is there a way to open these solutions in Visual Studio for Mac?

Opening Templates.Test gives the following errors (See image below)

<img width="575" alt="screen shot 2017-04-14 at 12 18 41 am" src="https://cloud.githubusercontent.com/assets/24983936/25033918/fa7cb7ca-20a7-11e7-97f3-5e539d4161d2.png">

Thanks

**Comment by mlorbetske** [comment]
It looks like `dotnet migrate` should be run on these projects to create csproj files for VS to open. It'd probably be ideal if it ran it for you.

@phenning it looks like there are `xproj`s being generated here - is that right?

/cc @mhutch

**Comment by mhutch** [comment]
Yes, VS for Mac does not support project.json, you should upgrade to csproj.

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/aspnet/Templates/blob/dev/README.md.
