### ISSUE TITLE
Core MVC template database file name starts with a backslash on Linux/Mac

### ISSUE THREAD

**Issue by DesktopMan** [aspnet/Templates#840]
From the template's appsettings.json:

```
"DefaultConnection": "DataSource=.\\test.db"
```
This has two presumably unintentional consequences: The file becomes hidden and the name starts with a backslash. My students had trouble finding the file to inspect it until I pointed this out.

**Comment by Eilon** [comment]
This issue was moved to aspnet/templating#85
