### ISSUE TITLE
Nav bar covers top of screen

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Templates#843]
![image](https://cloud.githubusercontent.com/assets/3605364/25300177/126fdf9e-26a5-11e7-9690-747ab1e80adb.png)

To repro:

Create a new MVC web app with all the defaults. Narrow the screen and hit the nav bar.

#626 might make this moot.

If you don't want to change the template we should at least document how you could change this. 

cc  @Drek1Droid

**Comment by Drek1Droid** [comment]
If you have enough links, and a long enough email address used in the greeting on the nav bar, you don't have to hit the nav bar to see the effect as simply narrowing the screen will cause the nav bar to double in height, obscuring the body content below.
Normal:

![nav1](https://cloud.githubusercontent.com/assets/8053879/25305128/9b150e48-272a-11e7-87a1-63aed4feddfa.PNG)
After narrowing:

![nav](https://cloud.githubusercontent.com/assets/8053879/25305132/9f558cee-272a-11e7-8af2-b79f3fceba83.PNG)

**Comment by Eilon** [comment]
This issue was moved to aspnet/templating#84
