### ISSUE TITLE
Post test 

### ISSUE THREAD

**Issue by a-elnajjar** [aspnet/Templates#847]
Hi asp.net Team;
I see your Templates/test/Microsoft.Web.Templates.Web.Tests/WebAPITests.cs only have tow test methods for testing and verify GET Web API is working. I want to ask can I add testing and verify methods for POST Web API?

**Comment by mlorbetske** [comment]
Sure, we'd love a PR for this

**Comment by Eilon** [comment]
This issue was moved to aspnet/templating#83
