### ISSUE TITLE
File new default names inconsistency.

### ISSUE THREAD

**Issue by mlorbetske** [aspnet/Templates#850]
_From @Bartmax on July 24, 2015 2:48_

All items in the file new dialog (client side) default names kind of follows a pattern but it's not consistent:

StyleSheet.css
JavaScript.js
htmlpage.html (all lowercase)
CoffeeScript.coffee
json-schema.json
package.json
etc.

Some must have a specific name (like package.json) while others just reflect the file type. 

I see 2 inconsistencies here:

1) casing is inconsistent.
2) TypeScript it suggest file.ts instead of TypeScript.ts

_Copied from original issue: aspnet/Tooling#118_

**Comment by mlorbetske** [comment]
_From @sayedihashimi on July 24, 2015 3:22_

@rustd?

**Comment by mlorbetske** [comment]
_From @sayedihashimi on June 14, 2016 20:25_

TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231271&fullScreen=false&_a=edit">231271</a>

**Comment by mlorbetske** [comment]
_From @sayedihashimi on January 9, 2017 21:43_

Sorry for the delay here. We haven't improved this yet, but it's on my radar.

**Comment by mlorbetske** [comment]
_From @webtools-bot on March 28, 2017 18:5_

The GitHub Issue Tracker for the aspnet/Tooling repo is being deprecated in favor of [Visual Studio's Report a Problem tool](https://developercommunity.visualstudio.com/).

If this issue is still a problem with the RTW release of Visual Studio 2017, please report a new issue using the [Report a Problem tool](https://developercommunity.visualstudio.com/). While you can still use .NET Core and ASP.NET Preview tools with Visual Studio 2015, Visual Studio 2017 is now the officially supported tool for developing .NET Core and ASP.NET Core projects. 

By using the [Report a Problem tool](https://developercommunity.visualstudio.com/) (available in both VS 2017 and VS 2015), you can collect detailed information about the problem, and send it to Microsoft with just a few button clicks. See [Visual Studio's Talk to Us page](https://docs.microsoft.com/en-us/visualstudio/ide/talk-to-us) for more details.

Please use the discussion topic [here](https://github.com/aspnet/Tooling/issues/1026) for feedback and questions on the deprecation of this issue tracker. Thanks!

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/aspnet/Templates/blob/dev/README.md.
