### ISSUE TITLE
Why do non-sentence headers end in a period?

### ISSUE THREAD

**Issue by SteveDesmond-ca** [aspnet/Templates#851]
See https://github.com/aspnet/Templates/blob/dev/src/Rules/StarterWeb/IndividualAuth/Views/Account/ResetPasswordConfirmation.cshtml as an example -- almost all the `<h1>`s have periods after them, when they should more likely be Title Case with no period.

**Comment by mlorbetske** [comment]
These have been fixed in dotnet/templating (where the templates are being built from for the time being)
