### ISSUE TITLE
Razor Page templates use fully qualified name 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Templates#858]
The constructor uses the FQN when it's not necessary. For example:

See [Pages/Movie/Index.cshtml.cs](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie/Pages/Movie/Index.cshtml.cs#L14-L16)

`using RazorPagesMovie.Models;` is in the template.

To repro - follow the [Razor Pages tutorial](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model)

**Comment by mlorbetske** [comment]
This issue was moved to aspnet/Scaffolding#585
