### ISSUE TITLE
Cannot force version of the template to install

### ISSUE THREAD

**Issue by marcusien** [aspnet/Templates#867]
Hi,

Maybe there's something not documented but I'd like to install a version of my own template in a specific version.

We are creating our own template for our project and we create prerelease packages for our template using semver. The problem is with "dotnet new -i" command, we cannot specify a specific version

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/aspnet/Templates/blob/dev/README.md.
